'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),M=require('../ai-literacy-lab.js');let passed=0,n=0;
function test(name,fn){try{fn();passed++}catch(e){console.error(`FAIL: ${name}\n${e.stack}`);process.exitCode=1}}
function throws(fn,code){assert.throws(fn,e=>e&&e.code===code)}
const student={userId:'student-ai',role:'student',tenantId:'ai-school'},teacher={userId:'teacher-ai',role:'teacher',tenantId:'ai-school'},tutor={userId:'tutor-ai',role:'verified_tutor',tenantId:'ai-school'},admin={userId:'admin-ai',role:'platform_admin',tenantId:'ai-school'},id=()=>`ai-${++n}`;
for(const [name,list,count] of [['dimensions',M.AILiteracyDimension,4],['levels',M.AILiteracyProgressionLevel,3],['steps',M.AILiteracyLearningCycleStep,6],['cycle statuses',M.AILiteracyLearningCycleStatus,7],['progress statuses',M.AILiteracyProgressStatus,6],['flags',M.AILiteracyFeatureFlag,8],['blocks',M.AILiteracyCompetencyBlocks,12],['routes',M.AILiteracyRoutes,14]])test(`${name} exact count`,()=>assert.strictEqual(list.length,count));
test('dimensions exact',()=>assert.deepStrictEqual(M.AILiteracyDimension,['HUMAN_CENTRED_MINDSET','ETHICS_OF_AI','AI_TECHNIQUES_AND_APPLICATIONS','AI_SYSTEM_DESIGN']));
test('levels exact',()=>assert.deepStrictEqual(M.AILiteracyProgressionLevel,['UNDERSTAND','APPLY','CREATE']));
test('cycle exact',()=>assert.deepStrictEqual(M.AILiteracyLearningCycleStep,['STUDENT_ATTEMPT','AI_GUIDED_SUPPORT','VERIFICATION','STUDENT_REVISION','STUDENT_EXPLANATION','REFLECTION_AND_DISCLOSURE']));
test('principle exact',()=>assert.strictEqual(M.COPY.principle,'StudySpark should help the student remain the thinker, author, and decision-maker.'));
test('opening exact',()=>assert.strictEqual(M.COPY.opening,'AI can help you learn, but it can also produce incorrect, biased, incomplete, or unsupported information. This lab will teach you how to remain the thinker, author, and decision-maker.'));
test('attribution exact',()=>assert.strictEqual(M.COPY.attribution,'StudySpark’s AI Literacy curriculum structure is informed by UNESCO’s AI Competency Framework for Students. StudySpark is not UNESCO-certified or officially endorsed by UNESCO.'));
const map=M.getAILiteracyFrameworkMap();
test('framework 2024',()=>assert.strictEqual(map.reference.publicationYear,2024));test('framework reference only',()=>assert.strictEqual(map.reference.referenceType,'CURRICULUM_REFERENCE'));test('not credential',()=>assert.strictEqual(map.reference.officialCredential,false));test('not endorsement',()=>assert.strictEqual(map.reference.endorsement,false));test('no logo',()=>assert.strictEqual(map.reference.logoUsed,false));
for(const d of M.AILiteracyDimension)test(`${d} has three levels`,()=>assert.deepStrictEqual(map.competencyBlocks.filter(x=>x.dimension===d).map(x=>x.progressionLevel),M.AILiteracyProgressionLevel));
for(const l of M.AILiteracyProgressionLevel)test(`${l} has four blocks`,()=>assert.strictEqual(map.competencyBlocks.filter(x=>x.progressionLevel===l).length,4));
for(const b of map.competencyBlocks){test(`${b.title} connected`,()=>assert.strictEqual(b.connected,true));test(`${b.title} iterative`,()=>assert.strictEqual(b.iterative,true))}
const lab=M.getAILiteracyLab(student);test('lab title',()=>assert.strictEqual(lab.title,'AI Literacy Lab'));test('three pathways',()=>assert.strictEqual(lab.pathways.length,3));test('six quick actions',()=>assert.strictEqual(lab.quickActions.length,6));test('six learning steps',()=>assert.strictEqual(lab.learningCycle.length,6));test('private lab',()=>assert.strictEqual(lab.private,true));test('privacy notice',()=>assert.ok(lab.privacyNotice.includes('Do not enter passwords')));test('integrity notice',()=>assert.ok(lab.integrityNotice.includes('will not complete graded work')));
for(const level of M.AILiteracyProgressionLevel){const p=M.getAILiteracyPathway({pathway:level},student);test(`${level} functional`,()=>assert.strictEqual(p.functionalStarter,true));test(`${level} four blocks`,()=>assert.strictEqual(p.blocks.length,4));test(`${level} four goals`,()=>assert.strictEqual(p.goals.length,4));test(`${level} back action`,()=>assert.strictEqual(p.backAction,'Return to AI Literacy Lab'))}
const prog=M.getAILiteracyUserProgress(student);for(const field of ['score','promptCount','streak'])test(`progress ${field} absent-value`,()=>assert.strictEqual(prog[field],null));test('progress private',()=>assert.strictEqual(prog.private,true));
const started=M.startAILiteracyModule({pathway:'UNDERSTAND',idempotencyKey:'start-one'},student);test('start contribution required',()=>assert.strictEqual(started.studentContributionRequired,true));test('AI does not complete',()=>assert.strictEqual(started.aiAnswerCompletedModule,false));test('start initial step',()=>assert.strictEqual(started.session.currentStep,'STUDENT_ATTEMPT'));test('start idempotent',()=>assert.strictEqual(M.startAILiteracyModule({pathway:'UNDERSTAND',idempotencyKey:'start-one'},student).duplicatePrevented,true));
test('cannot skip cycle',()=>throws(()=>M.updateAILiteracyLearningCycleStep({sessionId:started.session.id,step:'VERIFICATION',idempotencyKey:id()},student),'CYCLE_STEP_GUARD'));test('contribution guard',()=>throws(()=>M.updateAILiteracyLearningCycleStep({sessionId:started.session.id,step:'AI_GUIDED_SUPPORT',idempotencyKey:id()},student),'STUDENT_CONTRIBUTION_REQUIRED'));
let current=M.updateAILiteracyLearningCycleStep({sessionId:started.session.id,step:'AI_GUIDED_SUPPORT',studentContribution:'my attempt',idempotencyKey:id()},student);test('support after contribution',()=>assert.strictEqual(current.session.currentStep,'AI_GUIDED_SUPPORT'));for(const step of ['VERIFICATION','STUDENT_REVISION','STUDENT_EXPLANATION','REFLECTION_AND_DISCLOSURE'])current=M.updateAILiteracyLearningCycleStep({sessionId:started.session.id,step,idempotencyKey:id()},student);test('ready for reflection',()=>assert.strictEqual(current.session.status,'READY_FOR_REFLECTION'));test('completion needs reflection',()=>throws(()=>M.completeAILiteracyModule({sessionId:started.session.id,idempotencyKey:id()},student),'COMPLETION_REQUIREMENTS'));const done=M.completeAILiteracyModule({sessionId:started.session.id,studentExplanation:'mine',reflection:'checked',idempotencyKey:id()},student);test('complete',()=>assert.strictEqual(done.session.status,'COMPLETED'));test('AI output not sufficient',()=>assert.strictEqual(done.aiOutputAloneSufficient,false));
const app=M.startAIAppropriatenessActivity({},student);test('appropriateness starter',()=>assert.strictEqual(app.activity,'What AI Can and Cannot Do'));test('human judgement question',()=>assert.ok(app.questions.some(x=>x.includes('human judgement'))));test('no sensitive scenario required',()=>assert.strictEqual(app.sensitivePersonalScenarioRequired,false));
const noSource=M.startAIAnswerVerificationActivity({claim:'A claim'},student);test('source not found',()=>assert.strictEqual(noSource.status,'SOURCE_NOT_FOUND'));test('exact no-source wording',()=>assert.strictEqual(noSource.noSourceMessage,'No external source was used for this explanation.'));test('no fabrication',()=>assert.strictEqual(noSource.fabricated,false));const verified=M.startAIAnswerVerificationActivity({claim:'A claim',source:{title:'Synthetic reference',publisherOrAuthor:'Test Author'}},student);test('verified source',()=>assert.strictEqual(verified.status,'SOURCE_VERIFIED'));test('claim linked',()=>assert.strictEqual(verified.source.supportedClaim,'A claim'));
const active=M.startAIUseSelfCheck({context:'ACTIVE_ASSESSMENT'},student);test('active restricted',()=>assert.strictEqual(active.outcome,'ACTIVE_ASSESSMENT_ASSISTANCE_RESTRICTED'));test('no integrity score',()=>assert.strictEqual(active.integrityScore,null));test('no detector proof',()=>assert.strictEqual(active.detectorProof,false));test('no auto report',()=>assert.strictEqual(active.automaticReport,false));test('no final submission',()=>assert.strictEqual(active.finalSubmissionGenerated,false));
const project=M.startAIProjectScopingActivity({problem:'food waste',peopleAffected:'community',privacyRisks:'private data'},student);test('project scoped',()=>assert.strictEqual(project.activity,'Scope an AI Project'));test('no complete project',()=>assert.strictEqual(project.completeProjectGenerated,false));test('authorized data',()=>assert.strictEqual(project.syntheticOrAuthorizedDataRequired,true));test('private project',()=>assert.strictEqual(project.private,true));
const saved=M.createAILiteracyReflection({moduleId:'understand-1',studentReflection:'I checked the uncertainty.',idempotencyKey:id()},student);test('reflection private',()=>assert.strictEqual(saved.reflection.private,true));test('not analytics',()=>assert.strictEqual(saved.ordinaryAnalyticsIncluded,false));test('not logs',()=>assert.strictEqual(saved.ordinaryLogsIncluded,false));test('not training',()=>assert.strictEqual(saved.modelTraining,false));const deleted=M.deleteAILiteracyReflection({reflectionId:saved.reflection.id},student);test('reflection deleted',()=>assert.strictEqual(deleted.activeTextDeleted,true));
test('student teacher preview denied',()=>throws(()=>M.getTeacherAILiteracyOverview(student),'TEACHER_ROLE_REQUIRED'));const tv=M.getTeacherAILiteracyOverview(teacher);for(const f of ['privateReflectionsIncluded','studentPromptsIncluded','conversationsIncluded','integrityScoresIncluded'])test(`teacher ${f} false`,()=>assert.strictEqual(tv[f],false));test('unverified tutor denied',()=>throws(()=>M.getAILiteracyTutorGuidance({...tutor,role:'tutor'}),'VERIFIED_TUTOR_REQUIRED'));const tg=M.getAILiteracyTutorGuidance(tutor);test('tutor cannot complete graded work',()=>assert.ok(tg.prohibited.includes('Complete graded work')));test('tutor no private reflections',()=>assert.strictEqual(tg.privateReflectionsIncluded,false));const room=M.getAILiteracyStudyRoomGuide();test('room no inspection',()=>assert.strictEqual(room.automaticMessageInspection,false));test('room no scores',()=>assert.strictEqual(room.scoreMessages,false));
test('ordinary admin config denied',()=>throws(()=>M.configureAILiteracyLab({flags:{}},{...admin,role:'student'}),'CONFIGURATION_AUTHORITY_REQUIRED'));const off=M.configureAILiteracyLab({organizationId:'disabled-school',flags:{AI_LITERACY_LAB_ENABLED:false}},admin);test('configuration versioned',()=>assert.ok(off.featureFlagVersion>1));const disabled={userId:'disabled',role:'student',tenantId:'disabled-school'};test('disabled Lab guarded',()=>throws(()=>M.getAILiteracyLab(disabled),'AI_LITERACY_CAPABILITY_DISABLED'));test('server authority honest',()=>assert.strictEqual(M.getAILiteracyCapabilities(student).serverAuthoritative,false));test('production enforcement honest',()=>assert.strictEqual(M.getAILiteracyCapabilities(student).productionServerEnforcementAvailable,false));
for(const event of ['AI_LITERACY_LAB_OPENED','PATHWAY_OPENED','STARTER_ACTIVITY_STARTED','STARTER_ACTIVITY_COMPLETED','VERIFICATION_ACTIVITY_COMPLETED','PROJECT_SCOPE_ACTIVITY_COMPLETED','REFLECTION_SAVED','ACCESSIBILITY_MODE_USED','LOW_BANDWIDTH_VERSION_USED'])test(`safe event ${event}`,()=>assert.strictEqual(M.createPrivacySafeAILiteracyAnalyticsEvent(event).event,event));test('raw analytics rejected',()=>throws(()=>M.createPrivacySafeAILiteracyAnalyticsEvent('STUDENT_PROMPT_CAPTURED'),'ANALYTICS_EVENT_REJECTED'));test('public empty',()=>assert.deepStrictEqual(M.toPublicView(),{}));
const src=fs.readFileSync(path.join(__dirname,'..','ai-literacy-lab.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'..','ai-literacy-lab.css'),'utf8'),html=fs.readFileSync(path.join(__dirname,'..','index (2).html'),'utf8');test('loader JS',()=>assert.ok(html.includes('<script src="ai-literacy-lab.js"></script>')));test('loader CSS',()=>assert.ok(html.includes('ai-literacy-lab.css')));test('prominent entries',()=>assert.ok(src.includes('dashboardView')&&src.includes('appNav')&&src.includes('resourceStudioView')&&src.includes('peerTutoringView')&&src.includes('roleDashboardsView')));test('private progress UI',()=>assert.ok(src.includes('Your private progress')&&src.includes('Continue learning')));test('functional starter control',()=>assert.ok(src.includes('data-ai-starter')));test('modern pathway cards',()=>assert.ok(src.includes('ai-path-card')&&src.includes('ai-card-action')));test('modern lesson cards',()=>assert.ok(src.includes('ai-module-card')&&src.includes('Choose module')));test('pathway tabs',()=>assert.ok(src.includes('ai-path-tabs')&&src.includes('aria-current')));test('accessible progress indicators',()=>assert.ok(src.includes('role="progressbar"')&&src.includes('aria-valuenow')));test('semantic table',()=>assert.ok(src.includes('<caption>')&&src.includes('scope="col"')&&src.includes('scope="row"')));test('semantic ordered cycle',()=>assert.ok(src.includes('<ol class="ai-cycle">')));test('live status',()=>assert.ok(src.includes('aria-live="polite"')));test('responsive CSS',()=>assert.ok(css.includes('@media(max-width:42rem)')));test('comfortable tap targets',()=>assert.ok(css.includes('min-height:44px')));test('reduced motion',()=>assert.ok(css.includes('prefers-reduced-motion')));test('forced colors',()=>assert.ok(css.includes('forced-colors')));test('RTL',()=>assert.ok(css.includes('[dir=rtl]')));test('print support',()=>assert.ok(css.includes('@media print')));test('no fixed Learn controls',()=>assert.strictEqual(css.includes('position:fixed'),false));test('no UNESCO logo',()=>assert.strictEqual(src.toLowerCase().includes('unesco-logo'),false));test('no certification claim',()=>assert.strictEqual(src.toLowerCase().includes('unesco certified'),false));
test('lesson library container',()=>assert.ok(src.includes('aiLessonLibraryGrid')&&src.includes('Explore every lesson')));
test('lesson launcher enhancement',()=>assert.ok(src.includes('enhanceLessonLaunchers')&&src.includes('ai-lesson-launcher')));
test('lesson library responsive cards',()=>assert.ok(css.includes('.ai-lesson-library-grid')&&css.includes('.ai-lesson-action')));
if(!process.exitCode)console.log(`ai-literacy-lab: ${passed}/${passed} assertions passed`);
