'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const Coach=require('../prompt-writing-coach.js');
const source=fs.readFileSync(path.join(root,'prompt-writing-coach.js'),'utf8');
const css=fs.readFileSync(path.join(root,'prompt-writing-coach.css'),'utf8');
const router=fs.readFileSync(path.join(root,'script.js'),'utf8');
const navigation=fs.readFileSync(path.join(root,'first-screen-navigation.js'),'utf8');

const expected=['What is your goal?','What subject are you working on?','What course, grade, or level?','What do you already understand?','What exactly is confusing?','What type of help do you want?','How should the answer be presented?','What should the AI avoid doing?','Do you need sources?'];
assert.equal(Coach._test.guidedBuilderSteps.length,9,'guided builder must have exactly nine sections');
assert.deepEqual(Coach._test.guidedBuilderSteps.map(step=>step.title),expected,'guided builder uses the exact required section order');
assert.match(navigation,/promptBuilder:\{title:'Build Your Prompt',description:'Answer a few short questions to create a prompt that matches your learning goal\.'/,'shared child-page header uses the required copy');
assert.match(router,/promptBuilder:'\/ai-coach\/prompt-coach\/new'/,'guided builder uses the canonical new-prompt route');
assert.match(router,/promptBuilder:'promptWithPurpose'/,'fresh-load Back falls back to Prompt Coach');
assert.match(source,/id="promptBuilderView"/,'guided builder is a dedicated app view');
assert.match(source,/Step \$\{state\.step \+ 1\} of \$\{GUIDED_BUILDER_STEPS\.length\}/,'builder shows current step out of nine');
assert.match(source,/role="progressbar"[^>]*aria-valuemin="1" aria-valuemax="9"/,'builder exposes accessible progress');
assert.match(source,/GUIDED_BUILDER_STEPS\[state\.step\]/,'only the current section is selected for rendering');
assert.match(source,/data-guided-previous/,'builder includes Previous');
assert.match(source,/data-guided-continue/,'builder includes Continue');
assert.match(source,/data-guided-save>Save Draft/,'builder includes Save Draft');
assert.match(source,/data-guided-review>Prompt Preview/,'builder includes Prompt Preview');
assert.match(source,/data-guided-cancel>Cancel/,'builder includes Cancel');
assert.match(source,/data-guided-confirm/,'builder requires explicit confirmation');
assert.match(source,/data-guided-use\$\{state\.confirmed \? '' : ' disabled'\}/,'AI Coach use is disabled until confirmation');
assert.match(source,/API\.createPromptCoachSession/,'Save Draft uses the existing private Prompt Coach session API');
assert.match(source,/API\.createPromptDraftVersion/,'Save Draft uses the existing prompt-version API');
const saveBody=source.match(/function saveGuidedPromptDraft[\s\S]*?\n  \}/)?.[0]||'';
assert.doesNotMatch(saveBody,/sendApprovedPromptDraft|sendDraft/,'saving a guided draft must not send it');
assert.match(source,/composer\.dispatchEvent\(new Event\('input'/,'confirmed prompt is placed in the existing AI Coach composer');
assert.doesNotMatch(source,/composer\.(?:submit|click)\(/,'placing a prompt must not submit it');
assert.match(source,/Discard your unsaved prompt changes\?/,'Cancel and Back protect unsaved work');
assert.match(css,/\.guided-prompt-shell/,'guided builder has focused page styles');
assert.match(css,/\.guided-prompt-question textarea\{min-height:9rem/,'current answer area is comfortably sized');
assert.match(css,/@media\(max-width:42rem\)/,'guided builder supports mobile layouts');
assert.match(css,/@media\(forced-colors:active\)/,'guided builder supports forced colours');

const templateState=Coach._test.newGuidedBuilderState('hint');
assert.equal(templateState.step,0);
assert.equal(templateState.values.helpType,'HINT');
assert.ok(templateState.values.goal);
assert.equal(templateState.confirmed,false);
assert.equal(templateState.saved,false);
const draftInput=Coach._test.guidedDraftInput(templateState);
assert.equal(draftInput.helpMode,'HINT');
assert.equal(draftInput.studentAttemptRule,'WAIT_FOR_STUDENT_RESPONSE');
assert.deepEqual(draftInput.sourceRequirements,['NO_EXTERNAL_SOURCE_NEEDED']);
console.log('Prompt Coach guided builder tests passed');
