'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const coach=fs.readFileSync(path.join(root,'prompt-writing-coach.js'),'utf8');
const navigation=fs.readFileSync(path.join(root,'first-screen-navigation.js'),'utf8');
const router=fs.readFileSync(path.join(root,'script.js'),'utf8');

const description='Build clearer, safer, and more useful AI prompts while staying in control of your learning.';
assert.match(navigation,/\['Prompt Coach','promptWithPurpose'\]/,'AI Coach hub must use the existing Prompt Coach view');
assert.doesNotMatch(navigation,/\['Prompt Coach','promptWritingCoach'\]/,'hub must not use the nonexistent legacy view key');
assert.match(coach,/viewNames\.promptWithPurpose = \['AI COACH', 'Prompt Coach'\]/,'Prompt Coach must register its canonical view');
assert.match(coach,/>Prompt Coach<\/h1>/,'page must include the exact title');
assert.ok(coach.includes(description),'page must include the exact description');
assert.match(coach,/data-prompt-create>Create a New Prompt<\/button>/,'page must include the exact primary action');
assert.match(navigation,/promptWithPurpose:\{hub:true,title:'Prompt Coach'/,'shared page header must use the exact title and hub layout');
assert.ok(navigation.includes(description),'shared page header must use the exact description');
assert.match(navigation,/primaryLabel:'Create a New Prompt'/,'shared header must display the exact action label');
assert.match(navigation,/promptWithPurpose:'\/ai-coach\/prompt-coach'/,'feature card must expose the canonical Prompt Coach route');
assert.match(coach,/if \(document\.getElementById\('promptWithPurposeView'\)\) \{ render\(\); return; \}/,'existing view must render instead of returning empty');
assert.match(coach,/setTimeout\(render, 0\)/,'feature-card navigation must trigger Prompt Coach rendering');
assert.match(coach,/firstField\?\.focus\?\.\(\)/,'Create a New Prompt must focus the existing builder');
assert.match(router,/promptWithPurpose:'coach'/,'fresh-load Back must return to AI Coach');
assert.match(router,/promptWithPurpose:'\/ai-coach\/prompt-coach'/,'router must map Prompt Coach to the canonical path');
assert.match(router,/location\.protocol==='file:'\?`#\$\{route\}`:route/,'direct-file use must preserve the canonical route through a safe hash fallback');
assert.match(router,/canonicalViewFromLocation\(\)\|\|'dashboard'/,'sign-in and Guest Mode must restore canonical deep links');
assert.doesNotMatch(coach,/fake prompt|demo prompt|sample prompt record/i,'page header must not add fake records');
console.log('Prompt Coach page header tests passed');
