'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const Coach=require('../prompt-writing-coach.js');
const source=fs.readFileSync(path.join(root,'prompt-writing-coach.js'),'utf8');
const css=fs.readFileSync(path.join(root,'prompt-writing-coach.css'),'utf8');
const router=fs.readFileSync(path.join(root,'script.js'),'utf8');
const navigation=fs.readFileSync(path.join(root,'first-screen-navigation.js'),'utf8');

assert.match(source,/>Improve an Existing Prompt</,'Prompt Coach has the required entry card');
assert.match(source,/>Improve My Prompt</,'entry point uses the exact primary action');
assert.match(source,/Paste a prompt you already wrote and review suggestions for making it clearer, safer, and more useful\./,'entry point explains the workflow');
assert.match(router,/promptImprove:'\/ai-coach\/prompt-coach\/improve'/,'workflow has a canonical child route');
assert.match(router,/promptImprove:'promptWithPurpose'/,'Back falls safely to Prompt Coach');
assert.match(navigation,/promptImprove:\{title:'Improve an Existing Prompt'/,'shared page header recognizes the workflow');
assert.match(source,/id="promptImproveView"/,'workflow renders as a dedicated child page');
for(const heading of ['Original Prompt','Improved Prompt','What Changed','Why It Is Better','What Still Needs Verification']) assert.match(source,new RegExp(`>${heading}<`),`results include ${heading}`);
for(const action of ['Accept Suggestion','Reject Suggestion','Restore Original Prompt','Save Improved Prompt as New Version','Use Approved Prompt in AI Coach']) assert.match(source,new RegExp(action),`workflow includes ${action}`);
assert.match(source,/data-improve-suggestion-text/,'every suggestion has editable wording');
assert.match(source,/state\.original\.trim\(\), \.\.\.additions/,'improved text is derived without overwriting the original');
assert.match(source,/suggestion\.status === 'accepted'/,'only accepted suggestions enter the improved prompt');
assert.match(source,/suggestion\.status !== 'pending'/,'every suggestion must be reviewed');
assert.match(source,/Privacy Check Before Sending/,'workflow includes a privacy check before AI Coach use');
assert.match(source,/!state\?\.approved \|\| !improvePrivacyClear\(state\)/,'AI Coach use requires approval and a clear privacy check');
assert.match(source,/composer\.dispatchEvent\(new Event\('input'/,'approved prompt is placed in the existing composer');
assert.doesNotMatch(source,/composer\.(?:submit|click)\(/,'improved prompts are never sent automatically');
assert.match(source,/originalDraftId = API\.createPromptDraftVersion/,'saving preserves the original as a private version');
assert.match(source,/improvedDraftId = API\.createPromptDraftVersion/,'saving creates a separate improved version');
assert.doesNotMatch(source,/Prompt Quality:\s*97%/,'workflow does not create a meaningless numeric score');

const state=Coach._test.newImprovePromptState();
state.original='Explain how photosynthesis stores energy.';
state.suggestions=Coach._test.improveSuggestions();
state.reviewed=true;
state.suggestions[0].status='accepted';
state.suggestions[0].editedText='Ask one question first so the explanation matches what I know.';
state.suggestions.slice(1).forEach(item=>{item.status='rejected';});
assert.equal(Coach._test.improveReviewComplete(state),true);
assert.equal(state.original,'Explain how photosynthesis stores energy.','review never replaces the original');
assert.match(Coach._test.improvedPromptText(state),/Ask one question first/,'accepted edited wording appears in the improved version');
assert.equal(Coach._test.improvePrivacyClear(state),true);
state.suggestions[0].editedText='My home address is 123 Main Street.';
assert.equal(Coach._test.improvePrivacyClear(state),false,'edited suggestions are privacy checked');
assert.match(css,/\.prompt-improve-results[^}]*grid-template-columns:repeat\(2/,'comparison uses two columns when space permits');
assert.match(css,/@media\(max-width:48rem\)[\s\S]*?\.prompt-improve-results[^}]*grid-template-columns:1fr/,'comparison stacks without horizontal scrolling on narrow screens');
console.log('Prompt Coach improve-existing-prompt tests passed');
