'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
require('../responsible-ai-learning-success-measures.js');
const W=global.ResponsibleAICorrectionWorkflow;
const source=fs.readFileSync(path.join(root,'responsible-ai-learning-success-measures.js'),'utf8');
const css=fs.readFileSync(path.join(root,'responsible-ai-learning-success-measures.css'),'utf8');
const script=fs.readFileSync(path.join(root,'script.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index (2).html'),'utf8');
const student={userId:'correction-student',tenantId:'correction-school',role:'student'};
const teacher={userId:'correction-teacher',tenantId:'correction-school',role:'teacher'};

assert.ok(W,'One shared correction workflow must be available');
const draft=W.saveCorrectionDraft({metricDefinitionVersionId:'definition-version-independent_retry_success_rate-1',correctionType:'WRONG_STATUS',sourceRecordType:'LearningCheck',sourceRecordId:'check-1',studentFacingDescription:'My completed check is still shown as pending.',originView:'competencyPortfolio'},student);
assert.strictEqual(draft.submitted,false);
assert.strictEqual(draft.recordChanged,false);
assert.strictEqual(draft.progressChanged,false);
assert.strictEqual(draft.competencyChanged,false);
assert.throws(()=>W.requestCorrection({idempotencyKey:'missing-description'},student),error=>error.code==='CORRECTION_DESCRIPTION_REQUIRED');
const submitted=W.requestCorrection({idempotencyKey:'submit-correction',draftId:draft.draft.id,metricDefinitionVersionId:draft.draft.metricDefinitionVersionId,correctionType:draft.draft.correctionType,sourceRecordType:draft.draft.sourceRecordType,sourceRecordId:draft.draft.sourceRecordId,studentFacingDescription:draft.draft.studentFacingDescription},student);
assert.strictEqual(submitted.correction.status,'SUBMITTED');
assert.strictEqual(submitted.correction.humanReviewRequired,true);
assert.strictEqual(submitted.recordChanged,false);
assert.strictEqual(submitted.progressChanged,false);
assert.strictEqual(submitted.competencyChanged,false);
const reviewed=W.reviewCorrection({id:submitted.correction.id,status:'ADDITIONAL_INFORMATION_REQUESTED',resolutionSummary:'Please provide the attempt date.'},teacher);
assert.strictEqual(reviewed.status,'ADDITIONAL_INFORMATION_REQUESTED');

assert.match(source,/data-request-metric-correction/,'Every shared section button must use the working action hook');
assert.match(source,/id="metricCorrectionRequestView"|view\.id='metricCorrectionRequestView'/,'The dedicated correction page must exist');
for(const label of ['Save Draft','Review and Submit Request','Cancel','Review only']) assert.ok(source.includes(label),`${label} must be visible`);
assert.match(script,/metricCorrectionRequest:'\/progress\/responsible-ai-measures\/correction'/,'The workflow must have one canonical route');
assert.match(script,/metricCorrectionRequest'\?'progress'/,'The correction page must have a safe Progress fallback');
assert.match(css,/\.railm-correction-form/);
assert.match(css,/@media\(max-width:640px\)/);
assert.match(html,/responsible-ai-learning-success-measures\.js\?v=correction-workflow-20260826-5/);
console.log('responsible AI correction workflow tests passed');
