'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const html=read('index (2).html'),script=read('script.js');
let passed=0;
const test=(name,fn)=>{fn();passed++;console.log(`✓ ${name}`)};
test('planner shortcut retains its exact label and header location',()=>assert.ok(html.includes('<button class="btn btn-secondary saved-plans-shortcut" id="savedPlansShortcut" type="button">Saved Study Plans</button></div><div class="planner-layout">')));
test('saved plans has a separate app view',()=>assert.ok(html.includes('<section class="app-view" id="savedPlansView">')));
test('planner no longer contains the saved plans section',()=>{const plannerLine=html.split('\n').find(line=>line.includes('id="plannerView"'));assert.ok(plannerLine&&!plannerLine.includes('savedPlansSection'))});
test('separate page owns the existing saved plans grid',()=>assert.strictEqual((html.match(/id="savedPlansGrid"/g)||[]).length,1));
test('shortcut navigates to the saved plans view',()=>assert.ok(script.includes("$('#savedPlansShortcut').addEventListener('click',()=>showView('savedPlans'))")));
test('old shortcut scroll is removed',()=>assert.ok(!script.includes("scrollPlannerTarget('saved')")));
test('old saved-section scroll target is removed',()=>assert.ok(!script.includes("$('#savedPlansSection')?.scrollIntoView")));
test('saved plans view is registered',()=>assert.ok(script.includes("savedPlans:['STUDY','Saved Study Plans']")));
test('saved plans route has a content contract',()=>assert.ok(script.includes("savedPlans:{role:'student',title:'Saved Study Plans'")));
test('route renders existing saved plan data',()=>assert.ok(script.includes("if(view==='savedPlans')renderSavedPlans()")));
test('dashboard recent plans routes to the separate page',()=>assert.ok(html.includes('data-view="savedPlans">View all</button>')));
test('plan detail returns to the separate page',()=>assert.ok(script.includes("$('#backToPlansBtn').addEventListener('click',()=>showView('savedPlans'))")));
test('saved page returns to Study Planner',()=>assert.ok(script.includes("$('#backToPlannerBtn').addEventListener('click',()=>showView('planner'))")));
test('existing plan management actions remain available',()=>['data-plan-open','data-plan-edit','data-plan-rename','data-plan-delete'].forEach(action=>assert.ok(script.includes(action),action)));
console.log(`${passed} saved-study-plans route assertions passed`);
