const fs=require('fs'),path=require('path'),assert=require('assert'),S=require('../speech-to-text.js');
const root=path.join(__dirname,'..'),js=fs.readFileSync(path.join(root,'speech-to-text.js'),'utf8'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8'),css=fs.readFileSync(path.join(root,'speech-to-text.css'),'utf8');
const tests=[],test=(n,f)=>tests.push([n,f]);
test('load order',()=>assert(html.indexOf('text-to-speech.js')<html.indexOf('speech-to-text.js')&&html.indexOf('speech-to-text.js')<html.indexOf('accessibility-toolbar.js')));
test('stylesheet loaded',()=>assert(html.includes('speech-to-text.css')));
test('eleven states',()=>assert.equal(S.STATES.length,11));
for(const x of ['IDLE','REQUESTING_PERMISSION','LISTENING','PROCESSING','TRANSCRIPT_READY','PERMISSION_DENIED','UNAVAILABLE','CONNECTION_LOST','ERROR','CANCELLED'])test(`state ${x}`,()=>assert(S.STATES.includes(x)));
for(const x of ['Microphone off','Requesting microphone access','Listening','Processing speech','Transcript ready','Microphone unavailable','Microphone permission denied','Connection lost','Speech recognition error'])test(`label ${x}`,()=>assert(Object.values(S.LABELS).includes(x)));
test('seven destinations',()=>assert.equal(S.SOURCE_TYPES.length,7));
test('sixteen capabilities',()=>assert.equal(Object.keys(S.getSpeechToTextCapabilities()).length,16));
test('offline and server unavailable',()=>{assert.equal(S.getSpeechToTextCapabilities().SPEECH_TO_TEXT_OFFLINE.supportLevel,'NOT_AVAILABLE');assert.equal(S.getSpeechToTextCapabilities().SPEECH_TO_TEXT_SERVER_PROVIDER.supportLevel,'NOT_AVAILABLE')});
test('manual pending',()=>Object.values(S.getSpeechToTextCapabilities()).forEach(x=>assert.equal(x.manualTestStatus,'PENDING')));
test('permission explanation before request',()=>assert(js.includes("querySelector('[data-dictation=\"continue\"]').onclick")&&js.includes("querySelector('#dictationPermission').hidden=true;request()")));
test('continue required',()=>assert(js.includes('Continue and Request Microphone Access')));
test('no page load permission',()=>assert(!/function init\(\)[\s\S]{0,250}getUserMedia/.test(js)));
test('audio only constraints',()=>['video:false','echoCancellation:true','noiseSuppression:true','autoGainControl:true','channelCount:1'].forEach(x=>assert(js.includes(x))));
test('all tracks stop',()=>assert(js.includes('getTracks?.().forEach(t=>t.stop())')));
test('existing value selection captured',()=>['initialFieldText:f.value','initialSelectionStart','initialSelectionEnd'].forEach(x=>assert(js.includes(x))));
test('interim separate',()=>assert(js.includes("interimTranscript:''")));
test('editable review and actions',()=>['id="dictationReviewText"','Insert Transcript','Append Transcript','Replace Selected Text','Discard Transcript','Start Over','Undo Last Dictation','Copy Transcript'].forEach(x=>assert(js.includes(x))));
test('conflict detected',()=>assert(js.includes('version(s.field)!==s.fieldVersion')));
test('no auto submit invariant',()=>assert.equal(S.speechRecognitionCompletionEqualsContentSubmission,false));
for(const x of ['send','submit','search','post','go','enter','confirm'])test(`spoken ${x} stays text`,()=>assert(S.ACTION_WORDS.includes(x)));
test('no destination calls',()=>assert(!/\.submit\(|requestSubmit\(|sendAIMessage|executeSearch|postDiscussionResponse|submitTutoringRequest/.test(js)));
test('interim never inserted',()=>assert(!/onresult[\s\S]{0,700}field\.value/.test(js)));
test('TTS stops before capture',()=>assert(js.includes('TextToSpeech?.stopTextToSpeech?.()')));
test('lifecycle cleanup',()=>['visibilitychange','pagehide','beforeunload',"addEventListener('offline'"].forEach(x=>assert(js.includes(x))));
test('no reconnect restart',()=>assert(!js.includes("addEventListener('online'")));
test('Escape stops',()=>assert(js.includes("e.key==='Escape'")));
test('one session and private cross-tab',()=>{assert(js.includes("state={status:'IDLE',session:null"));assert(!/postMessage\([^)]*(transcript|audio)/.test(js))});
test('no raw storage recorder or profiling',()=>{assert(js.includes("rawAudioRetention:'NONE_BY_STUDYSPARK'"));assert(!/MediaRecorder|voiceprint|emotion|accent.?score|fluency.?score|analytics|trackEvent/i.test(js))});
test('normal fields remain',()=>assert(js.includes("querySelectorAll('textarea,input[type=\"search\"]")));
test('unavailable hides controls',()=>assert(js.includes('if(!available()')));
test('contextual native buttons',()=>assert(js.includes('Start dictation for ${label}')&&js.includes("b.type='button'")));
test('restrained accessible status',()=>['aria-live="polite"','aria-label="Dictation preview"','Listening. Dictation preview is updating.','id="dictationStatus"'].forEach(x=>assert(js.includes(x))));
test('visual access rules',()=>['@media(forced-colors:active)','safe-area-inset-bottom','flex-wrap:wrap','@media print'].forEach(x=>assert(css.includes(x))));
test('no waveform',()=>assert(!/waveform|AudioWorklet|AudioContext/.test(js)));
test('language list and rejection',()=>{for(const x of ['en','en-CA','fr-CA','zh-Hans','zh-Hant','es','ar'])assert(S.LANGUAGES.includes(x));assert.equal(S.toSpeechRecognitionLanguageView('xx').supported,false)});
test('provider disclosure no storage',()=>assert.equal(S.getSpeechToTextProviderDisclosure().rawAudioStored,false));
test('development fixtures only',()=>S.seedDevelopmentData().forEach(x=>assert(x.developmentOnly)));
let passed=0;for(const[n,f]of tests){try{f();passed++;console.log(`PASS ${n}`)}catch(e){console.error(`FAIL ${n}\n${e.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
