'use strict';
const assert=require('assert'),P=require('../student-privacy.js');let n=0;const test=(name,fn)=>{fn();n++;};
test('32 controlled categories',()=>assert.equal(P.StudentDataCategory.length,32));
test('four sensitivity levels',()=>assert.deepEqual(P.DataSensitivity,['PUBLIC','PRIVATE','SENSITIVE','HIGHLY_RESTRICTED']));
['ACCESSIBILITY_PREFERENCES','LANGUAGE_PREFERENCES','STORED_VOICE_RECORDING','SAVED_TRANSCRIPT'].forEach(c=>test(`${c} sensitive`,()=>assert.equal(P.classify(c),'SENSITIVE')));
['ACCOMMODATION_REQUEST','ACCOMMODATION_DOCUMENT','DISABILITY_OR_MEDICAL_INFORMATION','LEARNING_DIFFICULTY_DISCLOSURE'].forEach(c=>test(`${c} restricted`,()=>assert.equal(P.classify(c),'HIGHLY_RESTRICTED')));
test('unknown category rejected',()=>assert.throws(()=>P.classify('FREE_TEXT'),/Unknown/));
test('category cannot default public',()=>assert.equal(P.classify('PRIVATE_PROFILE'),'PRIVATE'));
test('public serializer allowlist',()=>{const v=P.toPublicStudentProfileView({displayName:'Sam',avatar:'a',diagnosis:'x',languagePreferences:'fr',voiceRecordings:['x'],privacyRequests:['x']});assert.deepEqual(v,{displayName:'Sam',avatar:'a'})});
P.forbiddenPublic.forEach(k=>test(`public excludes ${k}`,()=>assert.ok(!(k in P.toPublicStudentProfileView({[k]:'secret'})))));
test('AI removes diagnosis',()=>assert.ok(!('diagnosis' in P.minimizeForAI({diagnosis:'x',topic:'math'}))));
test('AI removes accommodation',()=>assert.ok(!('accommodationDocument' in P.minimizeForAI({accommodationDocument:'x'}))));
test('AI removes guardian data',()=>assert.ok(!('guardianInformation' in P.minimizeForAI({guardianInformation:'x'}))));
test('AI removes other participants',()=>assert.ok(!('otherParticipants' in P.minimizeForAI({otherParticipants:['x']}))));
test('AI retains functional topic',()=>assert.equal(P.minimizeForAI({topic:'math'}).topic,'math'));
test('tutor preview selected fields only',()=>{const v=P.tutorPreview({captionsPreferred:true,diagnosis:'x'},['captionsPreferred','diagnosis']);assert.deepEqual(v.shared,{captionsPreferred:true})});
test('tutor preview names exclusions',()=>assert.ok(P.tutorPreview().notShared.some(x=>x.includes('Disability'))));
test('recording account consent blocked',()=>assert.throws(()=>P.consentDecision({type:'SAVE_SESSION_AUDIO_RECORDING',scope:'ACCOUNT_PREFERENCE',status:'GRANTED'}),/blanket/));
test('recording one session allowed',()=>assert.equal(P.consentDecision({type:'SAVE_SESSION_AUDIO_RECORDING',scope:'ONE_SESSION',status:'GRANTED',noticeVersion:'1',policyVersion:'1',dataCategories:['SESSION_AUDIO_RECORDING']}).scope,'ONE_SESSION'));
test('decline stored accurately',()=>assert.equal(P.consentDecision({type:'SAVE_PERSONAL_TRANSCRIPT',scope:'ONE_SESSION',status:'DECLINED'}).status,'DECLINED'));
test('invalid choice rejected',()=>assert.throws(()=>P.consentDecision({type:'SAVE_PERSONAL_TRANSCRIPT',scope:'ONE_SESSION',status:'YES'}),/granted or declined/));
test('recording without authorization blocked',()=>assert.throws(()=>P.startRecording({authorized:false}),/before current authorization/));
test('recording without policy blocked',()=>assert.throws(()=>P.startRecording({authorized:true}),/notice and policy/));
test('authorized recording starts',()=>assert.equal(P.startRecording({authorized:true,noticeVersion:'1',policyVersion:'1',transcript:false}).active,true));
test('recording and transcript separate',()=>assert.equal(P.state.recording.transcript,false));
test('recording stops',()=>assert.equal(P.stopRecording().active,false));
test('withdraw receipt',()=>{const r=P.consentDecision({type:'SAVE_PERSONAL_TRANSCRIPT',scope:'ONE_ACTION',status:'GRANTED'});assert.equal(P.withdrawConsent(r.id).status,'WITHDRAWN')});
test('notice identifies raw audio',()=>assert.ok(P.recordingNotice().rawAudio));
test('notice identifies transcript',()=>assert.ok(P.recordingNotice().transcript));
test('notice identifies purpose',()=>assert.ok(P.recordingNotice().purpose));
test('notice identifies recipients',()=>assert.ok(P.recordingNotice().recipients.length));
test('notice identifies processors',()=>assert.ok(P.recordingNotice().processors.length));
test('notice identifies retention',()=>assert.ok(P.recordingNotice().retention));
test('notice has decline',()=>assert.equal(P.recordingNotice().canDecline,true));
test('notice has alternative',()=>assert.ok(P.recordingNotice().alternative.includes('Text-Only')));
test('notice separates deletion',()=>assert.ok(P.recordingNotice().withdrawal.includes('separately')));
test('notice explains external downloads',()=>assert.ok(P.recordingNotice().downloads.includes('not be remotely')));
test('request needs idempotency',()=>assert.throws(()=>P.request('DATA_EXPORT',[]),/idempotency/));
test('request stays draft',()=>assert.equal(P.request('DATA_EXPORT',['LANGUAGE_PREFERENCES'],'export-1').status,'DRAFT'));
test('request is idempotent',()=>assert.equal(P.request('DATA_EXPORT',[],'export-1').id,'privacy-request-1'));
test('request does not claim submission',()=>assert.ok(P.request('DATA_EXPORT',[],'export-1').notice.includes('not been submitted')));
test('unknown request rejected',()=>assert.throws(()=>P.request('DELETE_ALL',[],'x'),/Unknown/));
test('unsynced cleanup blocked',()=>assert.throws(()=>P.removeDeviceData({unsyncedDrafts:1}),/Unsynced|unsynced|Export/));
test('cleanup external limitation',()=>assert.equal(P.removeDeviceData({unsyncedDrafts:0}).externalFilesRemoved,false));
test('inventory has purpose',()=>assert.ok(P.inventory.every(x=>x[3])));
test('inventory has recipients',()=>assert.ok(P.inventory.every(x=>x[4])));
test('inventory has retention',()=>assert.ok(P.inventory.every(x=>x[5])));
test('transcript choices granular',()=>assert.equal(P.TranscriptSavingPreference.length,5));
test('sharing defaults none',()=>assert.equal(P.state.tutorSharingMode,'SHARE_NOTHING'));
test('recording statuses honest',()=>assert.ok(P.PrivacyDeletionStatus.includes('BACKUP_EXPIRATION_PENDING')));
test('export statuses include identity verification',()=>assert.ok(P.DataExportStatus.includes('VERIFYING_IDENTITY')));
test('no training consent type',()=>assert.ok(P.PrivacyConsentType.every(x=>!x.includes('TRAIN'))));
console.log(`student-privacy: ${n}/${n} assertions passed`);
