const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const db={users:{},tutoringOrganizations:[{id:'org-a',name:'Demo School A',verificationStatus:'VERIFIED'},{id:'org-b',name:'Demo School B',verificationStatus:'VERIFIED'}]};let currentAccount=null;
const document={querySelector:()=>null,querySelectorAll:()=>[]},window={};
const context={console,db,document,window,Intl,Date,Math,Uint32Array,viewNames:{},showView:async()=>{},user:()=>currentAccount,saveDB:()=>{},toast:()=>{},FormData:class{},appData:{courses:['Biology','Math','English']}};vm.createContext(context);
for(const file of ['peer-tutoring.js','student-onboarding.js','tutor-application.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);
const P=window.PeerTutoring,S=window.StudentOnboarding,T=window.TutorApplication;
function account(id,roles=[P.ROLES.PEER_TUTOR],opts={}){const a={id,email:`${id}@demo.invalid`,name:`Demo ${id}`,studentId:`STU-${String(Object.keys(db.users).length+1).padStart(6,'0')}`,emailVerifiedAt:opts.verified===false?null:new Date().toISOString(),peerTutoring:{accountStatus:opts.status||P.ACCOUNT_STATUS.ACTIVE,roles:[...roles],activeRole:roles[0],isMinor:opts.minor===true,guardianConsentStatus:opts.minor?'REQUIRED':'NOT_REQUIRED',learnerProfile:{},tutorProfile:{verificationStatus:opts.legacyStatus||'NOT_SUBMITTED'},organizationMemberships:opts.memberships||[],qualifications:[]}};db.users[a.email]=a;completeStudent(a);if(opts.minor&&opts.consent)S._test.consentRecords().push({id:`consent-${id}`,learnerUserId:a.id,parentGuardianUserId:'guardian',status:'GRANTED',grantedAt:new Date().toISOString(),revokedAt:null});return a;}
function completeStudent(a){const p=S.getStudentProfile(a);Object.assign(p,{firstName:'Demo',lastName:'Tutor',schoolOrganizationName:'Demo School',gradeLevel:'Grade 11',timeZone:'America/Toronto',preferredLanguage:'en',sessionModePreference:'ONLINE',subjectInterests:[{subjectId:'Biology',interestType:'TUTOR'}],availabilityWindows:[{dayOfWeek:'Monday',startTime:'16:00',endTime:'18:00',timeZone:'America/Toronto'}],onboardingStartedAt:new Date().toISOString(),onboardingCompletedAt:new Date().toISOString(),availableForTutoring:true});}
function fillApp(a){currentAccount=a;let app=T.getApplication(a);if(app.status===T.TUTOR_STATUS.NOT_APPLIED)app=T.startApplication();T.saveSubjects({subjects:[{subjectId:'Biology',courseLevel:'Grade 10',claimedResultType:'PERCENTAGE',claimedResultValue:'88',qualificationSummary:'Completed the course successfully.'}],gradeLevels:['Grade 9','Grade 10']});T.saveExperience({noPreviousExperience:true,entries:[],summary:''});T.saveLanguages({languages:[{languageCode:'en',proficiencyLevel:'Fluent',canTutorInLanguage:true}]});T.saveAvailability({reuseStudent:true,availabilityVaries:false,sessionModePreference:'ONLINE'});T.saveMotivation('I want to help other students understand challenging ideas through patient explanations, examples, and supportive practice.');T.acceptCodeOfConduct(true);return app;}
function submit(a){currentAccount=a;fillApp(a);return T.submitApplication();}
function capInput(app){const snap=T._test.latestSubmission(app).submittedSnapshot,s=snap.subjects[0];return {version:app.currentVersion,confirmVersion:true,evidenceReviewed:true,conductCurrent:true,noConflict:true,applicantVisibleComment:'Your application has been verified.',capabilities:[{subjectId:s.subjectId,courseLevel:s.courseLevel,gradeLevels:['Grade 9'],languageCodes:['en']}]};}
function expectThrow(fn,re){assert.throws(fn,re)}const tests=[];function test(n,f){tests.push([n,f])}

const learner=account('learner',[P.ROLES.LEARNER]);const tutor=account('tutor');
test('1 peer tutor starts NOT_APPLIED',()=>assert.equal(T.canonicalTutorStatus(tutor),T.TUTOR_STATUS.NOT_APPLIED));
test('2 starting changes to incomplete',()=>{currentAccount=tutor;assert.equal(T.startApplication().status,T.TUTOR_STATUS.APPLICATION_INCOMPLETE)});
test('3 incomplete cannot submit',()=>{currentAccount=tutor;expectThrow(()=>T.submitApplication(),/not ready/)});
test('4 complete application submits',()=>{const a=account('complete');assert.equal(submit(a).version,1)});
test('5 submission changes status',()=>{const a=account('pending');submit(a);assert.equal(T.getApplication(a).status,T.TUTOR_STATUS.PENDING_VERIFICATION)});
test('6 immutable snapshot created',()=>{const a=account('snapshot');const sub=submit(a),before=JSON.stringify(sub.submittedSnapshot);T.getApplication(a).motivationStatement='changed outside snapshot';assert.equal(JSON.stringify(sub.submittedSnapshot),before)});
test('7 resubmission preserves version one',()=>{const a=account('resubmit');submit(a);const app=T.getApplication(a),reviewer=account('reviewer7',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});app.organizationId='org-a';currentAccount=reviewer;T.requestChanges(app.id,{categories:['MOTIVATION'],applicantVisibleInstruction:'Please clarify your motivation statement.'});currentAccount=a;T.saveMotivation('I want to help students learn with patient explanations and examples, and I have clarified how I would support their progress.');T.submitApplication();assert.deepEqual(app.submissions.map(s=>s.version),[1,2])});
test('8 applicant cannot verify self',()=>{const a=account('selfverify');submit(a);currentAccount=a;expectThrow(()=>T.verifyApplication(T.getApplication(a).id,capInput(T.getApplication(a))),/permission/)});
test('9 applicant cannot directly set pending',()=>{const a=account('directpending');currentAccount=a;const app=T.startApplication();assert.equal(T.canTransition(app.status,T.TUTOR_STATUS.PENDING_VERIFICATION,a,app),false);expectThrow(()=>T.transition(app,T.TUTOR_STATUS.PENDING_VERIFICATION,a,{}),/not allowed/)});
test('10 applicant cannot remove rejected status',()=>{const a=account('rejectlock');const app=T.getApplication(a);app.status=T.TUTOR_STATUS.REJECTED;currentAccount=a;expectThrow(()=>T.saveMotivation('A'.repeat(100)),/not currently editable/)});
for(const [i,status] of Object.values(T.TUTOR_STATUS).filter(s=>s!=='VERIFIED').entries())test(`${11+i} ${status} excluded from matching`,()=>{const a=account(`excluded-${status}`);const app=T.getApplication(a);app.status=status;assert.equal(T.canAppearInTutorMatching(a),false)});
test('17 verified tutor needs all other eligibility',()=>{const a=account('verified-all');const app=T.getApplication(a);app.status=T.TUTOR_STATUS.VERIFIED;assert(T.matchingBlockers(a).includes('CODE_OF_CONDUCT_OUTDATED'))});
test('18 verified unverified-email tutor excluded',()=>{const a=account('verified-email',[P.ROLES.PEER_TUTOR],{verified:false});const app=T.getApplication(a);app.status=T.TUTOR_STATUS.VERIFIED;assert(T.matchingBlockers(a).includes('EMAIL_NOT_VERIFIED'))});
test('19 verified minor without consent excluded',()=>{const a=account('verified-minor',[P.ROLES.PEER_TUTOR],{minor:true});T.getApplication(a).status=T.TUTOR_STATUS.VERIFIED;assert(T.matchingBlockers(a).includes('GUARDIAN_CONSENT_REQUIRED'))});
test('20 verified without capabilities excluded',()=>{const a=account('verified-nocaps');T.getApplication(a).status=T.TUTOR_STATUS.VERIFIED;assert(T.matchingBlockers(a).includes('NO_APPROVED_CAPABILITIES'))});
test('21 suspension removes matching immediately',()=>{const a=account('suspend-match'),admin=account('admin21',[P.ROLES.PLATFORM_ADMIN]);submit(a);const app=T.getApplication(a);app.status=T.TUTOR_STATUS.VERIFIED;T._test.capabilities().push({id:'cap21',tutorUserId:a.id,sourceApplicationId:app.id,subjectId:'Biology',courseLevel:'Grade 10',gradeLevels:['Grade 9'],languageCodes:['en'],approvedAt:new Date().toISOString(),revokedAt:null});currentAccount=admin;T.suspendTutor(a.id,{category:'SAFETY',applicantVisibleComment:'Tutoring access is paused during a safety review.'});assert.equal(T.canAppearInTutorMatching(a),false);assert(T._test.capabilities().find(c=>c.id==='cap21').revokedAt)});
test('22 matching uses approved not requested capabilities',()=>{const a=account('cap-scope');const app=T.getApplication(a);app.status=T.TUTOR_STATUS.VERIFIED;app.codeOfConductVersion=T.CODE_OF_CONDUCT_VERSION;app.codeOfConductAgreedAt=new Date().toISOString();T._test.capabilities().push({id:'cap22',tutorUserId:a.id,sourceApplicationId:app.id,subjectId:'Biology',courseLevel:'Grade 10',gradeLevels:['Grade 9'],languageCodes:['en'],approvedAt:new Date().toISOString(),revokedAt:null});assert.equal(T.getVerifiedTutorCandidates({subjectId:'Math'}).some(x=>x.id===a.id),false)});
test('23 learner cannot view verifier queue',()=>assert.equal(T.reviewerQueue(learner).length,0));
test('24 tutor cannot self review',()=>{const a=account('self-review',[P.ROLES.PEER_TUTOR,P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});submit(a);T.getApplication(a).organizationId='org-a';assert.equal(T.canReviewTutorApplication(a,T.getApplication(a)),false)});
test('25 inactive verifier cannot review',()=>{const v=account('inactive-verifier',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.SUSPENDED}]});const a=account('app25');submit(a);T.getApplication(a).organizationId='org-a';assert.equal(T.canReviewTutorApplication(v,T.getApplication(a)),false)});
test('26 verifier cannot access other organization',()=>{const v=account('verifier26',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app26');submit(a);T.getApplication(a).organizationId='org-b';assert.equal(T.canViewTutorApplication(v,T.getApplication(a)),false)});
test('27 verifier cannot access other org document',()=>{const v=account('verifier27',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app27');fillApp(a);const doc=T.uploadDocument({name:'record.pdf',type:'application/pdf',size:1000});T.getApplication(a).organizationId='org-b';currentAccount=v;expectThrow(()=>T.getDocumentAccess(doc.id),/do not have access/)});
test('28 authorized verifier can review assigned app',()=>{const v=account('verifier28',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app28');submit(a);T.getApplication(a).organizationId='org-a';assert(T.canReviewTutorApplication(v,T.getApplication(a)))});
test('29 admin can access application',()=>{const admin=account('admin29',[P.ROLES.PLATFORM_ADMIN]);const a=account('app29');assert(T.canViewTutorApplication(admin,T.getApplication(a)))});
test('30 review decision audits',()=>{const v=account('verifier30',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app30');submit(a);const app=T.getApplication(a);app.organizationId='org-a';currentAccount=v;T.requestChanges(app.id,{categories:['MOTIVATION'],applicantVisibleInstruction:'Please add a clearer motivation explanation.'});assert(db.peerTutoringAuditLogs.some(x=>x.action==='TUTOR_APPLICATION_CHANGES_REQUESTED'&&x.targetId===app.id))});
test('31 verification requires capability',()=>{const v=account('verifier31',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app31');submit(a);const app=T.getApplication(a);app.organizationId='org-a';currentAccount=v;expectThrow(()=>T.verifyApplication(app.id,{...capInput(app),capabilities:[]}),/at least one/)});
test('32 verification sets VERIFIED',()=>{const v=account('verifier32',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app32');submit(a);const app=T.getApplication(a);app.organizationId='org-a';currentAccount=v;T.verifyApplication(app.id,capInput(app));assert.equal(app.status,T.TUTOR_STATUS.VERIFIED)});
test('33 changes need instructions',()=>{const v=account('verifier33',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app33');submit(a);const app=T.getApplication(a);app.organizationId='org-a';currentAccount=v;expectThrow(()=>T.requestChanges(app.id,{categories:['MOTIVATION'],applicantVisibleInstruction:''}),/between/)});
test('34 changes status set',()=>{const v=account('verifier34',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app34');submit(a);const app=T.getApplication(a);app.organizationId='org-a';currentAccount=v;T.requestChanges(app.id,{categories:['EXPERIENCE'],applicantVisibleInstruction:'Please clarify the experience section.'});assert.equal(app.status,T.TUTOR_STATUS.CHANGES_REQUESTED)});
test('35 resubmission returns pending',()=>{const v=account('verifier35',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app35');submit(a);const app=T.getApplication(a);app.organizationId='org-a';currentAccount=v;T.requestChanges(app.id,{categories:['MOTIVATION'],applicantVisibleInstruction:'Please clarify the motivation section.'});currentAccount=a;T.submitApplication();assert.equal(app.status,T.TUTOR_STATUS.PENDING_VERIFICATION)});
test('36 rejection requires reason',()=>{const v=account('verifier36',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});const a=account('app36');submit(a);const app=T.getApplication(a);app.organizationId='org-a';currentAccount=v;expectThrow(()=>T.rejectApplication(app.id,{category:'',applicantVisibleComment:'Not approved because requirements were not met.'}),/category/)});
test('37 suspension requires admin and reason',()=>{const a=account('app37');const v=account('v37',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});currentAccount=v;expectThrow(()=>T.suspendTutor(a.id,{category:'SAFETY',applicantVisibleComment:'Tutoring access is paused during review.'}),/Administrator/)});
test('38 suspension revokes capabilities',()=>{const a=account('app38'),admin=account('admin38',[P.ROLES.PLATFORM_ADMIN]);const app=T.getApplication(a);app.status=T.TUTOR_STATUS.VERIFIED;T._test.capabilities().push({id:'cap38',tutorUserId:a.id,revokedAt:null});currentAccount=admin;T.suspendTutor(a.id,{category:'POLICY',applicantVisibleComment:'Tutoring access is paused for policy review.'});assert(T._test.capabilities().find(c=>c.id==='cap38').revokedAt)});
test('39 reinstatement audits',()=>{const a=account('app39'),admin=account('admin39',[P.ROLES.PLATFORM_ADMIN]);T.getApplication(a).status=T.TUTOR_STATUS.SUSPENDED;currentAccount=admin;T.reinstateTutor(a.id,{nextStatus:T.TUTOR_STATUS.PENDING_VERIFICATION});assert(db.peerTutoringAuditLogs.some(x=>x.action==='TUTOR_REINSTATED'&&x.targetId===T.getApplication(a).id))});
test('40 invalid transition rejected',()=>{const a=account('app40'),admin=account('admin40',[P.ROLES.PLATFORM_ADMIN]);const app=T.getApplication(a);currentAccount=admin;expectThrow(()=>T.transition(app,T.TUTOR_STATUS.VERIFIED,admin,{}),/not allowed/)});
test('41 public user cannot access docs',()=>{const a=account('app41');fillApp(a);const d=T.uploadDocument({name:'a.pdf',type:'application/pdf',size:100});currentAccount=null;expectThrow(()=>T.getDocumentAccess(d.id),/do not have access/)});
test('42 unrelated student cannot access docs',()=>{const a=account('app42');fillApp(a);const d=T.uploadDocument({name:'a.pdf',type:'application/pdf',size:100});currentAccount=learner;expectThrow(()=>T.getDocumentAccess(d.id),/do not have access/)});
test('43 applicant can access own quarantined metadata',()=>{const a=account('app43');fillApp(a);const d=T.uploadDocument({name:'a.pdf',type:'application/pdf',size:100});assert(T.getDocumentAccess(d.id).authorizationToken)});
test('44 reviewer can access clean scoped document',()=>{const a=account('app44');fillApp(a);const d=T.uploadDocument({name:'a.pdf',type:'application/pdf',size:100});T._test.documents().find(x=>x.id===d.id).scanStatus='CLEAN';T.getApplication(a).organizationId='org-a';const v=account('v44',[P.ROLES.ORGANIZATION_VERIFIER],{memberships:[{organizationId:'org-a',authorizationStatus:P.VERIFIER_STATUS.ACTIVE}]});currentAccount=v;assert(T.getDocumentAccess(d.id).authorizationToken)});
test('45 document authorization is short lived',()=>{const a=account('app45');fillApp(a);const d=T.uploadDocument({name:'a.pdf',type:'application/pdf',size:100});const access=T.getDocumentAccess(d.id);assert(new Date(access.expiresAt)-Date.now()<=300001)});
test('46 unsupported file rejected',()=>{const a=account('app46');fillApp(a);expectThrow(()=>T.uploadDocument({name:'a.txt',type:'text/plain',size:100}),/Only PDF/)});
test('47 oversized file rejected',()=>expectThrow(()=>T._test.validateDocument({name:'a.pdf',type:'application/pdf',size:T.MAX_FILE_SIZE+1}),/10 MB/));
test('48 executable file rejected',()=>expectThrow(()=>T._test.validateDocument({name:'a.exe',type:'application/pdf',size:100}),/Executable/));
test('49 public serializers exclude storage keys',()=>{const a=account('app49');assert(!/storageKey/.test(JSON.stringify(T.toPublicTutorProfile(a))))});
test('50 public tutor excludes documents',()=>{const a=account('app50');assert(!/document/i.test(JSON.stringify(T.toPublicTutorProfile(a))))});
test('51 document views are audited',()=>{const a=account('app51');fillApp(a);const d=T.uploadDocument({name:'a.pdf',type:'application/pdf',size:100});T.getDocumentAccess(d.id);assert(db.peerTutoringAuditLogs.some(x=>x.action==='TUTOR_DOCUMENT_VIEWED'&&x.targetId===d.id))});
for(const [i,term] of ['claimedResultValue','email','phone','homeAddress','schoolTimetable','guardian','internalDecisionNote','accessibility'].entries())test(`${52+i} public tutor excludes ${term}`,()=>{const a=account(`privacy-${i}`);const out=T.toPublicTutorProfile(a);assert(!new RegExp(term,'i').test(JSON.stringify(out)))});
test('60 motivation rejects contact information',()=>{const a=account('contact60');currentAccount=a;T.startApplication();expectThrow(()=>T.saveMotivation('I want to tutor. Contact me at private@example.com so I can explain how I support students and share more information.'),/contact/)});

let passed=0;for(const [name,fn] of tests){try{fn();passed++;console.log(`PASS ${name}`)}catch(e){console.error(`FAIL ${name}\n${e.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
