const fs=require('fs'),path=require('path'),assert=require('assert'),V=require('../visual-display.js');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8'),css=fs.readFileSync(path.join(root,'style.css'),'utf8'),profile=fs.readFileSync(path.join(root,'accessibility-language.js'),'utf8'),boot=fs.readFileSync(path.join(root,'accessibility-toolbar-boot.js'),'utf8'),visual=fs.readFileSync(path.join(root,'visual-display.js'),'utf8');
const tests=[];function test(name,fn){tests.push([name,fn])}
test('visual module reuses shared page',()=>assert(html.includes('<script src="visual-display.js"></script>')));
test('visual module loads after profile',()=>assert(html.indexOf('accessibility-language.js')<html.indexOf('visual-display.js')));
test('visual module loads before toolbar',()=>assert(html.indexOf('visual-display.js')<html.indexOf('accessibility-toolbar.js')));
test('no third party overlay added',()=>assert(!/accessiBe|UserWay|AudioEye|EqualWeb/i.test(html+visual)));
test('browser zoom remains enabled',()=>assert(/user-scalable\s*=\s*no|maximum-scale\s*=\s*1/i.test(html)===false));
test('same toolbar storage key is reused',()=>assert(visual.includes("studyspark.accessibilityToolbar.v1")));
test('same account profile API is reused',()=>assert(visual.includes('A.updateAccessibilityLanguageProfile')));
test('DEFAULT text scale migrates to MEDIUM',()=>assert.equal(V.migrateExistingVisualPreferences({textScale:'DEFAULT'}).textScale,'MEDIUM'));
test('SYSTEM text scale remains SYSTEM',()=>assert.equal(V.migrateExistingVisualPreferences({textScale:'SYSTEM'}).textScale,'SYSTEM'));
test('LARGE remains LARGE',()=>assert.equal(V.migrateExistingVisualPreferences({textScale:'LARGE'}).textScale,'LARGE'));
test('EXTRA LARGE remains EXTRA LARGE',()=>assert.equal(V.migrateExistingVisualPreferences({textScale:'EXTRA_LARGE'}).textScale,'EXTRA_LARGE'));
test('legacy narrow maps to short',()=>assert.equal(V.migrateExistingVisualPreferences({contentWidth:'NARROW'}).contentWidth,'SHORT'));
test('legacy reduced motion enabled migrates',()=>assert.equal(V.migrateExistingVisualPreferences({reducedMotionPreference:'ENABLED'}).motionMode,'REDUCED_MOTION'));
test('legacy reduced motion disabled migrates',()=>assert.equal(V.migrateExistingVisualPreferences({reducedMotionPreference:'DISABLED'}).motionMode,'STANDARD'));
test('legacy high contrast light migrates',()=>assert.equal(V.migrateExistingVisualPreferences({highContrastPreference:'ENABLED',displayMode:'LIGHT'}).contrastTheme,'HIGH_CONTRAST_LIGHT'));
test('legacy high contrast dark migrates',()=>assert.equal(V.migrateExistingVisualPreferences({highContrastPreference:'ENABLED',displayMode:'DARK'}).contrastTheme,'HIGH_CONTRAST_DARK'));
test('unrelated language survives migration',()=>assert.equal(V.migrateExistingVisualPreferences({primaryExplanationLanguageCode:'ar'}).primaryExplanationLanguageCode,'ar'));
test('small text is controlled',()=>assert(profile.includes("'SMALL'")));
test('medium text is controlled',()=>assert(profile.includes("'MEDIUM'")));
test('extra expanded line height is controlled',()=>assert(profile.includes("'EXTRA_EXPANDED'")));
test('reading alignment is controlled',()=>assert(profile.includes("readingAlignment:['SYSTEM','READING_DIRECTION_START']")));
test('paragraph spacing is controlled',()=>assert(profile.includes("paragraphSpacing:['SYSTEM','DEFAULT','RELAXED','EXPANDED']")));
test('contrast themes are controlled',()=>assert(profile.includes("'HIGH_CONTRAST_LIGHT','HIGH_CONTRAST_DARK'")));
test('motion modes are separate',()=>assert(profile.includes("'REDUCED_MOTION','ANIMATION_FREE'")));
test('simplified layout is one shared profile field',()=>assert(profile.includes('simplifiedLayoutEnabled:false')));
test('reading view preference is controlled',()=>assert(profile.includes('distractionReducedReadingPreference')));
test('small maps to safe 90 percent',()=>assert(boot.includes('SMALL:90')));
test('medium maps to 100 percent',()=>assert(boot.includes('MEDIUM:100')));
test('large maps to 125 percent',()=>assert(boot.includes('LARGE:125')));
test('extra large maps to 150 percent',()=>assert(boot.includes('EXTRA_LARGE:150')));
test('custom lower bound is validated',()=>assert.throws(()=>V.validateVisualDisplayPreferences({customTextScalePercent:99})));
test('custom upper bound is validated',()=>assert.throws(()=>V.validateVisualDisplayPreferences({customTextScalePercent:201})));
test('custom valid value accepted',()=>assert.equal(V.validateVisualDisplayPreferences({customTextScalePercent:175}).customTextScalePercent,175));
test('root visual attributes apply before body',()=>assert(boot.includes('document.documentElement')));
test('early boot applies contrast theme',()=>assert(boot.includes('contrastTheme:p.contrastTheme')));
test('early boot applies motion mode',()=>assert(boot.includes('motionMode:p.motionMode')));
test('early boot treats storage as untrusted',()=>assert(boot.includes('migrate(JSON.parse')));
test('relative root scaling is used',()=>assert(css.includes('font-size:calc(100% * var(--studyspark-text-scale))')));
test('semantic typography tokens exist',()=>['--studyspark-text-scale','--studyspark-line-height','--studyspark-letter-spacing','--studyspark-paragraph-spacing','--studyspark-reading-max-width'].forEach(x=>assert(css.includes(x))));
test('semantic colour tokens exist',()=>['--studyspark-page-background','--studyspark-primary-text','--studyspark-focus-ring','--studyspark-error-text','--studyspark-warning-text'].forEach(x=>assert(css.includes(x))));
test('high contrast does not use filters',()=>assert(!/data-contrast-theme[^}]*filter\s*:/s.test(css)));
test('high contrast light has semantic token override',()=>assert(css.includes('[data-contrast-theme="HIGH_CONTRAST_LIGHT"]')));
test('high contrast dark has semantic token override',()=>assert(css.includes('[data-contrast-theme="HIGH_CONTRAST_DARK"]')));
test('images are not inverted',()=>assert(!/img[^}]*invert\(/i.test(css)));
test('focus remains explicit',()=>assert(css.includes('outline:3px solid var(--studyspark-focus-ring)!important')));
test('forced colours remains supported',()=>assert(css.includes('@media(forced-colors:active)')));
test('reduced motion is separate',()=>assert(css.includes('[data-motion-mode="REDUCED_MOTION"]')));
test('animation free is stronger',()=>assert(css.includes('[data-motion-mode="ANIMATION_FREE"] *')));
test('animation free disables animations',()=>assert(css.includes('animation:none!important')));
test('reading alignment uses logical start',()=>assert(css.includes('text-align:start!important')));
test('non Latin scripts exclude added tracking',()=>assert(css.includes(':lang(ar),:lang(zh),:lang(ja),:lang(ko),:lang(he),:lang(hi)')));
test('code excludes display spacing',()=>assert(css.includes('code,pre,kbd,samp,.math')));
test('short line length is defined',()=>assert(css.includes('--studyspark-reading-max-width:58ch')));
test('tables use internal overflow',()=>assert(css.includes('.tutoring-table-wrap,.table-wrap{overflow:auto')));
test('buttons may wrap',()=>assert(css.includes('white-space:normal')));
test('controls retain 44 pixel minimum',()=>assert(css.includes('min-block-size:44px')));
test('dialogs constrain to viewport',()=>assert(css.includes('max-block-size:calc(100dvh - 2rem)')));
test('dialog action groups wrap',()=>assert(css.includes('.delete-actions,.access-pref-actions')));
test('320 pixel equivalent breakpoint exists',()=>assert(css.includes('@media(max-width:40rem)')));
test('simplified layout uses one column',()=>assert(css.includes('[data-page-layout="SIMPLIFIED"]')));
test('simplified layout hides only named decorative panels',()=>assert(css.includes('.float-card,.coach-tips,.date-card,.streak-card,.upgrade-box,.simulated-badge')));
test('reading view has explicit exit control',()=>assert(visual.includes('Exit distraction-reduced reading view')));
test('reading view excludes Study Rooms honestly',()=>assert(visual.includes('not applied to Study Rooms')));
test('reading view preserves scroll position',()=>assert(visual.includes('readingState.scrollY=scrollY')&&visual.includes('scrollTo(0,readingState.scrollY)')));
test('required inventory has all required categories',()=>assert.equal(V.REQUIRED_CATEGORIES.length,14));
test('equivalent inventories pass',()=>assert(V.validateVisualModeContentEquivalence({quizQuestionIds:['q1']},{quizQuestionIds:['q1']}).valid));
test('missing question fails equivalence',()=>assert(!V.validateVisualModeContentEquivalence({quizQuestionIds:['q1']},{quizQuestionIds:[]}).valid));
test('missing safety notice fails equivalence',()=>assert(!V.validateVisualModeContentEquivalence({safetyNoticeIds:['s1']},{safetyNoticeIds:[]}).valid));
test('missing primary action fails equivalence',()=>assert(!V.validateVisualModeContentEquivalence({primaryActionIds:['submit']},{primaryActionIds:[]}).valid));
test('inventory comparison is source id based',()=>assert(visual.includes('missing=a[key].filter')));
test('status success has icon and text',()=>assert(V.StatusIndicator({statusType:'SUCCESS',visibleLabel:'Saved'}).includes('✓')&&V.StatusIndicator({statusType:'SUCCESS',visibleLabel:'Saved'}).includes('Saved')));
test('status error uses alert sparingly',()=>assert(V.StatusIndicator({statusType:'ERROR',visibleLabel:'Error'}).includes('role="alert"')));
test('offline status has visible text',()=>assert(V.StatusIndicator({statusType:'OFFLINE',visibleLabel:'Offline'}).includes('Offline')));
test('quiz correct state gains text',()=>assert(visual.includes("'✓ Correct'")));
test('quiz wrong state gains text',()=>assert(visual.includes("'✕ Try again'")));
test('selected answer has visible and native cues',()=>assert(css.includes('● Selected')&&css.includes('input:checked')));
test('device serializer is allowlisted',()=>assert.deepStrictEqual(Object.keys(V.toVisualDevicePreferenceSnapshot(V.DEFAULTS)).sort(),V.FIELDS.slice().sort()));
test('device snapshot excludes identity',()=>['userId','email','diagnosis','guardian','token','course'].forEach(key=>assert(!V.FIELDS.includes(key))));
test('capability registry is honest about manual tests',()=>Object.values(V.getVisualDisplayCapabilityRegistry()).forEach(item=>assert.equal(item.manualTestStatus,'PENDING')));
test('high zoom capability is partial',()=>assert.equal(V.getVisualDisplayCapabilityRegistry().HIGH_ZOOM_REFLOW.availability,'PARTIAL'));
test('colour independence capability is partial',()=>assert.equal(V.getVisualDisplayCapabilityRegistry().COLOUR_INDEPENDENT_STATUS.availability,'PARTIAL'));
test('toolbar controls include every quick option',()=>['textScale','lineSpacing','letterSpacing','contentWidth','contrastTheme','motionMode','simplifiedLayoutEnabled'].forEach(field=>assert(visual.includes(`'${field}'`))));
test('full settings and toolbar share control renderer',()=>assert(visual.includes("insertAdjacentHTML('afterbegin',controls())")));
test('presentation contract wording is present',()=>assert(visual.includes('Course content, objectives, reasoning, terminology, assessment, deadlines, safety and integrity information remain unchanged.')));
test('no diagnosis collection field added',()=>assert(!/name=["']diagnosis/i.test(html+visual)));
test('no analytics values emitted',()=>assert(!/analytics|trackEvent|dataLayer/.test(visual)));
let passed=0;for(const [name,fn]of tests){try{fn();passed++;console.log(`PASS ${name}`)}catch(error){console.error(`FAIL ${name}\n${error.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
