'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const Recovery = require('../academic-recovery.js');
let passed = 0;
function test(name, fn) { try { fn(); passed += 1; } catch (error) { console.error(`FAIL: ${name}\n${error.stack}`); process.exitCode = 1; } }
function throwsCode(fn, code) { assert.throws(fn, error => error && error.code === code); }
const actor = { userId: 'student-a', organizationId: 'school-a', role: 'student' };
const other = { userId: 'student-b', organizationId: 'school-a', role: 'student' };
const base = { entrySource: 'STUDENT_DASHBOARD', sourceRouteKey: 'dashboard' };

test('entry-source enum is complete', () => assert.strictEqual(Recovery.AcademicRecoveryEntrySource.length, 11));
for (const source of Recovery.AcademicRecoveryEntrySource) test(`accepts entry source ${source}`, () => assert.strictEqual(Recovery.validateRecoveryEntrySource(source), source));
test('unknown entry source is rejected', () => throwsCode(() => Recovery.validateRecoveryEntrySource('RISK_DASHBOARD'), 'INVALID_ENTRY_SOURCE'));
test('mode enum is exact', () => assert.deepStrictEqual(Recovery.AcademicRecoveryMode, ['QUICK_RESCUE_24_HOURS', 'FULL_RECOVERY_7_DAYS']));
for (const mode of Recovery.AcademicRecoveryMode) test(`accepts mode ${mode}`, () => assert.strictEqual(Recovery.validateRecoveryMode(mode), mode));
test('unknown mode is rejected', () => throwsCode(() => Recovery.validateRecoveryMode('EMERGENCY_MODE'), 'INVALID_RECOVERY_MODE'));
test('session status enum is complete', () => assert.strictEqual(Recovery.AcademicRecoverySessionStatus.length, 8));
for (const status of Recovery.AcademicRecoverySessionStatus) test(`accepts status ${status}`, () => assert.strictEqual(Recovery.validateRecoverySessionStatus(status), status));
test('opening does not create a session', () => assert.strictEqual(Recovery.listMyActiveAcademicRecoverySessions(actor).length, 0));
test('mode validation does not create a session', () => { Recovery.selectAcademicRecoveryMode('QUICK_RESCUE_24_HOURS'); assert.strictEqual(Recovery.listMyActiveAcademicRecoverySessions(actor).length, 0); });
test('explicit action creates one mode-selected draft', () => { const result = Recovery.createAcademicRecoverySessionDraft({ ...base, selectedMode: 'QUICK_RESCUE_24_HOURS', idempotencyKey: 'request-1' }, actor); assert.strictEqual(result.session.status, 'MODE_SELECTED'); assert.strictEqual(result.session.selectedMode, 'QUICK_RESCUE_24_HOURS'); });
test('duplicate request is idempotent', () => { const result = Recovery.createAcademicRecoverySessionDraft({ ...base, selectedMode: 'QUICK_RESCUE_24_HOURS', idempotencyKey: 'request-1' }, actor); assert.strictEqual(result.duplicatePrevented, true); assert.strictEqual(Recovery.listMyActiveAcademicRecoverySessions(actor).length, 1); });
test('same active mode is reused with a new request key', () => { const result = Recovery.createAcademicRecoverySessionDraft({ ...base, selectedMode: 'QUICK_RESCUE_24_HOURS', idempotencyKey: 'request-2' }, actor); assert.strictEqual(result.reusedExisting, true); assert.strictEqual(Recovery.listMyActiveAcademicRecoverySessions(actor).length, 1); });
test('full recovery creates a separate draft', () => { Recovery.createAcademicRecoverySessionDraft({ ...base, entrySource: 'STUDY_PLAN', selectedMode: 'FULL_RECOVERY_7_DAYS', idempotencyKey: 'request-3' }, actor); assert.strictEqual(Recovery.listMyActiveAcademicRecoverySessions(actor).length, 2); });
test('session owner is derived from actor', () => { const result = Recovery.createAcademicRecoverySessionDraft({ ...base, userId: 'student-b', entrySource: 'AI_COACH', selectedMode: 'FULL_RECOVERY_7_DAYS', idempotencyKey: 'request-4' }, actor); assert.ok(result.session.id); assert.strictEqual(Object.hasOwn(result.session, 'userId'), false); });
test('other student cannot read session', () => { const id = Recovery.listMyActiveAcademicRecoverySessions(actor)[0].id; throwsCode(() => Recovery.getMyAcademicRecoverySession(id, other), 'SESSION_NOT_FOUND'); });
test('missing authentication is rejected', () => throwsCode(() => Recovery.listMyActiveAcademicRecoverySessions({}), 'NOT_SIGNED_IN'));
test('non-student actor is rejected', () => throwsCode(() => Recovery.listMyActiveAcademicRecoverySessions({ userId: 'teacher-a', role: 'teacher' }), 'STUDENT_ACCESS_REQUIRED'));
test('idempotency key is required', () => throwsCode(() => Recovery.createAcademicRecoverySessionDraft({ ...base, selectedMode: 'QUICK_RESCUE_24_HOURS' }, actor), 'IDEMPOTENCY_REQUIRED'));
for (const field of ['lazinessScore', 'studentFailureLevel', 'motivationScore', 'emotionalWeakness', 'riskOfFailure', 'irresponsibility', 'likelyToSucceed', 'diagnosis', 'depression', 'anxiety', 'burnout', 'homeConflict', 'parentSupportLevel']) test(`rejects forbidden field ${field}`, () => throwsCode(() => Recovery.getAuthorizedRecoveryEntryContext({ ...base, [field]: 'value' }), 'FORBIDDEN_RECOVERY_FIELD'));
test('private task title is not represented in context view', () => { const view = Recovery.toAcademicRecoveryEntryView({ ...base, taskTitle: 'Private assignment title' }); assert.strictEqual(JSON.stringify(view).includes('Private assignment title'), false); });
test('source identifiers are normalized', () => { const context = Recovery.getAuthorizedRecoveryEntryContext({ ...base, sourceCourseId: 'course-1?<private>', sourceAssignmentId: 'assignment-2' }); assert.strictEqual(context.sourceCourseId, 'course-1private'); assert.strictEqual(context.sourceAssignmentId, 'assignment-2'); });
test('invalid calendar dates are excluded', () => assert.strictEqual(Recovery.getAuthorizedRecoveryEntryContext({ ...base, sourceCalendarDate: 'Monday private' }).sourceCalendarDate, null));
test('owner serializer excludes organization and prototype markers', () => { const row = Recovery.listMyActiveAcademicRecoverySessions(actor)[0]; const view = Recovery.toAcademicRecoverySessionOwnerView(row); assert.strictEqual(Object.hasOwn(view, 'organizationId'), false); assert.strictEqual(Object.hasOwn(view, 'prototypeOnly'), false); });
test('public serializer is empty', () => assert.deepStrictEqual(Recovery.toPublicView(Recovery.listMyActiveAcademicRecoverySessions(actor)[0]), {}));
test('capabilities use controlled states', () => Object.values(Recovery.getAcademicRecoveryCapabilities()).forEach(value => assert.ok(Recovery.AcademicRecoveryCapabilityState.includes(value))));
test('pause preserves session without completion', () => { const id = Recovery.listMyActiveAcademicRecoverySessions(actor)[0].id; assert.strictEqual(Recovery.pauseAcademicRecoverySession(id, actor).status, 'PAUSED'); });
test('resume marks only explicit resume in progress', () => { const id = Recovery.listMyActiveAcademicRecoverySessions(actor)[0].id; assert.strictEqual(Recovery.resumeAcademicRecoverySession(id, actor).status, 'IN_PROGRESS'); });
test('abandon does not label a plan failed', () => { const id = Recovery.listMyActiveAcademicRecoverySessions(actor)[0].id; assert.strictEqual(Recovery.abandonAcademicRecoverySession(id, actor).status, 'ABANDONED'); assert.strictEqual(JSON.stringify(Recovery.getMyAcademicRecoverySession(id, actor)).toLowerCase().includes('failed'), false); });
test('archive is explicit', () => { const id = Recovery.listMyActiveAcademicRecoverySessions(actor)[1].id; assert.strictEqual(Recovery.archiveAcademicRecoverySession(id, actor).status, 'ARCHIVED'); });
test('offline choice does not create a cloud session', () => { const before = Recovery.listMyActiveAcademicRecoverySessions(other).length; const value = Recovery.saveOfflineRecoveryChoice('FULL_RECOVERY_7_DAYS', base, other); assert.strictEqual(value.pendingExplicitContinue, true); assert.strictEqual(Recovery.listMyActiveAcademicRecoverySessions(other).length, before); });
test('device cleanup is user scoped', () => { Recovery.removeRecoveryDataFromDevice(other); assert.strictEqual(Recovery.listMyActiveAcademicRecoverySessions(other).length, 0); assert.ok(Recovery.listMyActiveAcademicRecoverySessions(actor).length >= 0); });
for (const event of ['RECOVERY_ENTRY_DISPLAYED', 'RECOVERY_ENTRY_OPENED', 'QUICK_RESCUE_SELECTED', 'FULL_RECOVERY_SELECTED', 'ENTRY_SCREEN_EXITED', 'EXISTING_PLAN_RESUMED', 'TECHNICAL_ERROR']) test(`allows aggregate event ${event}`, () => { const value = Recovery.createPrivacySafeRecoveryAnalyticsEvent(event, base); assert.deepStrictEqual(Object.keys(value).sort(), ['entrySource', 'event', 'occurredAt']); });
test('unknown analytics is rejected', () => throwsCode(() => Recovery.createPrivacySafeRecoveryAnalyticsEvent('OVERWHELM_SCORE', base), 'ANALYTICS_EVENT_REJECTED'));
test('supportive copy contains central message', () => assert.strictEqual(Recovery.COPY.central, 'The plan can change. You have not failed. Let’s choose the next achievable action.'));
test('primary action is canonical', () => assert.strictEqual(Recovery.COPY.action, 'Help Me Catch Up'));
test('accessible action is descriptive', () => assert.ok(Recovery.COPY.accessibleAction.includes('academic recovery plan')));
test('privacy copy prohibits automatic sending', () => assert.ok(Recovery.COPY.privacy.includes('unless you review it and choose to send it')));
test('policy copy makes no deadline promise', () => assert.ok(Recovery.COPY.policy.includes('cannot guarantee')));
test('quick copy protects essentials', () => { const copy = Recovery.MODE_DETAILS.QUICK_RESCUE_24_HOURS.description; ['sleep', 'meals', 'medical care', 'essential responsibilities'].forEach(term => assert.ok(copy.includes(term))); });
test('full copy permits work to wait', () => assert.ok(Recovery.MODE_DETAILS.FULL_RECOVERY_7_DAYS.description.includes('may need to wait')));
test('copy contains no all-nighter advice', () => assert.strictEqual(JSON.stringify({ copy: Recovery.COPY, details: Recovery.MODE_DETAILS }).toLowerCase().includes('all-nighter'), false));
test('source contains no scoring fields', () => { const source = fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.js'), 'utf8'); for (const term of ['recovery dependence score', 'behind score', 'overwhelm score']) assert.strictEqual(source.toLowerCase().includes(term), false); });
test('HTML loads shared recovery assets', () => { const html = fs.readFileSync(path.join(__dirname, '..', 'index (2).html'), 'utf8'); assert.ok(html.includes('academic-recovery.css')); assert.ok(html.includes('academic-recovery.js')); });
test('dashboard source is wired', () => assert.ok(fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.js'), 'utf8').includes("buttonHTML('STUDENT_DASHBOARD'")));
test('planner workload actions contain two entries', () => assert.strictEqual(Recovery.PLANNER_WORKLOAD_ACTIONS.length, 2));
test('planner workload action IDs are unique', () => assert.strictEqual(new Set(Recovery.PLANNER_WORKLOAD_ACTIONS.map(action => action.id)).size, 2));
test('planner workload labels are exact', () => assert.deepStrictEqual(Recovery.PLANNER_WORKLOAD_ACTIONS.map(action => action.label), ['Help Me Catch Up', 'Adjust My Plan']));
test('planner workload sources are assignment and study plan', () => assert.deepStrictEqual(Recovery.PLANNER_WORKLOAD_ACTIONS.map(action => action.source), ['ASSIGNMENT_TRACKER', 'STUDY_PLAN']));
test('AI Coach source is wired', () => assert.ok(fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.js'), 'utf8').includes("buttonHTML('AI_COACH'")));
test('calendar remains an authorized recovery source', () => assert.ok(Recovery.AcademicRecoveryEntrySource.includes('CALENDAR')));
test('course source is wired', () => assert.ok(fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.js'), 'utf8').includes("'COURSE_PAGE'")));
test('mobile source is wired', () => assert.ok(fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.js'), 'utf8').includes('MOBILE_NAVIGATION')));
test('overdue notification source is wired', () => assert.ok(fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.js'), 'utf8').includes("buttonHTML('OVERDUE_TASK_NOTIFICATION'")));
test('opening screen includes all required actions', () => { const source = fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.js'), 'utf8'); ['Not Now', 'Return to Previous Page', 'Learn How Recovery Plans Work'].forEach(label => assert.ok(source.includes(label))); });
test('responsive and forced-colour CSS exists', () => { const css = fs.readFileSync(path.join(__dirname, '..', 'academic-recovery.css'), 'utf8'); assert.ok(css.includes('@media(max-width:42rem)')); assert.ok(css.includes('@media(forced-colors:active)')); assert.ok(css.includes('focus-visible')); });

if (!process.exitCode) console.log(`academic-recovery: ${passed}/${passed} assertions passed`);
