'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),M=require('../academic-recovery-output.js');
let p=0,n=0;
function t(s,f){n++;try{f();p++}catch(e){console.error(`FAIL ${s}: ${e.message}`);process.exitCode=1}}
const actor={userId:'s36'};
const o=M.generateRecoveryOutput({recoverySessionId:'r36',subjectUserId:'s36',localDate:'2026-08-11',timezone:'America/Toronto',wednesdayDate:'2026-08-12',sourceVersion:3},actor);
for(const[k,v]of Object.entries({RecoveryFactStatus:6,RecoveryOutputFeasibilityStatus:8,RecoveryTriageCategory:5,RecoveryOutputStatus:11,RecoveryOutputSourceStatus:7}))t(k,()=>assert.strictEqual(M[k].length,v));
for(const x of Object.values(M.COPY))t('required copy',()=>assert.ok(x.length>40));
t('three upcoming',()=>assert.strictEqual(o.studentSituation.upcoming.length,3));
t('six missing',()=>assert.strictEqual(o.studentSituation.missing.length,6));
t('exact date',()=>assert.strictEqual(o.studentSituation.upcoming[0].date,'2026-08-13'));
t('relative preserved',()=>assert.strictEqual(o.studentSituation.upcoming[0].original,'in 2 days'));
t('today capacity',()=>assert.strictEqual(o.feasibility.confirmedTodayMinutes,45));
t('capacity conflict',()=>assert.strictEqual(o.studentSituation.capacity[1].date,o.studentSituation.capacity[2].date));
t('conflict not summed',()=>assert.deepStrictEqual(o.sevenDay.capacityConflict.entries,[90,60]));
t('conflict copy',()=>assert.ok(o.sevenDay.capacityConflict.message.includes('90 minutes, 60 minutes')));
const expected={DO_NOW:['Mathematics prerequisite review','Chemistry lab outline'],ASK_FIRST:['Confirm which English assignments are still accepted','Confirm whether the History reflection is still required'],DO_NEXT:['Computer Science project task breakdown','Mathematics test practice'],SCHEDULE_LATER:['Accepted English assignment'],CONSIDER_RELEASING:['Any task the teacher confirms is no longer required']};
for(const[c,items]of Object.entries(expected))for(const item of items)t(`${c} ${item}`,()=>assert.ok(o.triage.some(x=>x.category===c&&x.title===item&&x.explanation)));
t('no automatic release',()=>assert.ok(o.triage.every(x=>!x.automaticRelease)));
t('minimum 35',()=>assert.strictEqual(o.today.totalMinutes,35));
t('80 percent maximum',()=>assert.strictEqual(o.feasibility.maximumScheduledByDefault,36));
t('buffer 10',()=>assert.strictEqual(o.today.protectedBufferMinutes,10));
t('capacity percent 78',()=>assert.strictEqual(o.today.capacityPercent,78));
t('stretch optional',()=>assert.strictEqual(o.today.stretch.optional,true));
t('stretch unscheduled',()=>assert.strictEqual(o.today.stretch.status,'NOT_CURRENTLY_SCHEDULED'));
t('three minimum actions',()=>assert.strictEqual(o.today.minimumPlan.length,3));
for(const [title,min] of [['Draft English teacher message',5],['Review Factoring prerequisite',20],['Open the Chemistry rubric and list requirements',10]])t(title,()=>assert.ok(o.today.minimumPlan.some(x=>x.title===title&&x.minutes===min&&x.definitionOfDone)));
t('one next action',()=>assert.strictEqual(o.today.nextAction.id,'english-message'));
t('finish available',()=>assert.strictEqual(o.today.finishForTodayAvailable,true));
t('message draft unsent',()=>assert.strictEqual(o.askForHelp.sent,false));
t('no output attachment',()=>assert.strictEqual(o.askForHelp.fullOutputAttached,false));
t('no other courses',()=>assert.strictEqual(o.askForHelp.otherCoursesShared,false));
t('seven days',()=>assert.strictEqual(o.sevenDay.days.length,7));
t('not minute schedule',()=>assert.strictEqual(o.sevenDay.minuteByMinute,false));
t('five risks',()=>assert.strictEqual(o.risks.length,5));
for(const x of o.risks)t(`risk ${x.risk}`,()=>assert.ok(x.resolutionAction&&!x.addressed));
t('five triggers',()=>assert.strictEqual(o.recalculationTriggers.length,5));
for(const[k,v]of Object.entries({automaticActivation:false,automaticSending:false,automaticBooking:false,automaticRelease:false,globalScore:false,streak:false,points:false}))t(k,()=>assert.strictEqual(o[k],v));
t('private',()=>assert.strictEqual(o.privacy.privateByDefault,true));
t('not shared',()=>assert.strictEqual(o.privacy.automaticSharing,false));
const st=M.startRecoveryOutputAction(o.today.nextAction,actor);
for(const[k,v]of Object.entries({opened:true,timerStarted:false,completed:false,messageSent:false,submitted:false,planActivated:false}))t(`start ${k}`,()=>assert.strictEqual(st[k],v));
const ap=M.approveRecoveryOutput(o,actor);
t('student approved',()=>assert.strictEqual(ap.status,'STUDENT_APPROVED'));
t('approval no active change',()=>assert.strictEqual(ap.activePlanChanged,false));
t('separate activation',()=>assert.strictEqual(ap.activationRequiresSeparateAction,true));
const off=M.toRecoveryOutputOfflineView(o);
for(const[k,v]of Object.entries({status:'OFFLINE_CACHED',sourceStatus:'OFFLINE_CACHED',teacherMessageDraftOnly:true,bookingAvailable:false,planActivationAvailable:false,revalidationRequired:true,duplicateOutputPrevented:true,studentEditsPreserved:true}))t(`offline ${k}`,()=>assert.strictEqual(off[k],v));
for(const f of ['toRecoveryOutputTeacherView','toRecoveryOutputParentView','toRecoveryOutputTutorView','toRecoveryOutputAdministratorView'])t(f,()=>assert.deepStrictEqual(M[f](),{}));
t('safety replacement',()=>assert.strictEqual(M.generateRecoveryOutput({subjectUserId:'s36',safetyFlowActive:true},actor).ordinaryOutputHidden,true));
t('sixteen UI areas',()=>{const x=fs.readFileSync(path.join(__dirname,'..','academic-recovery-output.js'),'utf8');for(const y of ['Recovery Summary','Student Situation','Confirmed, Estimated, and Unknown Information','Workload Feasibility','StudySpark Triage',"Today’s Minimum Plan",'Protected Buffer','Optional Stretch Candidates','Ask for Help','Seven-Day Preview','Upcoming Risks','Progress Already Preserved','Recalculation Triggers','Next Review Point','Privacy and Sharing Status','Accessibility and Language Controls','Minimum Plan: 35 minutes','Not currently scheduled'])assert.ok(x.includes(y))});
t('CSS contracts',()=>{const x=fs.readFileSync(path.join(__dirname,'..','academic-recovery-output.css'),'utf8');for(const y of ['@media(max-width:42rem)','forced-colors','prefers-reduced-motion','[dir=rtl]',':focus-visible','@media print'])assert.ok(x.includes(y))});
t('loader order',()=>{const h=fs.readFileSync(path.join(__dirname,'..','index (2).html'),'utf8');assert.ok(h.indexOf('academic-recovery-teacher-support.js')<h.indexOf('academic-recovery-output.js'))});
if(!process.exitCode)console.log(`academic-recovery-output: ${p}/${n} assertions passed`);
