const fs=require('fs'),path=require('path'),assert=require('assert'),root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index (2).html'),'utf8');
const css=fs.readFileSync(path.join(root,'style.css'),'utf8');
const toolbar=fs.readFileSync(path.join(root,'accessibility-toolbar.js'),'utf8');
const profile=fs.readFileSync(path.join(root,'accessibility-language.js'),'utf8');
let passed=0;
function check(name,value){assert.ok(value,name);passed++;console.log(`PASS ${name}`)}
check('boot applies saved preferences before body',html.indexOf('accessibility-toolbar-boot.js')<html.indexOf('<body>'));
check('accessibility toolbar loads once',(html.match(/accessibility-toolbar\.js/g)||[]).length===1);
check('no third-party overlay added',!/accessiBe|UserWay|AudioEye|EqualWeb/i.test(toolbar+html));
check('header launcher is a button',toolbar.includes('id="accessibilityToolbarLauncher"'));
check('header launcher has an accessible name',toolbar.includes('aria-label="Open Accessibility and Language settings"'));
check('header launcher is mounted in top actions',toolbar.includes("querySelector('.app-topbar .top-actions')")&&toolbar.includes('host.prepend(root)'));
check('launcher opens full settings directly',toolbar.includes("showView('accessibilityLanguage')"));
check('launcher does not render the old panel',!/root\.innerHTML=panelHTML\(\)/.test(toolbar));
check('launcher is in normal layout',/\.accessibility-toolbar-launcher\{position:static/.test(css));
check('launcher is never fixed on mobile',/@media\(max-width:700px\)\{\.top-actions \.accessibility-toolbar-launcher\{[^}]*position:static/.test(css));
check('legacy panel cannot display',/\.accessibility-toolbar-panel\{display:none!important\}/.test(css));
check('launcher has a 44 pixel target',/accessibility-toolbar-launcher\{[^}]*width:44px[^}]*height:44px/.test(css));
check('full settings page remains',html.includes('id="accessibilityLanguageView"')&&html.includes('id="accessibilityLanguageContent"'));
check('full settings include text size',profile.includes('Text size')&&profile.includes("data-pref-field=\"${esc(field)}\""));
check('full settings include high contrast',profile.includes('High Contrast')&&profile.includes('contrastTheme'));
check('full settings include reading friendly display',profile.includes('dyslexiaFriendlyDisplayEnabled'));
check('full settings include language controls',profile.includes('Interface Language')&&profile.includes('Home Language'));
check('device key remains versioned',toolbar.includes('studyspark.accessibilityToolbar.v1'));
check('device snapshot retains schema version',toolbar.includes('schemaVersion:1'));
check('device snapshot excludes identity',!/snapshot[^\n]*(userId|email|studentId)/.test(toolbar));
check('device input is validated',toolbar.includes('validate(JSON.parse(localStorage.getItem'));
check('storage failure retains memory fallback',toolbar.includes("return 'session'"));
check('saved settings still apply',toolbar.includes('A.applyVisualPreferences(p)'));
check('cross-tab synchronization remains',toolbar.includes('BroadcastChannel')&&toolbar.includes("addEventListener('storage'"));
check('reconnection synchronization remains',toolbar.includes("addEventListener('online'"));
check('TTS never starts automatically',!/speechSynthesis\.(speak|resume)/.test(toolbar));
check('toolbar never requests a microphone',!/getUserMedia|mediaDevices/.test(toolbar));
check('low bandwidth behavior remains',toolbar.includes('m.autoplay=false')&&toolbar.includes("i.loading='lazy'"));
check('forced colours remain supported',/forced-colors:active/.test(css));
check('profile loads before header launcher',html.indexOf('accessibility-language.js')<html.indexOf('accessibility-toolbar.js'));
console.log(`${passed}/30 tests passed`);
