'use strict';
const assert=require('assert'),S=require('../accessible-resource-studio.js'),Q=require('../accessibility-quality-checks.js');let n=0;const t=(x,f)=>{f();n++};
t('six modes',()=>assert.equal(Q.AccessibilityCheckMode.length,6));
t('nine outcomes',()=>assert.equal(Q.AccessibilityCheckOutcome.length,9));
t('nine methods',()=>assert.equal(Q.AccessibilityCheckMethod.length,9));
t('four confidence levels',()=>assert.equal(Q.AccessibilityCheckConfidence.length,4));
t('eight owners',()=>assert.equal(Q.AccessibilityIssueOwnership.length,8));
t('25 categories',()=>assert.equal(Q.AccessibilityCheckCategory.length,25));
t('unknown mode rejected',()=>assert.throws(()=>Q.run([],{id:'x'},{mode:'BAD'}),/Unknown/));
t('rule per studio issue code',()=>assert.equal(Q.ruleRegistry.length,S.IssueCode.length));
t('rule versions present',()=>assert.ok(Q.ruleRegistry.every(r=>r.ruleVersion)));
t('rule methods controlled',()=>assert.ok(Q.ruleRegistry.every(r=>Q.AccessibilityCheckMethod.includes(r.checkMethod))));
t('rule categories controlled',()=>assert.ok(Q.ruleRegistry.every(r=>Q.AccessibilityCheckCategory.includes(r.category))));
t('no false compliance rule',()=>assert.ok(Q.ruleRegistry.every(r=>!/compliant|100% accessible/i.test(r.title))));
const teacher={id:'qc-teacher',role:'TEACHER',serverVerified:true,organizationId:'school-qc'};
const resource=S.resource({id:'qc-resource',version:'10',type:'INSTRUCTION_SET',title:'Quality lesson',ownerId:'qc-teacher',organizationId:'school-qc',language:'en',policyVersion:'policy-2',content:{text:'Click here and open it and press the button and complete the above.',colorOnly:true}});S.state.resources.push(resource);
const checked=Q.run([resource],teacher,{mode:'FULL_PREPUBLISH_CHECK',policyVersion:'policy-2'});
t('run completes',()=>assert.equal(checked.run.status,'COMPLETED'));
t('full mode stored',()=>assert.equal(checked.run.mode,'FULL_PREPUBLISH_CHECK'));
t('source version stored',()=>assert.equal(checked.run.sourceResources[0].resourceVersion,'10'));
t('source hash stored',()=>assert.equal(checked.run.sourceResources[0].contentHash,resource.contentHash));
t('scanner version stored',()=>assert.ok(checked.run.scannerVersion));
t('policy version stored',()=>assert.equal(checked.run.policyVersion,'policy-2'));
t('limitation exact',()=>assert.equal(checked.notice,S.AUTOMATED_ACCESSIBILITY_CHECK_LIMITATION_NOTICE));
t('results identify method',()=>assert.ok(checked.results.every(r=>Q.AccessibilityCheckMethod.includes(r.method))));
t('results identify rule version',()=>assert.ok(checked.results.every(r=>r.ruleVersion)));
t('results identify scanner version',()=>assert.ok(checked.results.every(r=>r.scannerVersion)));
t('results identify source hash',()=>assert.ok(checked.results.every(r=>r.sourceContentHash===resource.contentHash)));
t('heuristic is warning',()=>assert.ok(checked.results.some(r=>r.ruleCode==='INSTRUCTIONS_VAGUE_CONTROL_NAME'&&r.outcome==='WARNING')));
t('heuristic label is possible',()=>assert.ok(checked.results.some(r=>r.outcome==='WARNING'&&r.label==='Possible issue — human review required')));
t('heuristic confidence plain enum',()=>assert.ok(checked.results.filter(r=>r.outcome==='WARNING').every(r=>r.confidence==='MEDIUM')));
t('deterministic is fail',()=>assert.ok(checked.results.some(r=>r.ruleCode==='COLOR_ONLY_INFORMATION'&&r.outcome==='FAIL')));
t('human review separate',()=>assert.ok(checked.results.some(r=>r.outcome==='REQUIRES_HUMAN_REVIEW')));
t('five default human tasks',()=>assert.equal(checked.humanReviews.length,5));
t('automated does not pass human task',()=>assert.ok(checked.humanReviews.every(r=>r.status==='NOT_STARTED')));
t('checklist human status',()=>assert.ok(Q.checklist(checked.results).some(r=>r.status==='HUMAN_REVIEW_REQUIRED')));
t('checklist warning attention',()=>assert.ok(Q.checklist(checked.results).some(r=>r.status==='NEEDS_ATTENTION')));
t('unable never maps pass',()=>assert.equal(Q.checklist([{id:'x',ruleCode:'X',outcome:'UNABLE_TO_TEST',method:'STATIC_ANALYSIS'}])[0].status,'UNABLE_TO_TEST'));
t('not tested never maps pass',()=>assert.equal(Q.checklist([{id:'x',ruleCode:'X',outcome:'NOT_TESTED',method:'STATIC_ANALYSIS'}])[0].status,'UNABLE_TO_TEST'));
t('error never maps pass',()=>assert.equal(Q.checklist([{id:'x',ruleCode:'X',outcome:'ERROR',method:'STATIC_ANALYSIS'}])[0].status,'UNABLE_TO_TEST'));
t('sensitive evidence removed',()=>{const e=Q.sanitizeEvidence({location:'button',hiddenAnswers:['x'],learnerDiagnoses:'x',nested:{privateTranscripts:'x',safe:'yes'}});assert.deepEqual(e,{location:'button',nested:{safe:'yes'}})});
t('client cannot complete human review',()=>assert.throws(()=>Q.completeHumanReview(checked.humanReviews[0].id,{id:'x',role:'TEACHER',serverVerified:false},{decision:'PASS',evidence:'Keyboard journey completed.'}),/Trusted/));
t('human evidence required',()=>assert.throws(()=>Q.completeHumanReview(checked.humanReviews[0].id,teacher,{decision:'PASS',evidence:'short'}),/evidence/));
t('authorized human review',()=>assert.equal(Q.completeHumanReview(checked.humanReviews[0].id,teacher,{decision:'PASS',evidence:'Completed full keyboard journey.'}).status,'PASS'));
t('browser pass rejected',()=>assert.throws(()=>Q.gate(resource,teacher,{clientClaimsPassed:true}),/Browser/));
t('stale version rejected',()=>assert.throws(()=>Q.gate(resource,teacher,{expectedVersion:'9',expectedContentHash:resource.contentHash}),/Source changed/));
t('stale hash rejected',()=>assert.throws(()=>Q.gate(resource,teacher,{expectedVersion:'10',expectedContentHash:'old'}),/Source changed/));
t('incomplete human blocks',()=>assert.throws(()=>Q.gate(resource,teacher,{expectedVersion:'10',expectedContentHash:resource.contentHash,policy:{blockCritical:false,blockHigh:false,requireHumanReview:true}}),/human/));
const image=S.resource({id:'qc-image',version:'1',type:'IMAGE',ownerId:'other',organizationId:'school-qc',language:'en',content:{}});S.state.resources.push(image);const irun=Q.run([image],{id:'other',role:'TEACHER',serverVerified:true,organizationId:'school-qc'},{mode:'FULL_PREPUBLISH_CHECK'}),imageIssue=irun.issues.find(i=>i.code==='IMAGE_MISSING_ALT');
t('creator cannot approve own exception',()=>assert.throws(()=>Q.exception(imageIssue.id,{id:'other',role:'ACCESSIBILITY_REVIEWER',serverVerified:true},{reason:'x',reviewDate:'2026-12-01'}),/own/));
t('tutor cannot approve exception',()=>assert.throws(()=>Q.exception(imageIssue.id,{id:'tutor',role:'VERIFIED_TUTOR',serverVerified:true},{reason:'x',reviewDate:'2026-12-01'}),/reviewer/));
t('exception reason required',()=>assert.throws(()=>Q.exception(imageIssue.id,{id:'reviewer',role:'ACCESSIBILITY_REVIEWER',serverVerified:true},{reviewDate:'2026-12-01'}),/Reason/));
t('exception accepted by independent reviewer',()=>assert.equal(Q.exception(imageIssue.id,{id:'reviewer',role:'ACCESSIBILITY_REVIEWER',serverVerified:true},{reason:'Equivalent adjacent text is available.',equivalentAlternative:'Adjacent visible description',reviewDate:'2026-12-01'}).status,'ACCEPTED'));
Q.invalidate('qc-resource','11','new-hash');
t('run invalidated',()=>assert.equal(Q.state.runs.find(r=>r.id===checked.run.id).status,'OUTDATED'));
t('results invalidated',()=>assert.ok(checked.results.every(r=>r.outcome==='OUTDATED')));
t('human reviews invalidated',()=>assert.ok(checked.humanReviews.every(r=>r.status==='OUTDATED')));
t('notice has no guarantee',()=>assert.ok(!/guarantee|fully compliant|100% accessible/i.test(Q.AUTOMATED_ACCESSIBILITY_CHECK_LIMITATION_NOTICE)));
t('sensitive key inventory',()=>assert.ok(Q.sensitiveKeys.includes('activeTestContent')&&Q.sensitiveKeys.includes('voiceRecordings')));
console.log(`accessibility-quality-checks: ${n}/${n} assertions passed`);
