'use strict';
const assert=require('assert'),S=require('../accessible-resource-studio.js');let n=0;
const t=(name,fn)=>{fn();n++};
const teacher={id:'teacher-1',role:'TEACHER',serverVerified:true,organizationId:'school-1'};
t('resource enum',()=>assert.equal(S.AccessibleResourceType.length,33));
t('role enum',()=>assert.equal(S.AccessibleResourceAuthorRole.length,5));
t('issue enum',()=>assert.equal(S.IssueCode.length,39));
t('unknown type rejected',()=>assert.throws(()=>S.resource({id:'x',version:'1',type:'BAD'}),/Unknown/));
t('browser role rejected',()=>assert.equal(S.authorize({...teacher,serverVerified:false},S.state.resources[0],'CHECK').allowed,false));
t('cross org rejected',()=>assert.equal(S.authorize({...teacher,organizationId:'other'},S.state.resources[0],'CHECK').allowed,false));
const tutorResource=S.resource({id:'tutor-r',version:'1',type:'TUTORING_RESOURCE',ownerId:'tutor-1',organizationId:'school-1',subject:'Math',grade:'Grade 10',language:'en'});
const tutor={id:'tutor-1',role:'VERIFIED_TUTOR',serverVerified:true,verifiedTutor:true,organizationId:'school-1',approvedSubjects:['Math'],approvedGrades:['Grade 10']};
t('tutor own resource',()=>assert.equal(S.authorize(tutor,tutorResource,'CHECK').allowed,true));
t('unverified tutor denied',()=>assert.equal(S.authorize({...tutor,verifiedTutor:false},tutorResource,'CHECK').allowed,false));
t('tutor subject scope',()=>assert.equal(S.authorize({...tutor,approvedSubjects:['Biology']},tutorResource,'CHECK').allowed,false));
t('tutor grade scope',()=>assert.equal(S.authorize({...tutor,approvedGrades:['Grade 9']},tutorResource,'CHECK').allowed,false));
t('tutor publish denied',()=>assert.equal(S.authorize(tutor,tutorResource,'PUBLISH_OFFICIAL').allowed,false));
t('tutor exception denied',()=>assert.equal(S.authorize(tutor,tutorResource,'APPROVE_EXCEPTION').allowed,false));
const make=(id,type,content={},language='en')=>S.resource({id,version:'1',type,ownerId:'teacher-1',organizationId:'school-1',language,content});
const image=make('img','IMAGE',{}),complex=make('chart','CHART',{alt:'Chart'}),video=make('vid','VIDEO',{captions:true,automaticCaptions:true,captionsReviewed:false}),audio=make('aud','AUDIO_RECORDING',{}),button=make('btn','CUSTOM_BUTTON',{label:'Open'}),form=make('form','FORM',{unlabelledFields:1}),table=make('table','TABLE',{}),large=make('file','FILE_DOWNLOAD',{sizeBytes:90177536,downloadable:true}),instructions=make('ins','INSTRUCTION_SET',{text:'Click here and open it and press the button and complete the above.'}),math=make('math','MATHEMATICAL_CONTENT',{}),code=make('code','CODE_CONTENT',{});
const has=(r,c)=>S.scanOne(r).some(i=>i.code===c);
t('missing alt',()=>assert.ok(has(image,'IMAGE_MISSING_ALT')));
t('missing long description',()=>assert.ok(has(complex,'COMPLEX_IMAGE_MISSING_LONG_DESCRIPTION')));
t('video transcript',()=>assert.ok(has(video,'VIDEO_MISSING_TRANSCRIPT')));
t('automatic captions review',()=>assert.ok(has(video,'VIDEO_CAPTIONS_UNREVIEWED')));
t('recording transcript',()=>assert.ok(has(audio,'RECORDING_MISSING_TRANSCRIPT')));
t('control name',()=>assert.ok(has(button,'CONTROL_MISSING_ACCESSIBLE_NAME')));
t('ambiguous label',()=>assert.ok(has(button,'CONTROL_LABEL_AMBIGUOUS')));
t('form label',()=>assert.ok(has(form,'FORM_FIELD_MISSING_LABEL')));
t('table headers',()=>assert.ok(has(table,'TABLE_HEADERS_MISSING')));
t('large file',()=>assert.ok(has(large,'FILE_UNUSUALLY_LARGE')));
t('low data alternative',()=>assert.ok(has(large,'FILE_MISSING_LOW_DATA_ALTERNATIVE')));
t('vague instructions',()=>assert.ok(has(instructions,'INSTRUCTIONS_VAGUE_CONTROL_NAME')));
t('multiple actions',()=>assert.ok(has(instructions,'INSTRUCTIONS_MULTIPLE_ACTIONS')));
t('semantic math',()=>assert.ok(has(math,'MATH_MISSING_SEMANTIC_ALTERNATIVE')));
t('keyboard trap risk',()=>assert.ok(has(code,'CODE_KEYBOARD_TRAP_RISK')));
t('language metadata',()=>assert.ok(has(make('lang','DOCUMENT',{},null),'LANGUAGE_METADATA_MISSING')));
t('human review notice',()=>assert.ok(has(image,'HUMAN_REVIEW_REQUIRED')));
S.state.resources.push(image,instructions);
const run=S.runCheck([image,instructions],teacher);
t('batch multiple resources',()=>assert.equal(run.job.completed,2));
t('versions recorded',()=>assert.equal(run.job.resourceVersions.length,2));
t('review required',()=>assert.equal(run.job.status,'REVIEW_REQUIRED'));
t('limitation exact',()=>assert.equal(run.notice,S.AUTOMATED_ACCESSIBILITY_CHECK_LIMITATION_NOTICE));
const ids=run.issues.filter(i=>['IMAGE_MISSING_ALT','INSTRUCTIONS_VAGUE_CONTROL_NAME'].includes(i.code)).map(i=>i.id),drafts=S.generateDrafts(ids,teacher);
t('batch drafts',()=>assert.ok(drafts.length>=2));
t('drafts unpublished',()=>assert.ok(drafts.every(d=>d.published===false)));
t('source version preserved',()=>assert.ok(drafts.every(d=>d.sourceVersion==='1')));
t('academic preservation',()=>assert.ok(drafts.every(d=>d.preservationFields.includes('correctAnswer')&&d.preservationFields.includes('formulas'))));
t('draft review',()=>assert.equal(S.reviewDraft(drafts[0].id,'APPROVE',teacher).status,'APPROVED'));
t('auto publish decision rejected',()=>assert.throws(()=>S.reviewDraft(drafts[0].id,'AUTO_PUBLISH',teacher),/Unknown/));
t('critical readiness',()=>assert.equal(S.readiness([form],S.scanOne(form)),'CRITICAL_ISSUES_OPEN'));
t('publish blocked',()=>assert.throws(()=>S.publish(image,teacher),/review|resolution/i));
const grant={active:true,recipientUserId:'teacher-1',subjectUserId:'learner-1',expiresAt:new Date(Date.now()+60000).toISOString()};
const preview=S.learnerPreview(grant,{textSize:'LARGE',captionsPreferred:true,diagnosis:'x',accommodationDocument:'x'},teacher);
t('preview read only',()=>assert.equal(preview.readOnly,true));
t('preview no impersonation',()=>assert.equal(preview.impersonating,false));
t('functional preview',()=>assert.equal(preview.fields.textSize,'LARGE'));
t('diagnosis excluded',()=>assert.ok(!('diagnosis'in preview.fields)));
t('document excluded',()=>assert.ok(!('accommodationDocument'in preview.fields)));
t('expired preview denied',()=>assert.throws(()=>S.learnerPreview({...grant,expiresAt:new Date(0).toISOString()},{},teacher),/grant/));
t('eight preview fields',()=>assert.equal(S.LearnerPreviewFields.length,8));
S.invalidate('img','2','new');
t('issues outdated',()=>assert.ok(S.state.issues.filter(i=>i.resourceId==='img').every(i=>i.status==='OUTDATED')));
t('drafts outdated',()=>assert.ok(S.state.drafts.filter(d=>d.resourceId==='img').every(d=>d.status==='OUTDATED')));
t('reuses print',()=>assert.equal(S.integrations.printable,'PrintableReviewPlans'));
t('reuses audio',()=>assert.equal(S.integrations.audioSummary,'AudioLessonSummaries'));
t('no false score',()=>assert.ok(S.AccessibilityPublicationReadiness.every(x=>!x.includes('100')&&!x.includes('COMPLIANT'))));
console.log(`accessible-resource-studio: ${n}/${n} assertions passed`);
