'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const src=read('learning-pathway-module-flow.js'),css=read('learning-pathway-module-flow.css'),html=read('index (2).html'),lab=read('ai-literacy-lab.js');
let passed=0;
const test=(name,fn)=>{fn();passed++;console.log(`✓ ${name}`)};
test('preserves existing module records',()=>assert.ok(lab.includes('AILiteracyPathways:PATHWAYS')));
test('intercepts the existing module control',()=>assert.ok(src.includes("closest?.('[data-ai-module]')")));
test('stops the dead-end legacy handler',()=>assert.ok(src.includes('stopImmediatePropagation')));
test('renders a selected module panel',()=>assert.ok(src.includes('aiSelectedModulePanel')));
test('shows start and continue module actions',()=>assert.ok(src.includes("'Continue Module':'Start Module'")));
test('starts through the existing session API',()=>assert.ok(src.includes('startAILiteracyModule')));
test('retains a module session for continuation',()=>assert.ok(src.includes('const sessions=new Map()')));
test('opens a focused module workspace',()=>assert.ok(src.includes('ai-module-workspace')&&src.includes('Student Attempt')));
test('uses canonical Learn pathway hashes',()=>assert.ok(src.includes('#learn/pathways/')));
test('supports return to pathway modules',()=>assert.ok(src.includes('data-back-to-pathway')));
test('loads module flow after the existing lab',()=>assert.ok(html.indexOf('learning-pathway-module-flow.js')>html.indexOf('ai-literacy-lab.js')));
test('loads dedicated styles',()=>assert.ok(html.includes('learning-pathway-module-flow.css')));
test('responsive module selection layout',()=>assert.ok(css.includes('@media(max-width:42rem)')));
test('accessible focus and forced colors',()=>assert.ok(css.includes(':focus-visible')&&css.includes('forced-colors')));
console.log(`${passed} module-flow assertions passed`);
