const fs=require('fs'),path=require('path'),assert=require('assert'),vm=require('vm');const base=fs.readFileSync(path.join(__dirname,'session-attendance.test.js'),'utf8').split('const tests=[]')[0];eval(base+`;globalThis.__mvpFx={fixture,account,db,window,context,setAccount:a=>currentAccount=a}`);const F=globalThis.__mvpFx;for(const f of ['post-session-learning.js','community-service.js','help-credits.js','service-documents.js','integrity-review.js','safety-safeguarding.js','academic-integrity.js','community-impact.js','role-dashboards.js','mvp-stage.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),F.context);const P=F.window.PeerTutoring,M=F.window.MvpStage;const tests=[];function test(n,f){tests.push([n,f])}function throws(f,r){assert.throws(f,r)}
test('default target resolves to stage four when all stages complete',()=>assert.equal(M.getCurrentMvpStage(),4));
test('registry includes every suggested MVP feature',()=>['REGISTRATION','LEARNER_ROLE','TUTOR_ROLE','TUTOR_APPLICATION','MANUAL_TUTOR_VERIFICATION','TUTORING_REQUESTS','BASIC_MATCHING','BOOKING','IN_PLATFORM_MESSAGING','ATTENDANCE','POST_SESSION_CONFIRMATION','SERVICE_HOUR_REVIEW','SERVICE_HOUR_REPORTS','LEARNER_DASHBOARD','TUTOR_DASHBOARD','AI_MATCHING','AI_SESSION_PLANS','AI_SESSION_SUMMARIES','HELP_CREDITS','FRAUD_INDICATORS','ORGANIZATION_DASHBOARDS'].forEach(k=>assert(M.FEATURE[k])));
test('stage one features map only to stage one',()=>['REGISTRATION','LEARNER_ROLE','TUTOR_ROLE','TUTOR_APPLICATION','MANUAL_TUTOR_VERIFICATION','TUTORING_REQUESTS'].forEach(k=>assert.equal(M.MINIMUM_STAGE[k],1)));
test('stage two features map to stage two',()=>['BASIC_MATCHING','BOOKING','IN_PLATFORM_MESSAGING','ATTENDANCE','POST_SESSION_CONFIRMATION'].forEach(k=>assert.equal(M.MINIMUM_STAGE[k],2)));
test('stage three features map to stage three',()=>['SERVICE_HOUR_REVIEW','SERVICE_HOUR_REPORTS','LEARNER_DASHBOARD','TUTOR_DASHBOARD'].forEach(k=>assert.equal(M.MINIMUM_STAGE[k],3)));
test('stage four automation maps to stage four',()=>['AI_MATCHING','AI_SESSION_PLANS','AI_SESSION_SUMMARIES','HELP_CREDITS','FRAUD_INDICATORS','ORGANIZATION_DASHBOARDS'].forEach(k=>assert.equal(M.MINIMUM_STAGE[k],4)));
test('unknown feature rejected',()=>throws(()=>M.isFeatureEnabled('FAKE_LATER_FEATURE'),/Unknown/));
test('all current target features enabled',()=>Object.values(M.FEATURE).forEach(f=>assert(M.isFeatureEnabled(f))));
test('stage one feature list excludes matching',()=>{const f=M.getFeaturesForMvpStage(1);assert(f.includes('TUTOR_APPLICATION'));assert(!f.includes('BASIC_MATCHING'))});
test('stage two list excludes service review',()=>{const f=M.getFeaturesForMvpStage(2);assert(f.includes('ATTENDANCE'));assert(!f.includes('SERVICE_HOUR_REVIEW'))});
test('stage three list excludes AI and credits',()=>{const f=M.getFeaturesForMvpStage(3);assert(f.includes('SERVICE_HOUR_REPORTS'));assert(!f.includes('AI_MATCHING')&&!f.includes('HELP_CREDITS'))});
test('invalid stage rejected',()=>throws(()=>M.getFeaturesForMvpStage(5),/1 through 4/));
test('stage coverage marks all four complete',()=>M.getStageCoverage().forEach(s=>assert(s.complete)));
test('earliest incomplete is null',()=>assert.strictEqual(M._test.earliestIncomplete(),null));
test('acceptance gate passes only from real module coverage',()=>{const g=M.getAcceptanceGate();assert(g.passed);assert.deepEqual(g.failedStages,[]);assert(g.laterStagePlaceholdersDoNotCount)});
test('manual tutor approval remains authoritative',()=>assert.equal(M.MANUAL_AUTHORITY.tutorApplicationApproval,'AUTHORIZED_HUMAN_REVIEWER'));
test('manual subject scope approval remains authoritative',()=>assert.equal(M.MANUAL_AUTHORITY.tutorSubjectApproval,'AUTHORIZED_HUMAN_REVIEWER'));
test('manual service approval remains authoritative',()=>assert.equal(M.MANUAL_AUTHORITY.communityServiceApproval,'AUTHORIZED_ORGANIZATION_VERIFIER'));
test('AI cannot approve reject or suspend',()=>{assert(!M.MANUAL_AUTHORITY.aiMayApprove&&!M.MANUAL_AUTHORITY.aiMayReject&&!M.MANUAL_AUTHORITY.aiMaySuspend)});
test('email verification safety baseline preserved',()=>{assert(M.SAFETY_BASELINE.emailVerificationBeforeBooking);assert(M.SAFETY_BASELINE.emailVerificationBeforeTutoring)});
test('guardian consent safety baseline preserved',()=>{assert(M.SAFETY_BASELINE.guardianConsentForRestrictedMinorActivity);assert(M.SAFETY_BASELINE.learnerCannotApproveOwnConsent)});
test('private home remains prohibited',()=>assert.strictEqual(M.SAFETY_BASELINE.privateHomeTutoring,false));
test('academic integrity baseline preserved',()=>assert(M.SAFETY_BASELINE.activeAssessmentAnswersProhibited));
test('feature guard accepts current-stage operation',()=>assert(M.guardOperation('openOrganizationDashboard')));
test('unknown protected operation rejected',()=>throws(()=>M.guardOperation('selfApproveTutor'),/Unknown/));
test('role helper recognizes assigned learner role',()=>{const u=F.account('role-learner');assert(M.hasRole(u,P.ROLES.LEARNER));assert(M.requireRole(u,P.ROLES.LEARNER))});
test('role helper blocks missing internal role',()=>{const u=F.account('no-admin');throws(()=>M.requireRole(u,P.ROLES.PLATFORM_ADMIN),/required/)});
test('any-role helper is centralized',()=>{const u=F.account('any-role');assert(M.requireAnyRole(u,[P.ROLES.LEARNER,P.ROLES.PEER_TUTOR]))});
test('ordinary user cannot assign internal role',()=>{const u=F.account('target-internal'),actor=F.account('ordinary');throws(()=>M.assignInternalRole(u.id,P.ROLES.ORGANIZATION_VERIFIER,actor),/administrator/)});
test('admin internal-role assignment is audited',()=>{const u=F.account('internal-target'),ad=F.account('internal-admin',[P.ROLES.PLATFORM_ADMIN]),r=M.assignInternalRole(u.id,P.ROLES.ORGANIZATION_VERIFIER,ad);assert(!r.selfAssigned);assert(F.db.peerTutoringAuditLogs.some(a=>a.action==='MVP_INTERNAL_ROLE_ASSIGNED'))});
test('self-selection cannot request privileged roles',()=>{const u=F.account('self-priv');throws(()=>M.requestPublicRole(P.ROLES.PLATFORM_ADMIN,u),/Privileged/);throws(()=>M.requestPublicRole(P.ROLES.ORGANIZATION_VERIFIER,u),/Privileged/)});
test('stage report distinguishes unsafe prototype limits',()=>{const r=M.getMvpStageReport();assert(r.coverage.some(s=>s.unsafeOrUntested.length));assert(!r.backendEnforcementAvailable)});
test('advanced roadmap does not count as MVP completion',()=>{const r=M.getMvpStageReport();assert(r.advancedRoadmapFeaturesExcludedFromMvpCompletion.includes('Recognition badges'));assert(r.advancedRoadmapFeaturesExcludedFromMvpCompletion.includes('Public QR verification'))});
test('report identifies independently deployable target',()=>assert(M.getMvpStageReport().independentlyDeployable));
test('stage report preserves manual authority',()=>assert.strictEqual(M.getMvpStageReport().acceptanceGate.manualApprovalAuthoritative,true));
let passed=0;for(const [n,f] of tests){try{f();passed++;console.log(`PASS ${n}`)}catch(e){console.error(`FAIL ${n}\n${e.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
