(function(root){'use strict';
const f=Object.freeze;
const MVPStageStatus=f(['NOT_STARTED','IN_PROGRESS','READY_FOR_REVIEW','COMPLETE','BLOCKED','PARTIALLY_COMPLETE']);
const CapabilityState=f(['DISABLED','INTERNAL_TESTING','LIMITED_ROLLOUT','ENABLED']);
const stages=f([
{id:1,code:'BASIC_ACCESSIBILITY',name:'Basic Accessibility',capability:'accessibility.basic',modules:['AccessibilityBaseline','KeyboardAccessibility','VisualDisplay','AccessibilityToolbar'],features:['Keyboard navigation','Visible focus','Text size','Line spacing','High contrast','Reduced motion','Form labels','Screen-reader structure'],testFiles:['accessibility-baseline.test.js','keyboard-accessibility.test.js','visual-display.test.js']},
{id:2,code:'ACCESSIBLE_CONTENT',name:'Accessible Content',capability:'accessibility.content',modules:['TextToSpeech','SpeechToText','LiveCaptions','PlainLanguage','ExplanationLevels'],features:['Text-to-Speech','Speech-to-Text','Captions','Transcripts','Plain language','Reading levels'],testFiles:['text-to-speech.test.js','speech-to-text.test.js','live-captions.test.js','plain-language.test.js','explanation-levels.test.js']},
{id:3,code:'LANGUAGE_BRIDGE',name:'Language Bridge',capability:'accessibility.languageBridge',modules:['AccessibilityLanguage','LanguageBridge','AcademicVocabulary','MultilingualAI'],features:['Preferred languages','Bilingual AI','Vocabulary translation','Personal glossary','English terminology preservation'],testFiles:['accessibility-language.test.js','language-bridge.test.js','academic-vocabulary.test.js','multilingual-ai.test.js']},
{id:4,code:'DIGITAL_DIVIDE',name:'Digital-Divide Support',capability:'accessibility.digitalDivide',modules:['LowBandwidth','TextOnlyStudyRooms','OfflineStudyPackages','PrintableReviewPlans','AudioLessonSummaries'],features:['Low-Bandwidth Mode','Text-Only Study Rooms','Offline packages','Printable plans','Audio summaries','Offline recovery'],testFiles:['low-bandwidth.test.js','text-only-study-rooms.test.js','offline-study-packages.test.js','printable-review-plans.test.js','audio-lesson-summaries.test.js']},
{id:5,code:'QUALITY_ADMIN',name:'Quality and Administration',capability:'accessibility.qualityAndAdmin',modules:['AccessibleResourceStudio','AccessibilityQualityChecks','StudentPrivacy'],features:['Accessibility checker','Teacher preview','Privacy controls','Privacy-safe analytics','Barrier feedback'],testFiles:['accessible-resource-studio.test.js','accessibility-quality-checks.test.js','student-privacy.test.js']}
]);
const essentialRoutes=f([
['Sign in','Public user','Authenticate','Stage 1'],['Account creation','New student','Create account','Stage 1'],['Password recovery','Returning student','Recover access','Stage 1'],['Dashboard','Student','Open primary study tools','Stage 1'],['Accessibility & Language','Student','Change functional preferences','Stage 1'],['AI Coach','Student','Read and ask explicitly','Stage 2'],['Notes / lesson content','Student','Read learning content','Stage 2'],['Quiz','Student','Complete activity','Stage 1'],['Study Room','Student','Join and participate without forced media','Stage 4'],['Assignment upload','Student','Choose and submit a file explicitly','Stage 1'],['Offline materials','Student','Review and download explicitly','Stage 4'],['My Privacy and Data','Student','Manage private choices','Stage 5'],['How It Works','All users','Get accessible help','Stage 1'],['Accessible Resource Studio','Authorized creator','Review learning resources','Stage 5']
]);
const preferenceDefaults=f({schemaVersion:'1.0.0',textSize:'DEFAULT',lineSpacing:'DEFAULT',contrast:'DEFAULT',reducedMotion:'SYSTEM',dyslexiaFriendly:false,readingRuler:false,preferredLanguage:'en',bridgeLanguage:null,explanationLevel:'STANDARD',captionsPreferred:false,transcriptSaving:'ASK_EACH_TIME',speechRate:1,lowBandwidthMode:'AUTO',studyRoomMode:'TEXT_ONLY',tutorSharing:'SHARE_NOTHING'});
const forbiddenPreferenceFields=f(['diagnosis','disabilityType','medicalInformation','englishProficiency','immigrationStatus','academicAbility','financialStatus','homeCircumstances']);
const analyticsAllowlist=f(['accessibility_settings_opened','text_size_changed','contrast_mode_changed','reduced_motion_changed','tts_started_by_user','stt_permission_notice_opened','captions_enabled','transcript_preference_changed','language_bridge_opened','low_bandwidth_mode_changed','text_only_room_selected','offline_package_requested','print_preview_opened','privacy_centre_opened','accessibility_checker_opened','accessibility_barrier_report_drafted']);
const analyticsForbidden=f(['diagnosis','disability','transcriptText','voiceContent','languageHistory','simplificationContent','translationContent','privateNote','learnerId','teacherRanking','tutorRanking','abilityScore','dependencyScore']);
const state={capabilities:{'accessibility.basic':'INTERNAL_TESTING','accessibility.content':'INTERNAL_TESTING','accessibility.languageBridge':'INTERNAL_TESTING','accessibility.digitalDivide':'INTERNAL_TESTING','accessibility.qualityAndAdmin':'INTERNAL_TESTING'},evidence:[],events:[],feedbackDrafts:[]};let seq=0;
const known=(v,list,label)=>{if(!list.includes(v))throw new Error(`Unknown ${label}.`);return v};
function capability(code){const s=state.capabilities[code];if(!s)throw new Error('Unknown accessibility capability.');return s}
function setCapability(code,value,actor={}){if(!(code in state.capabilities))throw new Error('Unknown accessibility capability.');known(value,CapabilityState,'capability state');if(actor.serverVerified!==true||actor.role!=='ADMINISTRATOR')throw new Error('Trusted administrator configuration is required.');state.capabilities[code]=value;return {code,value,serverEnforcementRequired:true}}
function preference(input={}){for(const key of forbiddenPreferenceFields)if(key in input)throw new Error(`Diagnostic or inferred field is prohibited: ${key}.`);return {...preferenceDefaults,...Object.fromEntries(Object.entries(input).filter(([k])=>k in preferenceDefaults))}}
function addEvidence(input){const stage=stages.find(s=>s.id===input.stageId);if(!stage)throw new Error('Unknown MVP stage.');if(!stage.testFiles.includes(input.testFile))throw new Error('Test file is not registered for this stage.');if(input.passed!==true)throw new Error('Only successfully executed test evidence can be recorded as passed.');const row={id:`mvp-evidence-${++seq}`,stageId:stage.id,testFile:input.testFile,assertions:Number(input.assertions)||0,passed:true,executedAt:input.executedAt||new Date().toISOString(),source:'EXECUTED_AUTOMATED_TEST',browser:null,assistiveTechnology:null};state.evidence.push(row);return {...row}}
function stageStatus(stageId){const stage=stages.find(s=>s.id===stageId);if(!stage)throw new Error('Unknown MVP stage.');const evidence=state.evidence.filter(e=>e.stageId===stageId&&e.passed),allFiles=stage.testFiles.every(file=>evidence.some(e=>e.testFile===file)),prior=stageId===1?true:[...Array(stageId-1)].every((_,i)=>['READY_FOR_REVIEW','COMPLETE','PARTIALLY_COMPLETE'].includes(stageStatus(i+1).status)),modules=stage.modules.map(name=>({name,available:Boolean(root[name])})),missingModules=modules.filter(m=>!m.available).map(m=>m.name),limitations=[];if(!allFiles)limitations.push('Registered stage test evidence is incomplete in this runtime status record.');if(missingModules.length)limitations.push(`Unavailable module globals: ${missingModules.join(', ')}.`);limitations.push('Required browser, assistive-technology, privacy, security and complete journey evidence is not recorded.');const status=!prior?'BLOCKED':allFiles&&!missingModules.length?'READY_FOR_REVIEW':'PARTIALLY_COMPLETE';return {stageId,name:stage.name,status,capability:stage.capability,capabilityState:capability(stage.capability),features:[...stage.features],testEvidence:evidence,registeredTests:[...stage.testFiles],missingModules,limitations,canMarkComplete:false,completeReason:'Migrations, full journeys, privacy/security and manual browser/AT review are unavailable.'}}
function gate(stageId){const current=stageStatus(stageId),prior=stageId===1?[]:[...Array(stageId-1)].map((_,i)=>stageStatus(i+1));return {stageId,mayContinueIndependentWork:prior.every(s=>s.status!=='NOT_STARTED'&&s.status!=='BLOCKED'),mayEnableBroadRollout:prior.every(s=>s.status==='COMPLETE')&&current.status==='COMPLETE',mayEnablePublicationControls:stageId===5&&prior.every(s=>s.status==='COMPLETE'),browserCannotOverride:true,reasons:[...prior.filter(s=>s.status!=='COMPLETE').map(s=>`Stage ${s.stageId} is ${s.status}.`),...(current.status!=='COMPLETE'?[`Stage ${stageId} is ${current.status}.`]:[])]}}
function recordEvent(name,metadata={}){if(!analyticsAllowlist.includes(name))throw new Error('Analytics event is not allowlisted.');for(const key of Object.keys(metadata))if(analyticsForbidden.some(x=>key.toLowerCase().includes(x.toLowerCase())))throw new Error('Sensitive or scoring analytics metadata is prohibited.');const safe=Object.fromEntries(Object.entries(metadata).filter(([k,v])=>['route','control','mode','result','stage'].includes(k)&&['string','number','boolean'].includes(typeof v)));const row={name,metadata:safe,occurredAt:new Date().toISOString(),aggregateOnly:true,studentScoring:false,publicProfile:false};state.events.push(row);return {...row,metadata:{...safe}}}
function barrierReportDraft(input={}){const categories=['KEYBOARD_PROBLEM','SCREEN_READER_PROBLEM','CAPTION_PROBLEM','TRANSCRIPT_PROBLEM','VISUAL_DISPLAY_PROBLEM','LANGUAGE_PROBLEM','LOW_BANDWIDTH_PROBLEM','OTHER_ACCESSIBILITY_BARRIER'];known(input.category,categories,'barrier category');const row={id:`barrier-draft-${++seq}`,category:input.category,route:String(input.route||'').slice(0,120),description:String(input.description||'').slice(0,1000),status:'DRAFT',submitted:false,notice:'This local draft has not been submitted. A production feedback API is required.',diagnosisRequested:false,retaliationAllowed:false,createdAt:new Date().toISOString()};state.feedbackDrafts.push(row);recordEvent('accessibility_barrier_report_drafted',{route:row.route,result:'draft'});return {...row}}
function report(){return {purpose:'Stable sequential accessibility MVP',architecture:'Existing browser modules coordinated without duplication',capabilities:{...state.capabilities},stages:stages.map(s=>stageStatus(s.id)),gates:stages.map(s=>gate(s.id)),essentialRoutes:essentialRoutes.map(r=>({route:r[0],primaryUser:r[1],essentialTask:r[2],stage:r[3]})),preferences:{...preferenceDefaults},privacy:{forbiddenPreferenceFields:[...forbiddenPreferenceFields],analyticsAllowlist:[...analyticsAllowlist],analyticsForbidden:[...analyticsForbidden],publicProfileExcluded:true,noScoring:true},serverEnforcementAvailable:false,manualEvidenceAvailable:false}}
function render(){if(typeof document==='undefined')return;const el=document.querySelector('#accessibilityMvpContent');if(!el)return;const r=report();el.innerHTML=`<section class="a11y-mvp-hero card"><span class="kicker">SEQUENTIAL · EVIDENCE-BASED · PRIVATE</span><h2>Accessibility MVP</h2><p>The existing accessibility systems are organized into five dependency stages. Later-stage code does not make an earlier gate complete.</p><div class="a11y-mvp-notice" role="note"><b>Honest status:</b> No stage is marked complete without migrations, essential journeys, privacy/security checks and manual browser/assistive-technology evidence.</div></section><div class="a11y-mvp-grid">${r.stages.map(s=>`<article class="card"><span class="tutoring-status">${s.status}</span><h3>Stage ${s.stageId}: ${s.name}</h3><p>${s.features.join(' · ')}</p><dl><dt>Capability</dt><dd>${s.capabilityState}</dd><dt>Registered tests</dt><dd>${s.registeredTests.length}</dd><dt>Runtime evidence</dt><dd>${s.testEvidence.length}</dd><dt>Broad rollout</dt><dd>${r.gates[s.stageId-1].mayEnableBroadRollout?'Eligible':'Not eligible'}</dd></dl><details><summary>Known limitations</summary><ul>${s.limitations.map(x=>`<li>${x}</li>`).join('')}</ul></details></article>`).join('')}</div><article class="card"><h2>Essential route set</h2><div class="a11y-mvp-table"><table><thead><tr><th>Route</th><th>Primary user</th><th>Essential task</th><th>Stage</th></tr></thead><tbody>${r.essentialRoutes.map(x=>`<tr><td>${x.route}</td><td>${x.primaryUser}</td><td>${x.essentialTask}</td><td>${x.stage}</td></tr>`).join('')}</tbody></table></div></article>`}
const api={MVPStageStatus,CapabilityState,stages,essentialRoutes,preferenceDefaults,forbiddenPreferenceFields,analyticsAllowlist,analyticsForbidden,state,capability,setCapability,preference,addEvidence,stageStatus,gate,recordEvent,barrierReportDraft,report,render,_test:{known}};root.AccessibilityMVP=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;if(typeof document!=='undefined'){if(typeof viewNames==='object')viewNames.accessibilityMvp=['PLATFORM','Accessibility MVP'];document.addEventListener('click',e=>{if(e.target.closest('[data-view="accessibilityMvp"]'))setTimeout(render)})}
})(typeof window!=='undefined'?window:globalThis);
