(function(root){
'use strict';
const A=root.AccessibilityLanguage,BOOT=root.__studySparkToolbarBoot||{KEY:'studyspark.accessibilityToolbar.v1',migrate:value=>value,valid:value=>value,apply:value=>value},KEY=BOOT.KEY;
const DYSLEXIA_FRIENDLY_DISPLAY_NOTICE='These reading options may make text more comfortable to use. Different students prefer different combinations. No diagnosis is required, and the settings do not change the academic content of your lessons.';
const FIELDS=['dyslexiaPresetStatus','wordSpacingPreference','accessibleFontPreference','reduceItalicText','disableDecorativeFonts','reduceVisualClutter','currentReadingHighlightMode','readingRulerEnabled','readingRulerStyle','readingRulerSize','readingRulerTrackingMode'];
const SHARED_FIELDS=['letterSpacing','lineSpacing','contentWidth','readingAlignment','paragraphSpacing'];
const DEFAULTS=Object.freeze({dyslexiaPresetStatus:'NOT_APPLIED',wordSpacingPreference:'DEFAULT',accessibleFontPreference:'SYSTEM',reduceItalicText:false,disableDecorativeFonts:false,reduceVisualClutter:false,currentReadingHighlightMode:'OFF',readingRulerEnabled:false,readingRulerStyle:'HIGHLIGHT_BAND',readingRulerSize:'MEDIUM',readingRulerTrackingMode:'MANUAL'});
const PRESET=Object.freeze({letterSpacing:'RELAXED',wordSpacingPreference:'RELAXED',lineSpacing:'EXPANDED',contentWidth:'SHORT',readingAlignment:'READING_DIRECTION_START',paragraphSpacing:'EXPANDED',reduceItalicText:true,disableDecorativeFonts:true,reduceVisualClutter:true,dyslexiaPresetStatus:'SUGGESTED_PRESET'});
const ENUMS=Object.freeze({dyslexiaPresetStatus:['NOT_APPLIED','SUGGESTED_PRESET','CUSTOMIZED'],wordSpacingPreference:['SYSTEM','DEFAULT','RELAXED','EXPANDED'],accessibleFontPreference:['SYSTEM','STUDYSPARK_DEFAULT','HUMANIST_SANS','READABLE_SERIF'],currentReadingHighlightMode:['OFF','CURRENT_PARAGRAPH','CURRENT_LINE'],readingRulerStyle:['HIGHLIGHT_BAND','FOCUS_STRIP','DIM_SURROUNDING_CONTENT'],readingRulerSize:['SMALL','MEDIUM','LARGE'],readingRulerTrackingMode:['MANUAL','FOLLOW_READING_FOCUS','FOLLOW_TEXT_TO_SPEECH'],letterSpacing:['SYSTEM','DEFAULT','RELAXED','EXPANDED'],lineSpacing:['SYSTEM','DEFAULT','RELAXED','EXPANDED','EXTRA_EXPANDED'],contentWidth:['SYSTEM','SHORT','COMFORTABLE','WIDE','FULL'],readingAlignment:['SYSTEM','READING_DIRECTION_START'],paragraphSpacing:['SYSTEM','DEFAULT','RELAXED','EXPANDED']});
const FONT_REGISTRY=Object.freeze({SYSTEM:{displayName:'Use device system font',licensed:'SYSTEM_PROVIDED',available:true,supportedScripts:['Latin','Arabic','Hebrew','CJK','Devanagari'],fontFamilyToken:'system-ui, sans-serif',mathCompatible:false,codeCompatible:false,testedZoomRange:'Automated source only',knownLimitations:'Exact glyphs vary by device.'},STUDYSPARK_DEFAULT:{displayName:'Use StudySpark default',licensed:'GOOGLE_FONTS_PROJECT_ASSET',available:true,supportedScripts:['Latin'],fontFamilyToken:'DM Sans, system-ui, sans-serif',mathCompatible:false,codeCompatible:false,testedZoomRange:'Automated source only',knownLimitations:'Falls back by language when required glyphs are unavailable.'},HUMANIST_SANS:{displayName:'Humanist sans serif',licensed:'SYSTEM_PROVIDED',available:true,supportedScripts:['Latin'],fontFamilyToken:'Trebuchet MS, Segoe UI, system-ui, sans-serif',mathCompatible:false,codeCompatible:false,testedZoomRange:'Automated source only',knownLimitations:'Uses system-provided fonts and language fallback.'},READABLE_SERIF:{displayName:'Readable serif',licensed:'SYSTEM_PROVIDED',available:true,supportedScripts:['Latin'],fontFamilyToken:'Georgia, Times New Roman, serif',mathCompatible:false,codeCompatible:false,testedZoomRange:'Automated source only',knownLimitations:'Uses system-provided fonts and language fallback.'}});
const state={anchorIndex:0,rulerOffset:0,controllerCollapsed:false,pendingAccount:false,undo:null,raf:0};
function migrate(raw={}){const next={...DEFAULTS,...raw};if(raw.dyslexiaFriendlyDisplayEnabled&&!raw.dyslexiaPresetStatus)Object.assign(next,PRESET,{readingRulerEnabled:false,currentReadingHighlightMode:'OFF',accessibleFontPreference:raw.accessibleFontPreference||'SYSTEM'});return next}
function validate(raw={}){const merged=migrate(raw);for(const [key,values]of Object.entries(ENUMS))if(key in raw&&!values.includes(raw[key]))throw new Error(`Invalid ${key}.`);for(const key of ['reduceItalicText','disableDecorativeFonts','reduceVisualClutter','readingRulerEnabled'])if(key in raw&&typeof raw[key]!=='boolean')throw new Error(`Invalid ${key}.`);const safe=BOOT.valid(merged),out={...DEFAULTS};for(const key of [...FIELDS,...SHARED_FIELDS])if(key in safe)out[key]=safe[key];return out}
function read(){try{return validate(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {...DEFAULTS}}}
function ownerView(p){return Object.fromEntries(FIELDS.map(key=>[key,p[key]]))}
function persist(p){let raw={};try{raw=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}const next={...raw,...p,schemaVersion:3,updatedAt:new Date().toISOString()};try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}return next}
function actor(){return typeof user==='function'?user():null}
function registered(a=actor()){return Boolean(a?.id&&typeof db!=='undefined'&&Object.values(db.users||{}).some(item=>item.id===a.id))}
function syncAccount(patch){if(!registered()||!A)return;if(typeof navigator!=='undefined'&&!navigator.onLine){state.pendingAccount=true;return}try{const profile=A.getMyAccessibilityLanguageProfile();A.updateAccessibilityLanguageProfile(patch,profile?.version??null);state.pendingAccount=false}catch{state.pendingAccount=true}}
function apply(p){const next=validate(p);BOOT.apply(next);const html=document.documentElement,font=FONT_REGISTRY[next.accessibleFontPreference]||FONT_REGISTRY.SYSTEM;html.style.setProperty('--studyspark-reading-font',font.fontFamilyToken);html.dataset.rulerStyle=next.readingRulerStyle;html.dataset.rulerSize=next.readingRulerSize;renderAid(next);return next}
function update(patch,{customize=true,account=true}={}){const current=read(),next=validate({...current,...patch,...(customize&&current.dyslexiaPresetStatus==='SUGGESTED_PRESET'?{dyslexiaPresetStatus:'CUSTOMIZED'}:{})});persist(next);if(typeof document!=='undefined')apply(next);if(account)syncAccount({...ownerView(next),...Object.fromEntries(SHARED_FIELDS.filter(k=>k in patch).map(k=>[k,next[k]]))});syncControls(next);announce('✓ Reading display settings saved');return next}
function applySuggestedPreset(){state.undo=read();const next=update({...PRESET,readingRulerEnabled:read().readingRulerEnabled,currentReadingHighlightMode:read().currentReadingHighlightMode,accessibleFontPreference:read().accessibleFontPreference},{customize:false});announce(DYSLEXIA_FRIENDLY_DISPLAY_NOTICE);return next}
function undoPreset(){if(!state.undo)return read();const previous=state.undo;state.undo=null;return update(previous,{customize:false})}
function resetField(field){if(![...FIELDS,...SHARED_FIELDS].includes(field))throw new Error('Unknown reading option.');const fallback=field in DEFAULTS?DEFAULTS[field]:{letterSpacing:'DEFAULT',lineSpacing:'DEFAULT',contentWidth:'SYSTEM',readingAlignment:'SYSTEM',paragraphSpacing:'DEFAULT'}[field];return update({[field]:fallback})}
function resetSection(){return update({...DEFAULTS,letterSpacing:'DEFAULT',lineSpacing:'DEFAULT',contentWidth:'SYSTEM',readingAlignment:'SYSTEM',paragraphSpacing:'DEFAULT'},{customize:false})}
function fontForLanguage(code,locale='en'){const font=FONT_REGISTRY[code];if(!font?.available)throw new Error('That reading font is unavailable.');const rtl=/^(ar|he|fa|ur)/i.test(locale),cjk=/^(zh|ja|ko)/i.test(locale);if((rtl||cjk)&&code!=='SYSTEM')return {...FONT_REGISTRY.SYSTEM,fallbackFrom:code,notice:'The selected font is preserved for supported text. A system font is used for this writing system.'};return font}
function readingBlocks(){if(typeof document==='undefined')return [];const active=document.querySelector('.app-view.active,#landing.active')||document.body;return [...active.querySelectorAll('p,li,blockquote,.message p,.transcript')].filter(el=>el.textContent.trim()&&!el.closest('pre,code,.math,[data-math],table,form,.reading-aid-controller'))}
function anchor(){const blocks=readingBlocks();if(!blocks.length)return null;state.anchorIndex=Math.max(0,Math.min(state.anchorIndex,blocks.length-1));return blocks[state.anchorIndex]}
function anchorRect(mode='CURRENT_PARAGRAPH'){const block=anchor();if(!block)return null;if(mode==='CURRENT_LINE'){try{const node=[...block.childNodes].find(n=>n.nodeType===3&&n.textContent.trim());if(node){const range=document.createRange();range.setStart(node,0);range.setEnd(node,Math.min(node.length,1));const rect=range.getClientRects()[0];if(rect?.height)return {rect,fallback:false}}}catch{}}return {rect:block.getBoundingClientRect(),fallback:mode==='CURRENT_LINE'}}
function ensureOverlay(id,className){let el=document.querySelector(`#${id}`);if(!el){el=document.createElement('div');el.id=id;el.className=className;el.setAttribute('aria-hidden','true');el.tabIndex=-1;document.body.appendChild(el)}return el}
function positionOverlay(el,rect,extra=0){el.style.setProperty('--reading-aid-top',`${rect.top+scrollY+extra}px`);el.style.setProperty('--reading-aid-left',`${rect.left+scrollX}px`);el.style.setProperty('--reading-aid-width',`${rect.width}px`);el.style.setProperty('--reading-aid-height',`${Math.max(24,rect.height)}px`)}
function schedule(){if(typeof requestAnimationFrame==='undefined')return;cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(()=>renderAid(read()))}
function renderAid(p=read()){if(typeof document==='undefined')return;const result=anchorRect(p.currentReadingHighlightMode),highlight=p.currentReadingHighlightMode!=='OFF'&&result?ensureOverlay('readingFocusOverlay','reading-focus-overlay'):document.querySelector('#readingFocusOverlay');if(highlight){highlight.dataset.fallback=String(result.fallback);positionOverlay(highlight,result.rect)}else highlight?.remove();const ruler=p.readingRulerEnabled&&result?ensureOverlay('readingRulerOverlay','reading-ruler-overlay'):document.querySelector('#readingRulerOverlay');if(ruler){ruler.dataset.style=p.readingRulerStyle;ruler.dataset.size=p.readingRulerSize;positionOverlay(ruler,result.rect,state.rulerOffset);ensureController(p)}else{ruler?.remove();document.querySelector('#readingAidController')?.remove()}}
function move(delta){const blocks=readingBlocks();if(!blocks.length)return;state.anchorIndex=Math.max(0,Math.min(state.anchorIndex+delta,blocks.length-1));state.rulerOffset=0;schedule();anchor()?.scrollIntoView({block:'center',behavior:'auto'})}
function moveRuler(pixels){state.rulerOffset+=pixels;schedule()}
function ensureController(p){let controller=document.querySelector('#readingAidController');if(controller)return;controller=document.createElement('div');controller.id='readingAidController';controller.className='reading-aid-controller';controller.setAttribute('role','group');controller.setAttribute('aria-label','Reading ruler controls');controller.innerHTML=`<button type="button" data-aid="previous" aria-label="Move reading ruler to previous paragraph">Previous paragraph</button><button type="button" data-aid="next" aria-label="Move reading ruler to next paragraph">Next paragraph</button><button type="button" data-aid="up" aria-label="Move reading ruler up">Move up</button><button type="button" data-aid="down" aria-label="Move reading ruler down">Move down</button><button type="button" data-aid="smaller" aria-label="Decrease reading ruler height">Smaller</button><button type="button" data-aid="larger" aria-label="Increase reading ruler height">Larger</button><button type="button" data-aid="hide-controls">Hide reading ruler controls</button><button type="button" data-aid="off">Turn off reading ruler</button>`;document.body.appendChild(controller);controller.addEventListener('click',event=>{const action=event.target.dataset.aid;if(action==='previous')move(-1);if(action==='next')move(1);if(action==='up')moveRuler(-20);if(action==='down')moveRuler(20);if(action==='smaller')update({readingRulerSize:{LARGE:'MEDIUM',MEDIUM:'SMALL',SMALL:'SMALL'}[read().readingRulerSize]});if(action==='larger')update({readingRulerSize:{SMALL:'MEDIUM',MEDIUM:'LARGE',LARGE:'LARGE'}[read().readingRulerSize]});if(action==='off')update({readingRulerEnabled:false});if(action==='hide-controls')collapseController()})}
function collapseController(){document.querySelector('#readingAidController')?.remove();let button=document.querySelector('#showReadingRulerControls');if(!button){button=document.createElement('button');button.id='showReadingRulerControls';button.type='button';button.className='show-reading-ruler-controls';button.textContent='Show reading ruler controls';button.onclick=()=>{button.remove();ensureController(read())};document.body.appendChild(button)}}
function announce(text){let el=document.querySelector('#dyslexiaDisplayStatus');if(!el){el=document.createElement('div');el.id='dyslexiaDisplayStatus';el.className='sr-only';el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.appendChild(el)}el.textContent='';queueMicrotask(()=>el.textContent=text)}
function capabilityRegistry(){const codes=['DYSLEXIA_SUGGESTED_PRESET','WORD_SPACING','LANGUAGE_AWARE_LETTER_SPACING','DYSLEXIA_CONTENT_WIDTH','READING_DIRECTION_ALIGNMENT','DYSLEXIA_PARAGRAPH_SPACING','ACCESSIBLE_FONT_CHOICES','REDUCED_ITALICS','DECORATIVE_FONT_REDUCTION','REDUCED_VISUAL_CLUTTER','CURRENT_PARAGRAPH_HIGHLIGHT','CURRENT_LINE_HIGHLIGHT','READING_RULER','READING_RULER_MANUAL_CONTROL','READING_RULER_TTS_FOLLOW','MULTILINGUAL_FONT_FALLBACK'];return Object.fromEntries(codes.map(code=>[code,{availability:code==='READING_RULER_TTS_FOLLOW'?'UNAVAILABLE':['CURRENT_LINE_HIGHLIGHT','READING_RULER'].includes(code)?'PARTIAL':'AVAILABLE',supportedRoutes:'Reading prose containers; interactive editors and Study Room video grids excluded',supportedLanguages:code.includes('FONT')?['Latin','system fallback for other scripts']:['Language-aware'],knownLimitations:'Manual browser, zoom, screen-reader, geometry, and performance verification pending.',fallback:code==='CURRENT_LINE_HIGHLIGHT'?'Current paragraph highlight':code==='READING_RULER_TTS_FOLLOW'?'Manual or Follow Reading Focus':'System presentation',automatedTestStatus:'PASS',manualTestStatus:'PENDING',lastVerifiedDate:null}]))}
function friendly(field,value){const labels={SYSTEM:'System',DEFAULT:'Default',RELAXED:'Relaxed',EXPANDED:'Expanded',EXTRA_EXPANDED:'Extra Expanded',OFF:'Off',CURRENT_PARAGRAPH:'Current Paragraph',CURRENT_LINE:'Current Line',HIGHLIGHT_BAND:'Highlight Band',FOCUS_STRIP:'Underline Guide',DIM_SURROUNDING_CONTENT:'Reading Window',SMALL:'Small',MEDIUM:'Medium',LARGE:'Large',MANUAL:'Manual',FOLLOW_READING_FOCUS:'Follow Reading Focus',STUDYSPARK_DEFAULT:'StudySpark Default',HUMANIST_SANS:'Humanist Sans',READABLE_SERIF:'Readable Serif'};return labels[value]||FONT_REGISTRY[value]?.displayName||value.replaceAll('_',' ')}
function option(label,field,values){return `<label class="reading-comfort-legacy-select"><span>${label}</span><select data-dyslexia-pref="${field}">${values.map(v=>`<option value="${v}">${friendly(field,v)}</option>`).join('')}</select></label>`}
function controls(){return `<fieldset class="dyslexia-display-controls reading-comfort-legacy-panel"><legend>Reading Comfort</legend><p>Adjust text, spacing, and reading aids until StudySpark feels comfortable to use. No diagnosis is required, and these settings do not change lesson content.</p><div class="reading-comfort-legacy-actions"><button class="btn btn-secondary" data-dyslexia-preset type="button">Try Suggested Reading Settings</button><button class="btn btn-secondary" data-dyslexia-undo type="button">Undo Suggested Settings</button></div>${option('Word spacing','wordSpacingPreference',['DEFAULT','RELAXED','EXPANDED'])}${option('Reading font','accessibleFontPreference',Object.keys(FONT_REGISTRY))}<label class="reading-comfort-legacy-toggle"><input type="checkbox" data-dyslexia-pref="reduceItalicText"> <span>Reduce italic text</span></label><label class="reading-comfort-legacy-toggle"><input type="checkbox" data-dyslexia-pref="disableDecorativeFonts"> <span>Reduce decorative fonts</span></label><label class="reading-comfort-legacy-toggle"><input type="checkbox" data-dyslexia-pref="reduceVisualClutter"> <span>Reduce visual clutter</span></label>${option('Highlight current reading area','currentReadingHighlightMode',['OFF','CURRENT_PARAGRAPH','CURRENT_LINE'])}<label class="reading-comfort-legacy-toggle"><input type="checkbox" data-dyslexia-pref="readingRulerEnabled"> <span>Reading ruler</span></label><p class="reading-ruler-conditional-note" data-ruler-note>Turn on Reading Ruler to choose its style and size.</p><div class="reading-ruler-options" data-ruler-details hidden>${option('Reading ruler style','readingRulerStyle',['HIGHLIGHT_BAND','FOCUS_STRIP','DIM_SURROUNDING_CONTENT'])}${option('Reading ruler size','readingRulerSize',['SMALL','MEDIUM','LARGE'])}</div><button class="btn btn-secondary" data-reset-dyslexia-section type="button">Reset Reading Comfort</button></fieldset>`}
function inject(){const toolbar=document.querySelector('#accessibilityToolbarPanel .accessibility-toolbar-scroll'),full=document.querySelector('#accessPrefsForm');if(toolbar&&!toolbar.querySelector('.dyslexia-display-controls'))toolbar.insertAdjacentHTML('beforeend',controls());if(full&&!full.querySelector('.reading-comfort-section')&&!full.querySelector('.dyslexia-display-controls'))full.insertAdjacentHTML('beforeend',controls());document.querySelectorAll('[data-pref="dyslexiaFriendlyDisplayEnabled"]').forEach(el=>el.closest('label').hidden=true);bind();syncControls(read())}
function bind(){document.querySelectorAll('[data-dyslexia-pref]:not([data-dyslexia-bound])').forEach(control=>{control.dataset.dyslexiaBound='true';control.addEventListener('change',()=>update({[control.dataset.dyslexiaPref]:control.type==='checkbox'?control.checked:control.value}))});document.querySelectorAll('[data-reset-dyslexia]:not([data-dyslexia-bound])').forEach(button=>{button.dataset.dyslexiaBound='true';button.onclick=()=>resetField(button.dataset.resetDyslexia)});document.querySelectorAll('[data-dyslexia-preset]:not([data-dyslexia-bound])').forEach(button=>{button.dataset.dyslexiaBound='true';button.onclick=applySuggestedPreset});document.querySelectorAll('[data-dyslexia-undo]:not([data-dyslexia-bound])').forEach(button=>{button.dataset.dyslexiaBound='true';button.onclick=undoPreset});document.querySelectorAll('[data-reset-dyslexia-section]:not([data-dyslexia-bound])').forEach(button=>{button.dataset.dyslexiaBound='true';button.onclick=()=>confirm('Reset reading comfort spacing, font, clutter, highlight, and ruler options? Language, captions, speech, bandwidth, Study Room preferences, account, and progress will stay unchanged.')&&resetSection()})}
function syncControls(p){document.querySelectorAll('[data-dyslexia-pref]').forEach(control=>{const value=p[control.dataset.dyslexiaPref];if(control.type==='checkbox')control.checked=Boolean(value);else control.value=value});document.querySelectorAll('[data-ruler-details]').forEach(el=>{el.hidden=!p.readingRulerEnabled});document.querySelectorAll('[data-ruler-note]').forEach(el=>{el.hidden=Boolean(p.readingRulerEnabled)})}
function seedDevelopmentData(){return [{name:'Ruler only',developmentOnly:true,values:{...DEFAULTS,readingRulerEnabled:true}},{name:'Current line only',developmentOnly:true,values:{...DEFAULTS,currentReadingHighlightMode:'CURRENT_LINE'}},{name:'Word spacing only',developmentOnly:true,values:{...DEFAULTS,wordSpacingPreference:'EXPANDED'}},{name:'Humanist and reduced italics',developmentOnly:true,values:{...DEFAULTS,accessibleFontPreference:'HUMANIST_SANS',reduceItalicText:true}},{name:'RTL with ruler',developmentOnly:true,values:{...DEFAULTS,readingRulerEnabled:true,readingAlignment:'READING_DIRECTION_START'}},{name:'No options',developmentOnly:true,values:{...DEFAULTS}}]}
function init(){let initial=read();if(registered()&&A){const account=A.getMyAccessibilityLanguageProfile()||{},accountPatch={};for(const key of [...FIELDS,...SHARED_FIELDS])if(key in account)accountPatch[key]=account[key];initial=validate({...initial,...accountPatch});persist(initial)}apply(initial);inject();new MutationObserver(inject).observe(document.body,{subtree:true,childList:true});addEventListener('resize',schedule,{passive:true});addEventListener('scroll',schedule,{passive:true});document.fonts?.ready.then(schedule);addEventListener('storage',event=>{if(event.key===KEY&&event.newValue)try{apply(JSON.parse(event.newValue));syncControls(read())}catch{}});addEventListener('online',()=>{if(state.pendingAccount)syncAccount(ownerView(read()))})}
if(typeof document!=='undefined')document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
const api={DYSLEXIA_FRIENDLY_DISPLAY_NOTICE,FIELDS,DEFAULTS,PRESET,FONT_REGISTRY,migrateExistingDyslexiaFriendlyPreferences:migrate,validateDyslexiaFriendlyPreferences:validate,getMyDyslexiaFriendlyDisplayPreferences:read,getEffectiveDyslexiaFriendlyDisplayPreferences:read,updateMyDyslexiaFriendlyDisplayPreferences:update,updateMyDyslexiaFriendlyDisplayField:(field,value)=>update({[field]:value}),applySuggestedDyslexiaFriendlyPreset:applySuggestedPreset,undoSuggestedPreset:undoPreset,resetMyDyslexiaFriendlyDisplayField:resetField,resetMyDyslexiaFriendlyDisplayPreferences:resetSection,listAvailableReadingFonts:()=>Object.entries(FONT_REGISTRY).map(([code,value])=>({code,...value})),getFontCapabilityForLanguage:fontForLanguage,validateReadingFontPreference:fontForLanguage,getReadingFontFallback:fontForLanguage,getReadingFocusCapability:()=>capabilityRegistry().CURRENT_LINE_HIGHLIGHT,setCurrentReadingHighlightMode:mode=>update({currentReadingHighlightMode:mode}),enableCurrentReadingHighlight:()=>update({currentReadingHighlightMode:'CURRENT_PARAGRAPH'}),disableCurrentReadingHighlight:()=>update({currentReadingHighlightMode:'OFF'}),moveReadingFocusToPreviousParagraph:()=>move(-1),moveReadingFocusToNextParagraph:()=>move(1),moveReadingFocusToPreviousLine:()=>move(-1),moveReadingFocusToNextLine:()=>move(1),getReadingRulerCapability:()=>capabilityRegistry().READING_RULER,enableReadingRuler:()=>update({readingRulerEnabled:true}),disableReadingRuler:()=>update({readingRulerEnabled:false}),updateReadingRulerStyle:value=>update({readingRulerStyle:value}),updateReadingRulerSize:value=>update({readingRulerSize:value}),updateReadingRulerTrackingMode:value=>update({readingRulerTrackingMode:value}),moveReadingRulerUp:()=>moveRuler(-20),moveReadingRulerDown:()=>moveRuler(20),getDyslexiaDisplayCapabilityRegistry:capabilityRegistry,toDyslexiaDisplayOwnerView:ownerView,toDyslexiaDevicePreferenceSnapshot:ownerView,seedDevelopmentData,_test:{anchorRect,readingBlocks,fontForLanguage,state}};
if(typeof module!=='undefined'&&module.exports)module.exports=api;root.DyslexiaDisplay=api;
})(typeof window!=='undefined'?window:globalThis);
