(function(){
'use strict';
const REQUIRED_MODULES=['StudentOnboarding','TutorApplication','TutorVerification','TutoringRequests','TutorMatching','SafeBooking','SessionAttendance','PostSessionLearning','CommunityService','ServiceDocuments','SafetySafeguarding','IntegrityReview','HelpCredits'];
const SCENARIOS=Object.freeze([
['01','Learner registration','student-onboarding.test.js',['StudentProfile','GuardianConsent']],['02','Tutor application','tutor-application.test.js',['TutorApplication','TutorApplicationSubject']],['03','Partial subject verification','tutor-verification.test.js',['TutorApplicationSubjectDecision','ApprovedTutorCapability']],['04','Tutoring request','tutoring-requests.test.js',['TutoringRequest']],['05','Eligible AI recommendations','tutor-matching.test.js',['TutorMatchingRun','TutorMatchingCandidate']],['06','Tutor accepts session','safe-booking.test.js',['BookingInvitation','TutoringSession','Conversation']],['07','Dual attendance','session-attendance.test.js',['SessionAttendance','ParticipantAttendance']],['08','Reflections and joint summary','post-session-learning.test.js',['SessionLearningRecord','SessionSummary']],['09','Human service approval','community-service.test.js',['CommunityServiceRecord','CommunityServiceDecision']],['10','Service record download','service-documents.test.js',['CommunityServiceDocument']],['11','Inappropriate-behaviour report','safety-safeguarding.test.js',['SafetyReport','SafetyCase']],['12','Human account suspension','safety-safeguarding.test.js',['AccountRestriction']],['13','Suspicious-session warning','integrity-review.test.js',['IntegrityIndicator','IntegrityReviewCase']],['14','Sponsored zero-credit support','help-credits.test.js',['HelpCreditFundingAuthorization','HelpCreditSessionSettlement']],['15','Cancellation earns no hours','safe-booking.test.js',['TutoringSession']]
].map(([id,name,testFile,records])=>Object.freeze({id,name,testFile,records:Object.freeze(records),layers:Object.freeze(['UI contract','authorization','state','privacy','audit','idempotency'])})));
const INVARIANTS=Object.freeze({humanAuthority:['tutor verification','service approval','safety suspension','integrity finding'],separation:['booking is not attendance','service hours are not Help Credits','warning is not a finding','report is not a suspension'],cancellation:['no verified attendance','no service record','no tutor earning','funding released'],privacy:['funding excluded from matching','reporter identity confidential','private evidence excluded','protected characteristics excluded']});
function coverage(){const available=REQUIRED_MODULES.every(k=>Boolean(window[k]));return SCENARIOS.map(s=>({...s,moduleAvailable:available,status:available?'AUTOMATED_MODULE_COVERAGE':'BLOCKED'}))}
function report(){const rows=coverage();return {step:20,scenarioCount:rows.length,coveredScenarioCount:rows.filter(x=>x.moduleAvailable).length,scenarios:rows,invariants:INVARIANTS,limitations:['Browser-local domain tests are not deployed server tests.','No Playwright, test database, mail server, object storage, CI, linter, type checker, migration, or production build is configured.'],completeEndToEndClaim:false}}
function render(){const root=document.querySelector('#journeyTestingContent');if(!root)return;const r=report();root.innerHTML=`<div class="card journey-test-hero"><span class="kicker">STEP 20 · EXECUTED TEST EVIDENCE</span><h2>${r.coveredScenarioCount} of ${r.scenarioCount} journeys have automated module coverage</h2><p>The suite checks workflow rules, authorization boundaries, state, privacy, audits, idempotency, and recovery. A production browser/server journey is not claimed by this static prototype.</p></div><div class="journey-test-grid">${r.scenarios.map(s=>`<article class="card"><span class="tutoring-status">${s.status}</span><h3>${s.id}. ${s.name}</h3><p>${s.testFile}</p><small>${s.records.join(' · ')}</small></article>`).join('')}</div>`}
if(typeof viewNames!=='undefined')viewNames.journeyTesting=['PLATFORM','Journey Tests'];document.addEventListener('click',e=>{if(e.target.closest('[data-view="journeyTesting"]'))setTimeout(render,0)});
window.JourneyTesting={REQUIRED_MODULES,SCENARIOS,INVARIANTS,getCoverageMatrix:coverage,getJourneyTestReport:report,render};
})();
