(function(root){'use strict';
const P=root.PlainLanguage||(typeof require==='function'?require('./plain-language.js'):null),E=root.ExplanationLevels||(typeof require==='function'?require('./explanation-levels.js'):null);
const LANGUAGE_BRIDGE_AI_NOTICE='AI-generated translations may contain mistakes. Keep the English academic terms visible and check important names, numbers, formulas, technical terms, and instructions against the original English version.';
const MODES=Object.freeze(['ENGLISH_ONLY','BRIDGE_LANGUAGE_ONLY','ENGLISH_THEN_BRIDGE','BRIDGE_THEN_ENGLISH','SIDE_BY_SIDE_BILINGUAL','ENGLISH_WITH_TRANSLATED_KEYWORDS']);
const LABELS=Object.freeze({ENGLISH_ONLY:'English only',BRIDGE_LANGUAGE_ONLY:'Home language only',ENGLISH_THEN_BRIDGE:'English first, then home language',BRIDGE_THEN_ENGLISH:'Home language first, then English',SIDE_BY_SIDE_BILINGUAL:'Side-by-side bilingual',ENGLISH_WITH_TRANSLATED_KEYWORDS:'English with translated keywords'});
const LANGUAGES=Object.freeze([{code:'zh-Hans',nativeName:'中文（简体）',englishName:'Chinese, Simplified',dir:'ltr',fullFixture:true},{code:'zh-Hant',nativeName:'繁體中文',englishName:'Chinese, Traditional',dir:'ltr',fullFixture:false},{code:'fr',nativeName:'Français',englishName:'French',dir:'ltr',fullFixture:false},{code:'es',nativeName:'Español',englishName:'Spanish',dir:'ltr',fullFixture:false},{code:'ar',nativeName:'العربية',englishName:'Arabic',dir:'rtl',fullFixture:false}]);
const POLICY=Object.freeze({id:'studyspark-language-bridge',version:'2026.1',active:true,supportedModes:MODES,supportedBridgeLanguages:LANGUAGES.map(x=>x.code),englishAcademicLanguageCode:'en',terminologyRegistryVersion:'2026.1',provider:'DETERMINISTIC_REVIEWED_FIXTURE',correctiveRetries:0});
const PHOTO_EN='Photosynthesis is the process plants use to convert light energy into chemical energy.',PHOTO_ZH='光合作用是植物将光能转化为化学能的过程。';
const TERMS=Object.freeze([
 {id:'bio-photosynthesis',subject:'Biology',englishTerm:'Photosynthesis',definitionEnglish:'The process plants use to convert light energy into chemical energy.',translations:{'zh-Hans':{term:'光合作用',definition:'植物将光能转化为化学能的过程。',reviewStatus:'APPROVED_GLOSSARY',source:'ORGANIZATION_GLOSSARY'}}},
 {id:'bio-light-energy',subject:'Biology',englishTerm:'Light energy',definitionEnglish:'Energy carried by light.',translations:{'zh-Hans':{term:'光能',definition:'光所携带的能量。',reviewStatus:'APPROVED_GLOSSARY',source:'ORGANIZATION_GLOSSARY'}}},
 {id:'bio-chemical-energy',subject:'Biology',englishTerm:'Chemical energy',definitionEnglish:'Energy stored in chemical bonds.',translations:{'zh-Hans':{term:'化学能',definition:'储存在化学键中的能量。',reviewStatus:'APPROVED_GLOSSARY',source:'ORGANIZATION_GLOSSARY'}}},
 {id:'bio-chlorophyll',subject:'Biology',englishTerm:'Chlorophyll',definitionEnglish:'The green pigment that absorbs light.',translations:{'zh-Hans':{term:'叶绿素',definition:'吸收光的绿色色素。',reviewStatus:'APPROVED_GLOSSARY',source:'ORGANIZATION_GLOSSARY'}}}
]);
const artifacts=new Map(),cache=new Map();let active=null;
const hash=x=>P._test.hash(String(x)),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function language(code){const row=LANGUAGES.find(x=>x.code===code);if(!row)throw Error('Unsupported home or bridge language.');return row}
function mode(value){if(!MODES.includes(value))throw Error('Unsupported Language Bridge mode.');return value}
function requiredTerms(source,contract){const supplied=(source.requiredEnglishAcademicTerms||[]).map(x=>typeof x==='string'?x:x.englishTerm);const academic=(contract.requiredAcademicTerms||[]).map(x=>typeof x==='string'?x:x.term);return [...new Set([...supplied,...academic].filter(Boolean))]}
function glossaryFor(source,code){const requested=source.requiredEnglishAcademicTerms?.length?source.requiredEnglishAcademicTerms.map(x=>typeof x==='string'?x:x.englishTerm):TERMS.map(x=>x.englishTerm);return TERMS.filter(x=>requested.some(t=>t.toLowerCase()===x.englishTerm.toLowerCase())).map(x=>{const t=code?x.translations[code]:null;return{id:x.id,englishTerm:x.englishTerm,bridgeTerm:t?.term||null,englishDefinition:x.definitionEnglish,bridgeDefinition:t?.definition||null,translationReviewStatus:t?.reviewStatus||'NOT_VERIFIED',source:t?.source||null,englishTermPreserved:true}})}
function englishFor(source,level){return E.generateExplanationLevel(source,{level}).adaptation.structuredOutput.blocks.map(x=>x.text).join(' ')}
function photoFixture(source,code){return code==='zh-Hans'&&(source.fixtureKey==='PHOTOSYNTHESIS_LANGUAGE_BRIDGE'||source.text===PHOTO_EN)}
function validateEnglishTerms(artifact){const hay=[artifact.englishText,...artifact.glossary.map(x=>x.englishTerm),artifact.bridgeText||''].join(' ').toLowerCase(),missing=artifact.requiredEnglishTerms.filter(x=>!hay.includes(x.toLowerCase()));return{valid:!missing.length,status:missing.length?'FAILED_REQUIRED_ENGLISH_TERM':'PASSED',missing}}
function validatePreserved(source,artifact,contract){const combined=`${artifact.englishText} ${artifact.bridgeText||''}`;const base=P.validatePlainLanguageAdaptation(source,artifact.englishText,contract);if(base.status!=='PASSED')return{valid:false,status:base.status};for(const value of [...(contract.requiredEquations||[]),...(contract.requiredNumbers||[]),...(contract.requiredUnits||[]),...(contract.requiredScientificNames||[]),...(contract.requiredCode||[])])if(value&&!combined.includes(value))return{valid:false,status:'FAILED_PRESERVED_ELEMENT',missing:value};return{valid:true,status:'PASSED'}}
function validateLanguageBridgeArtifact(a){const term=validateEnglishTerms(a),preserved=validatePreserved(a.originalSource,a,a.contract),bridgeRequired=a.languageBridgeMode!=='ENGLISH_ONLY'&&a.languageBridgeMode!=='ENGLISH_WITH_TRANSLATED_KEYWORDS';if(bridgeRequired&&!a.bridgeText)return{valid:false,status:'FAILED_BRIDGE_CONTENT'};if(!term.valid)return term;if(!preserved.valid)return preserved;return{valid:true,status:'PASSED',backTranslationUsedAsProof:false,semanticEquivalenceIndependentlyVerified:false}}
function request(source,{languageBridgeMode='ENGLISH_ONLY',bridgeLanguageCode=null,explanationLevel='LEVEL_3_STANDARD_ACADEMIC'}={}){mode(languageBridgeMode);if(!E.EXPLANATION_LEVELS.includes(explanationLevel))throw Error('Unsupported explanation level.');if(languageBridgeMode!=='ENGLISH_ONLY'&&!bridgeLanguageCode)throw Error('Choose a home or bridge language to use this mode.');const lang=bridgeLanguageCode?language(bridgeLanguageCode):null,contract=P.createAcademicContentContract(source),englishText=englishFor(source,explanationLevel),glossary=glossaryFor(source,lang?.code||null);
 if(source.assessmentContext==='ACTIVE_ASSESSMENT'&&!source.languageBridgePermitted)throw Error('Language Bridge is limited for this active assessment. The original English assessment remains available.');
 if(source.highStakesType&&source.highStakesType!=='NONE'&&languageBridgeMode!=='ENGLISH_ONLY'&&!source.humanReviewedTranslation)throw Error('Official English remains authoritative. No human-reviewed supplemental translation is available.');
 let bridgeText=null;if(languageBridgeMode!=='ENGLISH_ONLY'&&languageBridgeMode!=='ENGLISH_WITH_TRANSLATED_KEYWORDS'){if(!photoFixture(source,lang.code))throw Error('StudySpark could not create a reliable Language Bridge version. The original English explanation remains available.');bridgeText=PHOTO_ZH}
 const key=[source.sourceType,source.sourceId,source.sourceVersion,explanationLevel,languageBridgeMode,bridgeLanguageCode||'none',contract.contractHash,POLICY.version,POLICY.terminologyRegistryVersion].join(':');if(cache.has(key))return owner(cache.get(key));
 const blocks=[{id:'bridge-block-main',sourceElementIds:['source-main'],blockType:'MAIN_IDEA',sequence:1,english:{text:englishText,languageCode:'en',direction:'LTR'},bridge:{text:bridgeText,languageCode:lang?.code||null,direction:lang?.dir?.toUpperCase()||null},requiredEnglishTerms:requiredTerms(source,contract),preservedFormulas:contract.requiredEquations||[],preservedNumbersAndUnits:[...(contract.requiredNumbers||[]),...(contract.requiredUnits||[])],citationIds:[]}];
 const a={id:`language-bridge-${hash(key)}`,sourceType:source.sourceType,sourceId:source.sourceId,sourceVersion:String(source.sourceVersion),sourceContentHash:hash(source.text),explanationLevel,explanationStructure:'STANDARD',languageBridgeMode,englishLanguageCode:'en',bridgeLanguageCode:lang?.code||null,academicTerminologyLanguageCode:'en',policyId:POLICY.id,policyVersion:POLICY.version,academicContractVersion:contract.contractVersion,academicContractHash:contract.contractHash,terminologyRegistryVersion:POLICY.terminologyRegistryVersion,promptVersion:'deterministic-reviewed-fixture-v1',modelProvider:'DETERMINISTIC_REVIEWED_FIXTURE',modelVersion:'1',status:'PENDING_VALIDATION',englishText,bridgeText,structuredOutput:{languageBridgeMode,englishLanguageCode:'en',bridgeLanguageCode:lang?.code||null,explanationLevel,blocks,academicTerms:glossary},glossary,requiredEnglishTerms:requiredTerms(source,contract),contract,originalSource:{...source},originalEnglish:source.text,generatedDirectlyFromOriginal:true,translationCertified:false,humanReviewed:Boolean(source.humanReviewedTranslation?.reviewerUserId&&source.humanReviewedTranslation?.reviewedAt),notice:LANGUAGE_BRIDGE_AI_NOTICE,createdAt:new Date().toISOString(),invalidatedAt:null};
 const validation=validateLanguageBridgeArtifact(a);if(!validation.valid)throw Error('StudySpark could not create a reliable Language Bridge version. The original English explanation remains available.');a.status='READY';a.validationStatus=validation.status;a.validationSummary=validation;artifacts.set(a.id,a);cache.set(key,a);return owner(a)}
function owner(a){return{id:a.id,sourceType:a.sourceType,sourceId:a.sourceId,sourceVersion:a.sourceVersion,explanationLevel:a.explanationLevel,languageBridgeMode:a.languageBridgeMode,englishLanguageCode:'en',bridgeLanguageCode:a.bridgeLanguageCode,academicTerminologyLanguageCode:'en',status:a.status,englishText:a.englishText,bridgeText:a.bridgeText,structuredOutput:a.structuredOutput,glossary:a.glossary,requiredEnglishTerms:[...a.requiredEnglishTerms],originalEnglish:a.originalEnglish,originalAvailable:true,generatedDirectlyFromOriginal:true,validationStatus:a.validationStatus,translationCertified:false,humanReviewed:a.humanReviewed,notice:a.notice,policyVersion:a.policyVersion,academicContractHash:a.academicContractHash,terminologyRegistryVersion:a.terminologyRegistryVersion}}
function keywordText(view){let out=view.englishText;for(const t of view.glossary.filter(x=>x.bridgeTerm))out=out.replace(new RegExp(`\\b${t.englishTerm.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i'),m=>`${m} (${t.bridgeTerm})`);return out}
function sections(view){const english=`<section lang="en" dir="ltr"><h3>English</h3><p>${esc(view.languageBridgeMode==='ENGLISH_WITH_TRANSLATED_KEYWORDS'?keywordText(view):view.englishText)}</p></section>`,bridge=view.bridgeText?`<section lang="${esc(view.bridgeLanguageCode)}" dir="${esc(language(view.bridgeLanguageCode).dir)}"><h3>${view.bridgeLanguageCode==='zh-Hans'?'中文解释':'Bridge-language explanation'}</h3><p>${esc(view.bridgeText)}</p></section>`:'';if(view.languageBridgeMode==='BRIDGE_LANGUAGE_ONLY')return bridge;if(view.languageBridgeMode==='BRIDGE_THEN_ENGLISH')return bridge+english;if(view.languageBridgeMode==='SIDE_BY_SIDE_BILINGUAL')return `<div class="language-bridge-pairs"><div class="language-bridge-pair">${english}${bridge}</div></div>`;if(view.languageBridgeMode==='ENGLISH_THEN_BRIDGE')return english+bridge;return english}
function glossaryHtml(view){return `<details open><summary>Important Academic Terms</summary><dl>${view.glossary.map(x=>`<div><dt lang="en">${esc(x.englishTerm)}</dt><dd lang="${esc(view.bridgeLanguageCode)}" dir="${esc(view.bridgeLanguageCode?language(view.bridgeLanguageCode).dir:'ltr')}">${esc(x.bridgeTerm||'Translation not yet verified')}</dd><dd>${esc(x.englishDefinition)}</dd></div>`).join('')}</dl></details>`}
function show(source,view,trigger){active={source,view,trigger};let p=document.querySelector('#languageBridgePanel');if(!p){p=document.createElement('section');p.id='languageBridgePanel';p.className='language-bridge-panel';p.setAttribute('aria-labelledby','languageBridgeTitle');document.body.appendChild(p)}p.innerHTML=`<header><div><h2 id="languageBridgeTitle">Language Bridge</h2><p><b>${LABELS[view.languageBridgeMode]}</b></p><p>${LANGUAGE_BRIDGE_AI_NOTICE}</p><p>English academic terms and the original English explanation remain available.</p></div><button type="button" data-bridge="close">Close</button></header><label>Select Language Bridge mode<select id="languageBridgeMode">${MODES.map(x=>`<option value="${x}" ${x===view.languageBridgeMode?'selected':''}>${LABELS[x]}</option>`).join('')}</select></label><label>Home or bridge language<select id="bridgeLanguage"><option value="">Choose when needed</option>${LANGUAGES.map(x=>`<option value="${x.code}" ${x.code===view.bridgeLanguageCode?'selected':''} lang="${x.code}">${x.nativeName} — ${x.englishName}${x.fullFixture?'':' (glossary only)'}</option>`).join('')}</select></label><div class="language-bridge-actions"><button type="button" data-bridge="terms">Show Important Academic Terms</button><button type="button" data-bridge="original">Show original English explanation</button><button type="button" data-bridge="compare">Compare languages</button><button type="button" data-bridge="listen-en">Listen to English explanation</button><button type="button" data-bridge="listen-other" ${view.bridgeText?'':'disabled'}>Listen to bridge-language explanation</button><button type="button" data-bridge="save">Save this Language Bridge mode as my default</button><button type="button" data-bridge="report">Report a translation problem</button></div><div id="languageBridgeStatus" role="status" aria-live="polite"></div><article id="languageBridgeContent" aria-label="AI-generated Language Bridge explanation">${sections(view)}${glossaryHtml(view)}</article>`;
 const status=p.querySelector('#languageBridgeStatus'),content=p.querySelector('#languageBridgeContent'),change=()=>{try{show(source,request(source,{languageBridgeMode:p.querySelector('#languageBridgeMode').value,bridgeLanguageCode:p.querySelector('#bridgeLanguage').value||null,explanationLevel:view.explanationLevel}),trigger)}catch(e){status.textContent=e.message}};p.querySelector('#languageBridgeMode').onchange=change;p.querySelector('#bridgeLanguage').onchange=change;p.querySelector('[data-bridge="terms"]').onclick=()=>content.querySelector('details')?.setAttribute('open','');p.querySelector('[data-bridge="original"]').onclick=()=>{content.innerHTML=`<section lang="en" dir="ltr"><h3>Original English explanation</h3><p>${esc(source.text)}</p></section>`};p.querySelector('[data-bridge="compare"]').onclick=()=>{content.innerHTML=`${sections(view)}${glossaryHtml(view)}`};p.querySelector('[data-bridge="listen-en"]').onclick=()=>listen(view,'en',p);p.querySelector('[data-bridge="listen-other"]').onclick=()=>listen(view,view.bridgeLanguageCode,p);p.querySelector('[data-bridge="save"]').onclick=()=>saveDefault(view,status);p.querySelector('[data-bridge="report"]').onclick=()=>{status.textContent='Translation problem noted locally for this prototype. No explanation text was sent.'};p.querySelector('[data-bridge="close"]').onclick=()=>{p.remove();trigger?.focus()}}
function listen(view,code,panel){const text=code==='en'?view.englishText:view.bridgeText,d=root.TextToSpeech?.createSpeechDocument?.({sourceType:'AI_EXPLANATION',sourceId:`${view.id}-${code}`,sourceVersion:view.sourceVersion,title:`Language Bridge ${code}`,defaultLanguageCode:code,blocks:[{id:`bridge-speech-${code}`,blockType:'PARAGRAPH',visibleText:text}],authorized:true});if(d)root.TextToSpeech.startTextToSpeech(d,panel)}
function saveDefault(view,status){const okay=typeof root.confirm==='function'?root.confirm(`Save ${LABELS[view.languageBridgeMode]} as your default Language Bridge mode?`):false;if(!okay){if(status)status.textContent='Language Bridge default was not changed.';return false}let raw={};try{raw=JSON.parse(localStorage.getItem('studyspark.accessibilityToolbar.v1')||'{}')}catch{}localStorage.setItem('studyspark.accessibilityToolbar.v1',JSON.stringify({...raw,languageBridgeEnabled:view.languageBridgeMode!=='ENGLISH_ONLY',defaultLanguageBridgeMode:view.languageBridgeMode,bridgeLanguageCode:view.bridgeLanguageCode,academicTerminologyLanguageCode:'en',preserveEnglishAcademicTerms:true,academicTermDisplayMode:'INLINE_AND_GLOSSARY',updatedAt:new Date().toISOString()}));if(status)status.textContent='Language Bridge default saved.';return true}
function inject(){document.querySelectorAll('.message.ai,.instruction-grid article,.help-guide-step,.analysis-card,.quiz-result,.explanation,.schedule-card,.session-summary,.vocabulary-definition,.folder-instructions').forEach(el=>{if(el.querySelector('.language-bridge-button')||el.closest('[hidden],[aria-hidden="true"]')||el.matches('.safety-warning,.integrity-warning,.privacy-notice'))return;const b=document.createElement('button');b.type='button';b.className='btn btn-secondary language-bridge-button';b.textContent='English + My Language';b.setAttribute('aria-label',`Show English and my language for ${el.querySelector(':scope > h2,:scope > h3,:scope > h4,:scope > b')?.textContent?.trim()||'this explanation'}`);b.onclick=()=>{try{const s=P.createExplanationSourceFromElement(el);show(s,request(s),b)}catch(e){b.setAttribute('aria-description',e.message)}};(root.AICoachLanguageTools?.add(el,b)||el.insertAdjacentElement('afterbegin',b))})}
function invalidate(sourceId,newVersion){for(const a of artifacts.values())if(a.sourceId===sourceId&&a.sourceVersion!==String(newVersion))a.invalidatedAt=new Date().toISOString();for(const[k,a]of cache)if(a.sourceId===sourceId&&a.sourceVersion!==String(newVersion))cache.delete(k);if(active?.source.sourceId===sourceId)document.querySelector('#languageBridgePanel')?.remove()}
function capabilities(){return{LANGUAGE_BRIDGE:{available:true,supportLevel:'PARTIALLY_SUPPORTED',provider:POLICY.provider,manualTestStatus:'PENDING'},ENGLISH_ONLY:{available:true,supportLevel:'AVAILABLE',manualTestStatus:'PENDING'},REVIEWED_PHOTOSYNTHESIS_ZH_HANS:{available:true,supportLevel:'DEVELOPMENT_FIXTURE_ONLY',manualTestStatus:'PENDING'},GENERAL_FULL_TRANSLATION:{available:false,supportLevel:'NOT_AVAILABLE',manualTestStatus:'PENDING'},APPROVED_TERMINOLOGY_GLOSSARY:{available:true,supportLevel:'LIMITED',manualTestStatus:'PENDING'},HUMAN_REVIEW_WORKFLOW:{available:false,supportLevel:'NOT_AVAILABLE',manualTestStatus:'PENDING'},CERTIFIED_TRANSLATION:{available:false,supportLevel:'NOT_AVAILABLE',manualTestStatus:'PENDING'},MIXED_LANGUAGE_TTS:{available:false,supportLevel:'NOT_AVAILABLE',manualTestStatus:'PENDING'},OFFLINE_NEW_TRANSLATION:{available:false,supportLevel:'NOT_AVAILABLE',manualTestStatus:'PENDING'},SEMANTIC_TRANSLATION_EQUIVALENCE:{available:false,supportLevel:'NOT_AVAILABLE',manualTestStatus:'PENDING'}}}
function seed(){return[{developmentOnly:true,name:'Required photosynthesis bridge',source:{sourceType:'AI_EXPLANATION',sourceId:'language-bridge-photo',sourceVersion:'1',fixtureKey:'PHOTOSYNTHESIS_LANGUAGE_BRIDGE',title:'Photosynthesis',subject:'Biology',courseOrGrade:'Grade 9',academicLevel:'GRADE_APPROPRIATE',languageCode:'en',learningObjective:'Explain how plants convert light energy into chemical energy.',requiredAcademicTerms:['Photosynthesis','Light energy','Chemical energy'],requiredEnglishAcademicTerms:['Photosynthesis','Light energy','Chemical energy','Chlorophyll'],text:PHOTO_EN,assessmentContext:'NOT_ASSESSED',authorized:true,adaptationEligible:true}},{developmentOnly:true,name:'Unsupported language'},{developmentOnly:true,name:'Active assessment blocked'},{developmentOnly:true,name:'Formula preservation',formula:'F = ma'},{developmentOnly:true,name:'RTL metadata',languageCode:'ar',direction:'rtl'}]}
function init(){inject();new MutationObserver(inject).observe(document.querySelector('#viewContainer')||document.body,{subtree:true,childList:true})}if(typeof document!=='undefined')(document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init());
const api={LANGUAGE_BRIDGE_AI_NOTICE,LANGUAGE_BRIDGE_MODES:MODES,LANGUAGE_BRIDGE_MODE_LABELS:LABELS,LANGUAGE_BRIDGE_POLICY:POLICY,SUPPORTED_BRIDGE_LANGUAGES:LANGUAGES,ACADEMIC_TERMINOLOGY_REGISTRY:TERMS,getLanguageBridgeCapabilities:capabilities,getSupportedLanguageBridgeModes:()=>MODES,listSupportedBridgeLanguages:()=>LANGUAGES,getAcademicTerminologyCapabilities:()=>capabilities().APPROVED_TERMINOLOGY_GLOSSARY,requestLanguageBridgeExplanation:request,requestEnglishOnlyExplanation:(s,o={})=>request(s,{...o,languageBridgeMode:'ENGLISH_ONLY'}),requestBridgeLanguageOnlyExplanation:(s,o)=>request(s,{...o,languageBridgeMode:'BRIDGE_LANGUAGE_ONLY'}),requestEnglishThenBridgeExplanation:(s,o)=>request(s,{...o,languageBridgeMode:'ENGLISH_THEN_BRIDGE'}),requestBridgeThenEnglishExplanation:(s,o)=>request(s,{...o,languageBridgeMode:'BRIDGE_THEN_ENGLISH'}),requestSideBySideBilingualExplanation:(s,o)=>request(s,{...o,languageBridgeMode:'SIDE_BY_SIDE_BILINGUAL'}),requestEnglishWithTranslatedKeywords:(s,o)=>request(s,{...o,languageBridgeMode:'ENGLISH_WITH_TRANSLATED_KEYWORDS'}),getAuthorizedLanguageBridgeArtifact:id=>artifacts.has(id)?owner(artifacts.get(id)):null,getImportantAcademicTerms:glossaryFor,validateLanguageBridgeArtifact,validateRequiredEnglishTerms:validateEnglishTerms,saveLanguageBridgeModeAsDefault:saveDefault,invalidateLanguageBridgeArtifacts:invalidate,toLanguageBridgeOwnerView:owner,seedDevelopmentData:seed,_test:{artifacts,cache,language,mode,requiredTerms,glossaryFor,photoFixture,keywordText,sections}};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.LanguageBridge=api;
})(typeof window!=='undefined'?window:globalThis);
