/* StudySpark AI Coach — browser-only prototype. All data is stored locally. */
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const DB_KEY = 'studyspark_data_v1';
const SESSION_KEY = 'studyspark_session_v1';
const GUEST_KEY = 'studyspark_guest_data_v1';
const GUEST_SESSION = '__guest__';
const FALLBACK_COURSES = ['English','Math','Biology','Chemistry','Physics','Science','History','Geography','Business','Computer Science','French','Art','Music','Health'];
const SYSTEM_FOLDER_ID = 'uncategorized';
const appData = {courses:[]};

const sampleNotes = [
  {id:'sample-bio',subject:'Biology',title:'Cell structure and function',text:'Cells are the basic unit of life. The cell membrane controls what enters and leaves the cell. The nucleus stores DNA and directs cell activities. Mitochondria release energy through cellular respiration. Ribosomes build proteins. Plant cells also have chloroplasts for photosynthesis and a rigid cell wall.',created:'Sample'},
  {id:'sample-math',subject:'Mathematics',title:'Quadratic equations',text:'A quadratic equation has the form ax squared plus bx plus c equals zero. It can be solved by factoring, completing the square, or using the quadratic formula. The discriminant b squared minus 4ac tells us how many real solutions exist. A positive discriminant gives two real solutions.',created:'Sample'},
  {id:'sample-eng',subject:'English',title:'Literary analysis essentials',text:'A strong literary analysis uses a clear thesis supported by evidence from the text. Theme is the central idea explored by a work. Tone reflects the author’s attitude, while mood is the feeling created for the reader. Explain how each quotation supports the argument instead of only summarizing it.',created:'Sample'}
];

// Build reusable multi-select course controls and folder selectors. The default available courses come from JSON; custom courses are saved per user in localStorage.
function normalizeCourseName(name=''){return name.trim().replace(/\s+/g,' ')}
function limitCourseName(name=''){return normalizeCourseName(name).slice(0,30)}
function uniqueCourses(list=[]){const seen=new Set();return list.map(limitCourseName).map(s=>s==='Mathematics'?'Math':s).filter(Boolean).filter(s=>{const key=s.toLowerCase();if(seen.has(key))return false;seen.add(key);return true})}
function customCourses(){const u=user();return uniqueCourses(u?.customCourses||[])}
function availableCourses(){return uniqueCourses([...appData.courses,...customCourses()])}
function courseExists(name,extra=[]){const key=normalizeCourseName(name).toLowerCase();return [...availableCourses(),...extra].some(c=>c.toLowerCase()===key)}
function courseButtons(name,selected=[],courses=availableCourses()){const custom=customCourses().map(c=>c.toLowerCase());return courses.map(c=>`<label class="course-chip ${custom.includes(c.toLowerCase())?'custom-chip':''}"><input type="checkbox" name="${name}" value="${escapeHTML(c)}" ${selected.includes(c)?'checked':''}><span>${escapeHTML(c)}</span></label>`).join('')}
function selectedCourses(){const u=user();return uniqueCourses(u?.courses||[]).filter(c=>availableCourses().some(a=>a.toLowerCase()===c.toLowerCase()))}
function courseOptionsHTML(courses=selectedCourses()){return courses.length?courses.map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(c)}</option>`).join(''):'<option value="" disabled selected>No courses selected — update profile</option>'}
function renderSignupCourses(){const chosen=$$('input[name="courses"]:checked').map(x=>x.value);$('#signupCourses').innerHTML=courseButtons('courses',chosen)}
async function loadCourses(){try{const res=await fetch('data/courses.json',{cache:'no-store'});if(!res.ok)throw new Error('data/courses.json not found');const data=await res.json(),list=Array.isArray(data)?data:data.courses;if(Array.isArray(list)&&list.length)appData.courses=list}catch{appData.courses=FALLBACK_COURSES;toast('Course list could not load, so fallback courses are available.')}renderSignupCourses();if(user()){renderSettings();refreshAfterCourseChange()}}
const flashControls=$('#flashSubject').parentElement;flashControls.insertBefore(Object.assign(document.createElement('select'),{id:'flashFolder'}),$('#generateCardsBtn'));
const quizControls=$('#quizSubject').parentElement;quizControls.insertBefore(Object.assign(document.createElement('select'),{id:'quizFolder'}),$('#generateQuizBtn'));
const planInput=$('#planSubject');const planPicker=document.createElement('fieldset');planPicker.className='course-picker compact';planPicker.innerHTML='<legend>Courses <small>Select one or more</small></legend><div id="planCourses" class="course-options"></div>';planInput.closest('label').replaceWith(planPicker);const planFolderLabel=document.createElement('label');planFolderLabel.innerHTML='Folder<select id="planFolder"></select>';planPicker.after(planFolderLabel);
const organizer=document.createElement('section');organizer.className='card resource-organizer';organizer.innerHTML='<div class="card-head"><div><h3>Move study resources</h3><p>Choose a new folder for cards, quizzes, or study plans.</p></div></div><div id="resourceMoveList" class="resource-move-list"></div>';$('#dashboardFolders').after(organizer);

let db = loadDB();
let currentUser = localStorage.getItem(SESSION_KEY) || null;
let guestData = loadGuestData();
let currentCards = [], cardIndex = 0;

function loadDB(){
  try{return JSON.parse(localStorage.getItem(DB_KEY)) || {users:{}}}catch{return {users:{}}}
}
function saveDB(){if(isGuestMode())localStorage.setItem(GUEST_KEY,JSON.stringify(guestData));else localStorage.setItem(DB_KEY,JSON.stringify(db))}
function user(){return isGuestMode() ? guestData : currentUser ? db.users[currentUser] : null}
function isGuestMode(){return currentUser===GUEST_SESSION}
function freshData(account){const folders=[{id:SYSTEM_FOLDER_ID,name:'Uncategorized',updated:today(),color:'#8b95aa',protected:true,parentId:''}];const notes=sampleNotes.map(n=>({...n,subject:n.subject==='Mathematics'?'Math':n.subject,folderId:SYSTEM_FOLDER_ID}));account.customCourses=uniqueCourses(account.customCourses||[]);account.courses=uniqueCourses(account.courses||account.subjects||[]);delete account.subjects;return {...account,folders,notes,flashcards:[],quizzes:[],plans:[],files:[],progress:{cardsCompleted:0,cardsKnown:0,weakTopics:[],minutes:0,streak:1,lastStudy:today()},activity:[{type:'note',text:'Sample study library added',time:'Just now'}]}}
function freshGuestData(){return {name:'Guest Student',grade:'Guest Mode',email:null,courses:[],customCourses:[],folders:[{id:SYSTEM_FOLDER_ID,name:'Uncategorized',updated:today(),color:'#8b95aa',protected:true,parentId:''}],notes:[],files:[],flashcards:[],quizzes:[],plans:[],progress:{cardsCompleted:0,cardsKnown:0,weakTopics:[],minutes:0,streak:1,lastStudy:today()},activity:[]}}
function loadGuestData(){try{return normalizeGuestData(JSON.parse(localStorage.getItem(GUEST_KEY)))}catch{return freshGuestData()}}
function normalizeGuestData(data){return data&&typeof data==='object'?{...freshGuestData(),...data,name:'Guest Student',grade:'Guest Mode',email:null}:freshGuestData()}
function isLegacySampleFolder(f){const names=[['Biology','Unit','1'].join(' '),['Math','Exam','Review'].join(' '),['English','Essays'].join(' ')],ids=['folder-biology','folder-math','folder-english','bio-unit-1','math-review','english-essays','f-bio','f-math','f-english'];return names.includes(f.name)||ids.includes(f.id)}
function migrateUser(u){u.customCourses=uniqueCourses(u.customCourses||[]);u.courses=uniqueCourses([...(u.courses||[]),...(u.subjects||[])]);u.courses.forEach(c=>{if(!appData.courses.some(d=>d.toLowerCase()===c.toLowerCase())&&!u.customCourses.some(x=>x.toLowerCase()===c.toLowerCase()))u.customCourses.push(c)});u.customCourses=uniqueCourses(u.customCourses);delete u.subjects;u.folders=u.folders||[];const legacyFolderIds=u.folders.filter(isLegacySampleFolder).map(f=>f.id);let unc=u.folders.find(f=>f.id===SYSTEM_FOLDER_ID||f.name==='Uncategorized');if(!unc){unc={id:SYSTEM_FOLDER_ID,name:'Uncategorized',updated:today(),color:'#8b95aa',protected:true,parentId:''};u.folders.unshift(unc)}else Object.assign(unc,{id:SYSTEM_FOLDER_ID,name:'Uncategorized',protected:true,parentId:''});u.folders=u.folders.filter(f=>(f.id===SYSTEM_FOLDER_ID||!f.protected)&&!legacyFolderIds.includes(f.id)).map((f,i)=>({...f,color:f.color||['#5867e8','#8b6ddd','#40a77e','#dd8b51'][i%4],parentId:f.protected?'':f.parentId||''}));u.notes=(u.notes||[]).map(n=>({...n,subject:n.subject==='Mathematics'?'Math':n.subject,folderId:legacyFolderIds.includes(n.folderId)?SYSTEM_FOLDER_ID:normalizeFolderId(n.folderId)}));u.flashcards=(u.flashcards||[]).map(c=>({...c,folderId:legacyFolderIds.includes(c.folderId)?SYSTEM_FOLDER_ID:normalizeFolderId(c.folderId)}));u.quizzes=(u.quizzes||[]).map(q=>({...q,folderId:legacyFolderIds.includes(q.folderId)?SYSTEM_FOLDER_ID:normalizeFolderId(q.folderId)}));u.plans=(u.plans||[]).map(p=>({...p,courses:p.courses||[p.subject].filter(Boolean),folderId:legacyFolderIds.includes(p.folderId)?SYSTEM_FOLDER_ID:normalizeFolderId(p.folderId)}));u.files=(u.files||[]).map(f=>({...f,folderId:legacyFolderIds.includes(f.folderId)?SYSTEM_FOLDER_ID:normalizeFolderId(f.folderId)}));saveDB()}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function escapeHTML(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function recordActivity(type,text){const u=user();u.activity.unshift({type,text,time:'Just now'});u.activity=u.activity.slice(0,12);touchStudy();saveDB()}
function touchStudy(){const p=user().progress;if(p.lastStudy!==today()){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);p.streak=p.lastStudy===yesterday?p.streak+1:1;p.lastStudy=today()}}

/* Authentication */
function openAuth(mode='signup'){$('#authModal').classList.add('open');$('#authModal').setAttribute('aria-hidden','false');switchAuth(mode)}
function closeAuth(){$('#authModal').classList.remove('open');$('#authModal').setAttribute('aria-hidden','true')}
function switchAuth(mode){$$('.auth-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===mode));$('#signupForm').classList.toggle('hidden',mode!=='signup');$('#loginForm').classList.toggle('hidden',mode!=='login');$('#authTitle').textContent=mode==='signup'?'Create your account':'Welcome back';$('#authSubtitle').textContent=mode==='signup'?'Start studying smarter today. It is free.':'Pick up right where you left off.'}
function confirmDialog({title='Confirm action',message='',okText='Continue',cancelText='Cancel',danger=false}){return new Promise(resolve=>{const modal=$('#confirmModal'),ok=$('#confirmOk'),cancel=$('#confirmCancel');$('#confirmTitle').textContent=title;$('#confirmMessage').textContent=message;ok.textContent=okText;cancel.textContent=cancelText;ok.className='btn '+(danger?'btn-danger':'btn-primary');modal.classList.add('open');modal.setAttribute('aria-hidden','false');const done=value=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');ok.onclick=cancel.onclick=null;resolve(value)};ok.onclick=()=>done(true);cancel.onclick=()=>done(false)})}
$$('[data-auth]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();openAuth(btn.dataset.auth)}));
$$('[data-guest]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();enterGuestMode()}));
$$('[data-close]').forEach(btn=>btn.addEventListener('click',closeAuth));
$$('.auth-tabs button').forEach(btn=>btn.addEventListener('click',()=>switchAuth(btn.dataset.tab)));
$('#authModal').addEventListener('click',e=>{if(e.target===$('#authModal'))closeAuth()});
$('#signupForm').addEventListener('submit',async e=>{e.preventDefault();const wasGuest=isGuestMode(),guestSnapshot=wasGuest?cloneData(user()):null,fd=new FormData(e.target),email=fd.get('email').trim().toLowerCase(),courses=fd.getAll('courses');if(!courses.length&&!wasGuest)return toast('Choose at least one course.');if(db.users[email])return toast('An account with that email already exists.');db.users[email]=freshData({name:fd.get('name').trim(),email,password:fd.get('password'),grade:fd.get('grade'),courses});currentUser=null;localStorage.removeItem(SESSION_KEY);localStorage.setItem(DB_KEY,JSON.stringify(db));logIn(email);toast('Your StudySpark account is ready.');if(wasGuest&&guestSnapshot){const move=await confirmDialog({title:'Move guest data?',message:'Do you want to move your guest data into this account?',okText:'Move Guest Data',cancelText:'Start Fresh'});if(move){moveGuestDataToAccount(guestSnapshot,user());saveDB();renderAll();const clear=await confirmDialog({title:'Guest data moved',message:'Do you want to clear the separate Guest Mode data from this browser?',okText:'Clear Guest Data',cancelText:'Keep Guest Data',danger:true});if(clear){guestData=freshGuestData();localStorage.setItem(GUEST_KEY,JSON.stringify(guestData))}toast('Guest data moved into your account.')}}});
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),email=fd.get('email').trim().toLowerCase();if(!db.users[email]||db.users[email].password!==fd.get('password'))return toast('Email or password not found.');logIn(email);toast('Welcome back!');});
function logIn(email){currentUser=email;migrateUser(user());localStorage.setItem(SESSION_KEY,email);closeAuth();$('#landing').classList.remove('active');$('#publicNav').classList.add('hidden');$('#app').classList.remove('hidden');renderAll();showView('dashboard')}
function enterGuestMode(){guestData=loadGuestData();currentUser=GUEST_SESSION;migrateUser(user());localStorage.setItem(SESSION_KEY,GUEST_SESSION);closeAuth();$('#landing').classList.remove('active');$('#publicNav').classList.add('hidden');$('#app').classList.remove('hidden');renderAll();showView('dashboard');toast('Continuing as Guest Student.')}
async function logOut(){if(isGuestMode()){const exit=await confirmDialog({title:'Exit Guest Mode',message:'Do you want to exit guest mode?',okText:'Exit Guest Mode',cancelText:'Cancel'});if(!exit)return}else toast('You are logged out.');localStorage.removeItem(SESSION_KEY);currentUser=null;$('#app').classList.add('hidden');$('#landing').classList.add('active');$('#publicNav').classList.remove('hidden')}
function cloneData(value){return JSON.parse(JSON.stringify(value))}
function moveGuestDataToAccount(source,target){['courses','customCourses','folders','notes','files','flashcards','quizzes','plans','activity'].forEach(k=>{target[k]=cloneData(source[k]||[])});target.progress=cloneData(source.progress||freshGuestData().progress)}
$('#logoutBtn').addEventListener('click',logOut);
/* Navigation */
const viewNames={dashboard:['OVERVIEW','Dashboard'],notes:['STUDY','My Notes'],coach:['STUDY','AI Study Coach'],flashcards:['STUDY','Flashcards'],quiz:['STUDY','Quiz Generator'],planner:['STUDY','Study Planner'],progress:['INSIGHTS','Progress Tracker'],instructions:['HELP','How it works'],settings:['ACCOUNT','Account Settings']};
function showView(view){$$('.app-view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view&&b.closest('#appNav')));$('#breadcrumb').textContent=viewNames[view][0];$('#viewTitle').textContent=viewNames[view][1];$('.sidebar').classList.remove('open');if(view==='progress')renderProgress();if(view==='dashboard')renderDashboard();if(view==='settings')renderSettings();window.scrollTo(0,0)}
$$('[data-view]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));
document.addEventListener('click',e=>{const btn=e.target.closest('.open-settings-btn');if(btn)showView('settings')});
$('#menuBtn').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
$$('[data-premium]').forEach(b=>b.addEventListener('click',()=>$('#premiumModal').classList.add('open')));$$('[data-premium-close]').forEach(b=>b.addEventListener('click',()=>$('#premiumModal').classList.remove('open')));

function courseSettingsButton(){return '<button class="btn btn-secondary open-settings-btn" data-view="settings" type="button">Open Account Settings</button>'}
function courseEmptyMessage(){return '<div class="course-empty-message">No courses selected. Go to Account Settings to choose your courses. '+courseSettingsButton()+'</div>'}
function bindSettingsShortcuts(){$$('[data-view="settings"]').forEach(btn=>btn.onclick=()=>showView('settings'))}
function renderSettings(){const u=user();if(!u)return;const guest=isGuestMode();$('#settingsName').value=u.name||'';$('#settingsEmail').value=u.email||'';$('#settingsGrade').value=u.grade||'Grade 9';$('#settingsName').disabled=guest;$('#settingsEmail').disabled=guest;$('#settingsEmail').required=!guest;$('#settingsGrade').disabled=guest;$('#saveProfileBtn')?.classList.toggle('hidden',guest);$('#clearGuestDataBtn')?.classList.toggle('hidden',!guest);$('#profileHelp').textContent=guest?'Guest profile details are fixed. Course choices and custom courses still save on this browser.':'Your account details are saved in this browser.';$('#settingsCourses').innerHTML=appData.courses.length?courseButtons('settingsCourses',selectedCourses(),appData.courses):'<div class="empty-mini">Course list is loading. If it stays empty, fallback courses will be available.</div>';renderCustomCourseList();bindCustomCourseActions()}
function refreshAfterCourseChange(){updateSubjectSelects();renderDashboard();renderNotes();renderOrganization();renderProgress();renderSettings();bindSettingsShortcuts()}
function renderCustomCourseList(){const selected=selectedCourses(),courses=customCourses();$('#customCourseList').innerHTML=courses.length?courses.map(c=>`<div class="custom-course-row" data-custom-row="${escapeHTML(c)}"><div class="custom-course-view"><label class="course-chip custom-chip"><input type="checkbox" name="settingsCourses" value="${escapeHTML(c)}" ${selected.includes(c)?'checked':''}><span>${escapeHTML(c)}</span></label><div><button type="button" data-custom-rename="${escapeHTML(c)}">Rename</button><button type="button" data-custom-delete="${escapeHTML(c)}">Delete</button></div></div><div class="custom-course-edit hidden"><input data-custom-edit-input maxlength="30" value="${escapeHTML(c)}"><button type="button" data-custom-save="${escapeHTML(c)}">Save</button><button type="button" data-custom-cancel>Cancel</button></div></div>`).join(''):'<div class="empty-mini">No custom courses yet.</div>'}
function addCustomCourse(){const input=$('#customCourseName'),name=normalizeCourseName(input.value);if(!name)return toast('Enter a course name.');if(name.length>30)return toast('Custom course names must be 30 characters or less.');if(courseExists(name))return toast('That course already exists.');const u=user();u.customCourses=uniqueCourses([...(u.customCourses||[]),name]);u.courses=uniqueCourses([...(u.courses||[]),name]);input.value='';$('#customCourseForm').classList.add('hidden');saveDB();refreshAfterCourseChange();toast('Custom course added.')}
function renameCustomCourse(btn){const row=btn.closest('.custom-course-row');$('.custom-course-view',row).classList.add('hidden');$('.custom-course-edit',row).classList.remove('hidden');$('[data-custom-edit-input]',row).focus()}
function saveCustomCourseRename(btn,oldName){const row=btn.closest('.custom-course-row'),current=customCourses().find(c=>c.toLowerCase()===oldName.toLowerCase()),next=normalizeCourseName($('[data-custom-edit-input]',row).value);if(!current)return;if(!next)return toast('Enter a course name.');if(next===current)return renderSettings();if(next.length>30)return toast('Custom course names must be 30 characters or less.');if(courseExists(next,customCourses().filter(c=>c.toLowerCase()!==current.toLowerCase())))return toast('That course already exists.');const u=user(),same=x=>x.toLowerCase()===current.toLowerCase();u.customCourses=uniqueCourses(u.customCourses.map(c=>same(c)?next:c));u.courses=uniqueCourses(u.courses.map(c=>same(c)?next:c));u.notes.forEach(n=>{if(same(n.subject))n.subject=next});u.flashcards.forEach(c=>{if(same(c.subject))c.subject=next});u.quizzes.forEach(q=>{if(same(q.subject))q.subject=next});u.plans.forEach(p=>{if(same(p.subject))p.subject=next;p.courses=(p.courses||[]).map(c=>same(c)?next:c)});saveDB();refreshAfterCourseChange();toast('Custom course renamed.')}
function deleteCustomCourse(name){const current=customCourses().find(c=>c.toLowerCase()===name.toLowerCase());if(!current)return;const u=user(),same=x=>x.toLowerCase()===current.toLowerCase();u.customCourses=uniqueCourses(u.customCourses.filter(c=>!same(c)));u.courses=uniqueCourses(u.courses.filter(c=>!same(c)));saveDB();refreshAfterCourseChange();toast('Custom course deleted.')}
function bindCustomCourseActions(){$$('[data-custom-rename]').forEach(b=>b.onclick=()=>renameCustomCourse(b));$$('[data-custom-save]').forEach(b=>b.onclick=()=>saveCustomCourseRename(b,b.dataset.customSave));$$('[data-custom-cancel]').forEach(b=>b.onclick=()=>renderSettings());$$('[data-custom-delete]').forEach(b=>b.onclick=()=>deleteCustomCourse(b.dataset.customDelete));$$('[data-custom-edit-input]').forEach(i=>i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();saveCustomCourseRename(i.closest('.custom-course-row').querySelector('[data-custom-save]'),i.closest('.custom-course-row').dataset.customRow)}})}
$('#profileForm').addEventListener('submit',e=>{e.preventDefault();if(isGuestMode())return toast('Guest profile details are fixed.');const u=user(),oldEmail=currentUser,newEmail=$('#settingsEmail').value.trim().toLowerCase();if(!newEmail)return toast('Add an email address.');if(newEmail!==oldEmail&&db.users[newEmail])return toast('Another account already uses that email.');u.name=$('#settingsName').value.trim()||u.name;u.email=newEmail;u.grade=$('#settingsGrade').value;if(newEmail!==oldEmail){db.users[newEmail]=u;delete db.users[oldEmail];currentUser=newEmail;localStorage.setItem(SESSION_KEY,newEmail)}saveDB();renderAll();showView('settings');toast('Profile updated.')});
$('#coursesForm').addEventListener('submit',e=>{e.preventDefault();user().courses=$$('input[name="settingsCourses"]:checked').map(x=>x.value);delete user().subjects;saveDB();refreshAfterCourseChange();toast('Courses saved. Dropdowns updated.')});
$('#clearGuestDataBtn')?.addEventListener('click',async()=>{if(!isGuestMode())return;const clear=await confirmDialog({title:'Clear Guest Data',message:'This will delete all guest notes, folders, quizzes, flashcards, plans, and progress.',okText:'Clear Guest Data',cancelText:'Cancel',danger:true});if(!clear)return;guestData=freshGuestData();localStorage.setItem(GUEST_KEY,JSON.stringify(guestData));renderAll();showView('settings');toast('Guest data cleared.')});
$('#showCustomCourseBtn').addEventListener('click',()=>{$('#customCourseForm').classList.toggle('hidden');$('#customCourseName').focus()});
$('#addCustomCourseBtn').addEventListener('click',addCustomCourse);
$('#customCourseName').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCustomCourse()}});

/* Folder organization. Every study item stores a folderId in localStorage. */
function folderById(id){return user().folders.find(f=>f.id===id)}
function uncategorized(){return folderById(SYSTEM_FOLDER_ID)}
function visibleFolders(){return user().folders.filter(f=>!f.protected)}
function normalizeFolderId(id){return folderById(id)&&!folderById(id).protected?id:SYSTEM_FOLDER_ID}
function folderOptions(){const options=visibleFolders().map(f=>`<option value="${f.id}">${escapeHTML(f.name)}</option>`).join('');return '<option value="">No folder</option>'+options}
function displayFolderName(id){const f=folderById(id);return f&&!f.protected?f.name:'No folder'}
function touchFolder(id){const f=folderById(id);if(f)f.updated=today()}
function openFolderModal(id=''){const f=folderById(id);if(f?.protected)return toast('That system folder cannot be renamed.');$('#folderEditId').value=id;$('#folderName').value=f?.name||'';$('#folderModalTitle').textContent=f?'Rename folder':'Create a folder';$('#folderModal').classList.add('open');$('#folderName').focus()}
function closeFolderModal(){$('#folderModal').classList.remove('open')}
function folderDescendants(id){const found=[];const walk=parent=>user().folders.filter(f=>f.parentId===parent).forEach(f=>{found.push(f.id);walk(f.id)});walk(id);return found}
function openDeleteFolder(id){const f=folderById(id);if(!f||f.protected)return toast('That system folder cannot be deleted.');$('#deleteFolderId').value=id;$('input[name="deleteMode"][value="folder"]').checked=true;$('#deleteFolderModal').classList.add('open')}
function closeDeleteFolder(){$('#deleteFolderModal').classList.remove('open')}
function deleteFolder(){const id=$('#deleteFolderId').value,f=folderById(id),mode=$('input[name="deleteMode"]:checked').value;if(!f||f.protected)return;const ids=[id,...folderDescendants(id)],keys=['notes','flashcards','quizzes','plans','files'];if(mode==='all')keys.forEach(k=>user()[k]=user()[k].filter(x=>!ids.includes(x.folderId)));else keys.forEach(k=>user()[k].forEach(x=>{if(ids.includes(x.folderId))x.folderId=SYSTEM_FOLDER_ID}));user().folders=user().folders.filter(x=>!ids.includes(x.id));if(mode==='folder')touchFolder(SYSTEM_FOLDER_ID);saveDB();closeDeleteFolder();renderAll();toast(mode==='all'?'Folder and all contents permanently deleted.':'Folder deleted; contents moved to No folder.')}
function moveFolder(id,parentId){const f=folderById(id);if(!f||f.protected||id===parentId||folderDescendants(id).includes(parentId))return toast('That folder cannot be moved there.');f.parentId=parentId;touchFolder(id);saveDB();renderAll();toast(parentId?'Folder moved.':'Folder moved to the top level.')}
function changeFolderColor(id,color){const f=folderById(id);if(!f)return;f.color=color;touchFolder(id);saveDB();renderAll()}
$('#sidebarNewFolder').onclick=()=>openFolderModal();$('#dashboardNewFolder').onclick=()=>openFolderModal();$('#folderModalClose').onclick=closeFolderModal;$('#cancelDeleteFolder').onclick=closeDeleteFolder;$('#confirmDeleteFolder').onclick=deleteFolder;$('#folderForm').onsubmit=e=>{e.preventDefault();const name=$('#folderName').value.trim(),id=$('#folderEditId').value;if(!name)return;if(id){const f=folderById(id);if(f.protected)return toast('That system folder cannot be renamed.');f.name=name;f.updated=today()}else user().folders.unshift({id:'f'+Date.now(),name,updated:today(),color:'#5867e8',parentId:''});saveDB();closeFolderModal();renderAll();toast(id?'Folder renamed.':'Folder created.')};
function folderStats(id){const u=user();return {notes:u.notes.filter(x=>x.folderId===id).length,cards:u.flashcards.filter(x=>x.folderId===id).length,quizzes:u.quizzes.filter(x=>x.folderId===id).length,plans:u.plans.filter(x=>x.folderId===id).length,files:u.files.filter(x=>x.folderId===id).length}}
function folderMenuHTML(f,menuId,parentChoices){return `<div class="folder-menu" data-folder-dropdown="${menuId}"><button type="button" data-folder-edit="${f.id}">Rename Folder</button><div class="menu-section"><span>Change Folder Color</span><div class="color-options">${['#5867e8','#8b6ddd','#40a77e','#dd8b51','#d65e72','#4b9bc2'].map(c=>`<button type="button" data-folder-color="${f.id}" data-color="${c}" style="--swatch:${c}" aria-label="Use color ${c}"></button>`).join('')}</div></div><label class="move-folder-label">Move Folder<select data-folder-move="${f.id}">${parentChoices(f.id)}</select></label><button type="button" class="danger-menu-item" data-folder-delete="${f.id}">Delete Folder</button></div>`}
function renderOrganization(){
  const u=user(),folderFilter=$('#dashboardFolderFilter').value,courseFilter=$('#dashboardCourseFilter').value;
  const userFolders=visibleFolders(),safeFolderFilter=userFolders.some(f=>f.id===folderFilter)?folderFilter:'';
  $('#dashboardFolderFilter').innerHTML='<option value="">All folders</option>'+userFolders.map(f=>`<option value="${f.id}" ${f.id===safeFolderFilter?'selected':''}>${escapeHTML(f.name)}</option>`).join('');
  const courses=selectedCourses();
  $('#dashboardCourseFilter').innerHTML='<option value="">All courses</option>'+courses.map(s=>`<option ${s===courseFilter?'selected':''}>${escapeHTML(s)}</option>`).join('');
  $('#courseCards').innerHTML=courses.length?courses.filter(s=>!courseFilter||s===courseFilter).map((s,i)=>{const notes=u.notes.filter(n=>n.subject===s&&(!safeFolderFilter||n.folderId===safeFolderFilter)).length,quizzes=u.quizzes.filter(q=>q.subject===s&&(!safeFolderFilter||q.folderId===safeFolderFilter)).length;return `<article class="course-card"><span class="q-icon ${['blue','lavender','mint','peach'][i%4]}">${escapeHTML(s[0])}</span><div><b>${escapeHTML(s)}</b><small>${notes} notes · ${quizzes} quizzes</small></div><strong>${subjectScore(s)}%</strong></article>`}).join('')||'<div class="empty-mini">No courses match these filters.</div>':courseEmptyMessage();
  const parentChoices=id=>'<option value="">Top level</option>'+u.folders.filter(x=>x.id!==id&&!x.protected&&!folderDescendants(id).includes(x.id)).map(x=>`<option value="${x.id}">${escapeHTML(x.name)}</option>`).join('');
  $('#dashboardFolders').innerHTML=userFolders.length?userFolders.map(f=>{const s=folderStats(f.id);return `<article class="folder-card" data-folder-card="${f.id}" style="--folder-color:${f.color}"><div class="folder-card-top"><span class="folder-symbol">F</span><div><b>${escapeHTML(f.name)}</b><small>Updated ${escapeHTML(f.updated||today())}</small></div><button type="button" class="folder-menu-button" data-folder-menu="${f.id}" aria-label="Manage ${escapeHTML(f.name)}" title="Manage folder">⋮</button></div><div class="folder-counts"><span><b>${s.notes}</b> notes</span><span><b>${s.cards}</b> cards</span><span><b>${s.quizzes}</b> quizzes</span><span><b>${s.plans}</b> plans</span></div>${folderMenuHTML(f,f.id,parentChoices)}</article>`}).join(''):'<div class="empty-mini">You don&rsquo;t have any folders yet. Create your first folder to organize your study materials.</div>';
  $('#sidebarFolderList').innerHTML=userFolders.map(f=>`<div class="sidebar-folder-wrap" style="--folder-color:${f.color};padding-left:${f.parentId?'10px':'0'}"><button type="button" class="sidebar-folder" data-folder-open="${f.id}"><span>□</span>${escapeHTML(f.name)}<small>${folderStats(f.id).notes}</small></button><button type="button" class="sidebar-folder-menu" data-folder-menu="sidebar-${f.id}" aria-label="Manage ${escapeHTML(f.name)}" title="Manage folder">⋮</button>${folderMenuHTML(f,`sidebar-${f.id}`,parentChoices)}</div>`).join('');
  $$('[data-folder-menu]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const menu=$(`[data-folder-dropdown="${b.dataset.folderMenu}"]`);$$('.folder-menu').forEach(m=>{if(m!==menu)m.classList.remove('open')});menu?.classList.toggle('open')});
  $$('.folder-menu').forEach(menu=>menu.onclick=e=>e.stopPropagation());
  $$('[data-folder-card]').forEach(c=>{c.onclick=()=>openFolder(c.dataset.folderCard);c.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();$(`[data-folder-dropdown="${c.dataset.folderCard}"]`)?.classList.add('open')}});
  $$('[data-folder-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openFolderModal(b.dataset.folderEdit)});$$('[data-folder-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();openDeleteFolder(b.dataset.folderDelete)});$$('[data-folder-color]').forEach(b=>b.onclick=e=>{e.stopPropagation();changeFolderColor(b.dataset.folderColor,b.dataset.color)});$$('[data-folder-move]').forEach(s=>{s.value=folderById(s.dataset.folderMove)?.parentId||'';s.onclick=e=>e.stopPropagation();s.onchange=e=>{e.stopPropagation();moveFolder(s.dataset.folderMove,s.value)}});$$('[data-folder-open]').forEach(b=>b.onclick=()=>openFolder(b.dataset.folderOpen));
}
function openFolder(id){$('#noteFolderFilter').value=id;showView('notes');renderNotes()}
$('#dashboardFolderFilter').onchange=renderOrganization;$('#dashboardCourseFilter').onchange=renderOrganization;
document.addEventListener('click',e=>{if(!e.target.closest('.folder-menu')&&!e.target.closest('[data-folder-menu]'))$$('.folder-menu').forEach(m=>m.classList.remove('open'))});
function renderResourceMoves(){const u=user(),rows=[...u.flashcards.map((x,i)=>({kind:'flashcards',i,label:`Flashcard · ${x.subject}: ${x.question.slice(0,38)}`})),...u.quizzes.map((x,i)=>({kind:'quizzes',i,label:`Quiz · ${x.subject} (${x.score}%)`})),...u.plans.map((x,i)=>({kind:'plans',i,label:`Plan · ${(x.courses||[x.subject]).join(' + ')}`}))];$('#resourceMoveList').innerHTML=rows.length?rows.slice(-15).map(r=>{const item=u[r.kind][r.i];return `<div class="resource-move-row"><span class="pill blue-pill">${r.kind==='flashcards'?'CARD':r.kind==='quizzes'?'QUIZ':'PLAN'}</span><b>${escapeHTML(r.label)}</b><select data-move-kind="${r.kind}" data-move-index="${r.i}">${folderOptions()}</select></div>`}).join(''):'<div class="empty-mini">Generate cards, quizzes, or plans to organize them here.</div>';$$('[data-move-kind]').forEach(s=>{const item=u[s.dataset.moveKind][Number(s.dataset.moveIndex)];s.value=folderById(item.folderId)&&!folderById(item.folderId).protected?item.folderId:'';s.onchange=()=>{item.folderId=normalizeFolderId(s.value);touchFolder(item.folderId);saveDB();renderOrganization();toast('Study resource moved.')}})}

function renderAll(){const u=user();if(!u)return;const first=u.name.split(' ')[0],initial=isGuestMode()?'G':u.name[0].toUpperCase();$('#sideName').textContent=u.name;$('#sideGrade').textContent=u.grade;$('#sideAvatar').textContent=$('#topAvatar').textContent=initial;$('#logoutBtn').textContent=isGuestMode()?'Exit Guest Mode':'↪';$('#logoutBtn').title=isGuestMode()?'Exit Guest Mode':'Log out';$('#welcomeName').textContent=first;$('#todayDate').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});$('#guestBanner')?.classList.toggle('hidden',!isGuestMode());updateSubjectSelects();renderDashboard();renderNotes();renderOrganization();renderResourceMoves();renderProgress();setMinDate()}
function renderDashboard(){const u=user();if(!u)return;const p=u.progress,goal=Math.min(100,Math.round(p.minutes/45*100));$('#goalPercent').textContent=goal+'%';$('#goalBar').style.width=goal+'%';$('#goalRing').style.background=`conic-gradient(var(--blue) ${goal}%,#edf0f7 0)`;$('#timeStudied').textContent=`${Math.min(p.minutes,45)} of 45 min`;$('#streakCount').textContent=p.streak;const days=['M','T','W','T','F','S','S'],jsDay=new Date().getDay(),todayIndex=jsDay===0?6:jsDay-1;$('#weekRow').innerHTML=days.map((d,i)=>`<div class="day ${i<=todayIndex?'done':''} ${i===todayIndex?'today':''}"><i>${i<=todayIndex?'✓':i+1}</i><span>${d}</span></div>`).join('');const subjects=getSubjects();$('#subjectList').innerHTML=subjects.length?subjects.slice(0,4).map((s,i)=>`<div class="subject-row"><span class="subject-dot" style="background:${['#5867e8','#8b6ddd','#40a77e','#dd8b51'][i%4]}"></span><div><b>${escapeHTML(s)}</b><small>${u.notes.filter(n=>n.subject===s).length} saved note(s)</small></div><span>${subjectScore(s)}%</span></div>`).join(''):courseEmptyMessage();$('#activityList').innerHTML=u.activity.slice(0,4).map(a=>`<div class="activity-row"><span class="q-icon ${a.type==='quiz'?'mint':a.type==='card'?'lavender':'blue'}">${a.type[0].toUpperCase()}</span><div><b>${escapeHTML(a.text)}</b><small>${a.type==='quiz'?'Quiz result':a.type==='card'?'Flashcard review':'Study library'}</small></div><span class="activity-time">${a.time}</span></div>`).join('')}
function getSubjects(){return [...new Set([...selectedCourses(),...user().notes.map(n=>n.subject)])].filter(Boolean)}
function subjectScore(subject){const notes=user().notes.filter(n=>n.subject===subject).length,q=user().quizzes.filter(x=>x.subject===subject);return Math.min(100,Math.round(notes*12+(q.length?q.reduce((a,b)=>a+b.score,0)/q.length*.5:10)))}

/* Notes and simulated analysis */
$('#newNoteBtn').addEventListener('click',()=>{$('#noteComposer').classList.remove('hidden');$('#noteTitle').focus()});$('#closeComposer').addEventListener('click',()=>$('#noteComposer').classList.add('hidden'));$('#noteText').addEventListener('input',e=>$('#wordCount').textContent=(e.target.value.trim().split(/\s+/).filter(Boolean).length)+' words');
function noteFromForm(){const title=$('#noteTitle').value.trim(),text=$('#noteText').value.trim(),subject=$('#noteSubject').value,folderId=normalizeFolderId($('#noteFolder').value);if(!subject)return toast('Choose a course before saving notes.'),null;if(!title||!text){toast('Add a title and some notes first.');return null}touchFolder(folderId);return {id:'n'+Date.now(),subject,folderId,title,text,created:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})}}
function saveNote(analyze=false){const note=noteFromForm();if(!note)return;user().notes.unshift(note);recordActivity('note',`Saved ${note.subject} notes`);clearNoteForm();renderNotes();updateSubjectSelects();if(analyze)showAnalysis(note);toast(analyze?'Notes saved and analyzed.':'Notes saved.')}
$('#saveNoteBtn').addEventListener('click',()=>saveNote(false));$('#analyzeNoteBtn').addEventListener('click',()=>saveNote(true));
function clearNoteForm(){$('#noteTitle').value='';$('#noteText').value='';$('#wordCount').textContent='0 words'}
const stopWords=new Set('the a an and or but is are was were be been being in on at to for from of with by as it this that these those they their them we you your can has have had into through also what which when where how'.split(' '));
function keywords(text){const counts={};(text.toLowerCase().match(/[a-z]{4,}/g)||[]).forEach(w=>{if(!stopWords.has(w))counts[w]=(counts[w]||0)+1});return Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,7).map(x=>x[0])}
function summarize(text){const sentences=text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[text];return sentences.slice(0,2).join(' ').trim()}
function showAnalysis(note){const keys=keywords(note.text);$('#analysisResult').innerHTML=`<span class="pill purple-pill">NOTES ANALYSIS</span><h3>${escapeHTML(note.title)}</h3><p><b>Quick summary:</b> ${escapeHTML(summarize(note.text))}</p><div class="keyword-list">${keys.map(k=>`<span class="keyword">${escapeHTML(k)}</span>`).join('')}</div>`;$('#analysisResult').classList.remove('hidden')}
function renderNotes(){const u=user();if(!u)return;const filter=$('#noteFilter').value,folderFilter=$('#noteFolderFilter').value,userFolders=visibleFolders(),safeFolderFilter=userFolders.some(f=>f.id===folderFilter)?folderFilter:'';let notes=u.notes.filter(n=>(!filter||filter==='All subjects'||n.subject===filter)&&(!safeFolderFilter||n.folderId===safeFolderFilter));$('#noteCountLabel').textContent=`${notes.length} of ${u.notes.length} notes`;$('#notesGrid').innerHTML=notes.map(n=>`<article class="card note-card"><span class="note-subject">${escapeHTML(n.subject.toUpperCase())}</span><span class="note-folder-name">${escapeHTML(displayFolderName(n.folderId))}</span><h3>${escapeHTML(n.title)}</h3><p>${escapeHTML(n.text)}</p><select class="move-select" data-move-note="${n.id}" aria-label="Move ${escapeHTML(n.title)} to folder">${folderOptions()}</select><div class="note-footer"><span>${n.created}</span><span><button class="delete-note" data-analyze="${n.id}">Analyze</button><button class="delete-note" data-delete="${n.id}" aria-label="Delete note">Delete</button></span></div></article>`).join('')||'<div class="empty-state card"><h2>No notes here yet</h2><p>Add your first set of class notes above.</p></div>';const subjects=getSubjects();$('#noteFilter').innerHTML='<option>All subjects</option>'+subjects.map(s=>`<option ${s===filter?'selected':''}>${escapeHTML(s)}</option>`).join('');$('#noteFolderFilter').innerHTML='<option value="">All folders</option>'+userFolders.map(f=>`<option value="${f.id}" ${f.id===safeFolderFilter?'selected':''}>${escapeHTML(f.name)}</option>`).join('');$$('[data-move-note]').forEach(s=>{const n=u.notes.find(n=>n.id===s.dataset.moveNote);s.value=folderById(n.folderId)&&!folderById(n.folderId).protected?n.folderId:'';s.onchange=()=>{n.folderId=normalizeFolderId(s.value);touchFolder(n.folderId);saveDB();renderAll();toast('Note moved.')}});$$('[data-delete]').forEach(b=>b.onclick=()=>{u.notes=u.notes.filter(n=>n.id!==b.dataset.delete);saveDB();renderAll();toast('Note deleted.')} );$$('[data-analyze]').forEach(b=>b.onclick=()=>showAnalysis(u.notes.find(n=>n.id===b.dataset.analyze)))}
$('#noteFilter').addEventListener('change',renderNotes);$('#noteFolderFilter').addEventListener('change',renderNotes);

/* Simulated AI coach. Replace mockCoachReply with a fetch call to a real AI API later. */
function mockCoachReply(q){q=q.toLowerCase();if(q.includes('biology'))return 'Use active recall: sketch the process or structure from memory, label it, then compare it with your notes. Follow with five flashcards and a short quiz. Spend extra time explaining “why,” not only naming parts.';if(q.includes('before')||q.includes('test'))return 'Start with a quick brain dump of everything you remember. Check it against your notes, mark the gaps, then review those weak areas with flashcards. Finish with a timed quiz and explain every missed answer aloud.';if(q.includes('procrast'))return 'Make the first step tiny: set a 10-minute timer and open one note. Put your phone out of reach, choose one specific outcome, and stop after 10 minutes if you want. Starting is the real assignment.';if(q.includes('math'))return 'For math, spend less time rereading and more time solving. Work one example with notes, one without notes, then one mixed problem. Keep an error log that names exactly where each mistake happened.';return 'Try a three-part session: 10 minutes recalling what you know, 20 minutes practicing the hardest idea, and 5 minutes writing what to review next. Active recall will give you more useful feedback than rereading.'}
function sendCoach(q){const box=$('#chatMessages');box.insertAdjacentHTML('beforeend',`<div class="message user"><div><b>You</b><p>${escapeHTML(q)}</p></div></div>`);setTimeout(()=>{box.insertAdjacentHTML('beforeend',`<div class="message ai"><span class="bot-avatar">S</span><div><b>StudySpark Coach</b><p>${escapeHTML(mockCoachReply(q))}</p></div></div>`);box.scrollTop=box.scrollHeight},350);box.scrollTop=box.scrollHeight}
$('#coachForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#coachInput').value.trim();if(q){sendCoach(q);e.target.reset()}});$$('.suggestions button').forEach(b=>b.addEventListener('click',()=>sendCoach(b.textContent)));

function updateSubjectSelects(){if(!user())return;const courses=selectedCourses(),options=courseOptionsHTML(courses),folders=folderOptions(),empty=!courses.length;$$('.course-empty-message').forEach(x=>x.remove());$('#noteSubject').innerHTML=options;$('#flashSubject').innerHTML=options;$('#quizSubject').innerHTML=options;['#fileSubject','#uploadSubject'].forEach(id=>{if($(id))$(id).innerHTML=options});$('#noteFolder').innerHTML=folders;$('#flashFolder').innerHTML=folders;$('#quizFolder').innerHTML=folders;$('#planFolder').innerHTML=folders;$('#planCourses').innerHTML=courses.length?courseButtons('planCourses',[],courses):courseEmptyMessage();if(empty){$('#noteSubject').closest('.form-row').insertAdjacentHTML('afterend',courseEmptyMessage());$('#flashSubject').parentElement.insertAdjacentHTML('beforeend',courseEmptyMessage());$('#quizSubject').parentElement.insertAdjacentHTML('beforeend',courseEmptyMessage())}bindSettingsShortcuts()}
function subjectNotes(subject){return user().notes.filter(n=>n.subject===subject)}
function statementsFor(subject){const text=subjectNotes(subject).map(n=>n.text).join(' ');return (text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).map(s=>s.trim()).filter(s=>s.split(' ').length>4)}

/* Flashcards */
function generateCards(){const subject=$('#flashSubject').value,folderId=normalizeFolderId($('#flashFolder').value),notes=subjectNotes(subject);if(!notes.length)return toast('Save notes for this course first.');const sentences=statementsFor(subject),keys=keywords(notes.map(n=>n.text).join(' '));currentCards=sentences.slice(0,5).map((s,i)=>{const key=keys.find(k=>s.toLowerCase().includes(k))||keys[i]||'this concept';return {id:'c'+Date.now()+i,subject,folderId,question:`What should you remember about ${key}?`,answer:s,topic:key}});while(currentCards.length<5)currentCards.push({id:'c'+Date.now()+currentCards.length,subject,folderId,question:`What is a key idea from ${notes[0].title}?`,answer:summarize(notes[0].text),topic:keys[currentCards.length]||subject});user().flashcards.push(...currentCards);touchFolder(folderId);cardIndex=0;saveDB();$('#flashEmpty').classList.add('hidden');$('#flashStudy').classList.remove('hidden');showCard();recordActivity('card',`Generated 5 ${subject} flashcards`)}
function showCard(){if(cardIndex>=currentCards.length){$('#flashStudy').innerHTML='<div class="empty-state card"><span class="empty-icon">✓</span><h2>Deck complete</h2><p>Your card progress has been saved. Review weak topics in Progress.</p><button class="btn btn-primary" onclick="location.reload()">Study another deck</button></div>';return}const c=currentCards[cardIndex];$('#flashcard').classList.remove('flipped');$('#flashQuestion').textContent=c.question;$('#flashAnswer').textContent=c.answer;$('#cardCounter').textContent=`Card ${cardIndex+1} of ${currentCards.length}`;$('#cardProgress').style.width=(cardIndex/currentCards.length*100)+'%';$('#knownCount').textContent=user().progress.cardsKnown}
function markCard(known){const c=currentCards[cardIndex];user().progress.cardsCompleted++;if(known)user().progress.cardsKnown++;else if(!user().progress.weakTopics.includes(c.topic))user().progress.weakTopics.push(c.topic);user().progress.minutes+=2;saveDB();cardIndex++;showCard()}
$('#generateCardsBtn').addEventListener('click',generateCards);$('#flashcard').addEventListener('click',()=>$('#flashcard').classList.toggle('flipped'));$('#flashcard').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')$('#flashcard').classList.toggle('flipped')});$('#knowCardBtn').addEventListener('click',()=>markCard(true));$('#reviewCardBtn').addEventListener('click',()=>markCard(false));

/* Quiz generation — mock logic. Replace buildQuiz with a real AI API response later. */
function buildQuiz(subject){const notes=subjectNotes(subject),sentences=statementsFor(subject),keys=keywords(notes.map(n=>n.text).join(' '));return Array.from({length:5},(_,i)=>{const sentence=sentences[i%sentences.length]||notes[0].text;const answer=keys.find(k=>sentence.toLowerCase().includes(k))||keys[i%keys.length]||subject;const wrong=keys.filter(k=>k!==answer).slice(0,3);while(wrong.length<3)wrong.push(['concept','process','evidence'][wrong.length]);const options=[answer,...wrong].sort(()=>Math.random()-.5);return {question:`Which term best connects to this idea: “${sentence.slice(0,105)}${sentence.length>105?'…':''}”`,answer,options,explanation:`The notes connect this idea with ${answer}: ${sentence}`}})}
function generateQuiz(){const subject=$('#quizSubject').value;if(!subjectNotes(subject).length)return toast('Save notes for this subject first.');const quiz=buildQuiz(subject);$('#quizEmpty').classList.add('hidden');$('#quizResult').classList.add('hidden');const form=$('#quizForm');form.dataset.subject=subject;form._quiz=quiz;form.innerHTML=quiz.map((q,i)=>`<article class="card quiz-question"><span>QUESTION ${i+1} OF 5</span><h3>${escapeHTML(q.question)}</h3><div class="options">${q.options.map(o=>`<label class="option"><input type="radio" name="q${i}" value="${escapeHTML(o)}"> ${escapeHTML(o[0].toUpperCase()+o.slice(1))}</label>`).join('')}</div><div class="explanation hidden"></div></article>`).join('')+'<button class="btn btn-primary" type="submit">Submit answers</button>';form.classList.remove('hidden')}
$('#generateQuizBtn').addEventListener('click',generateQuiz);$('#quizForm').addEventListener('submit',e=>{e.preventDefault();const quiz=e.target._quiz;let correct=0;quiz.forEach((q,i)=>{const chosen=$(`input[name="q${i}"]:checked`,e.target)?.value;const card=$$('.quiz-question',e.target)[i];$$('.option',card).forEach(l=>{const val=$('input',l).value;l.classList.toggle('correct',val===q.answer);l.classList.toggle('wrong',val===chosen&&chosen!==q.answer)});const ex=$('.explanation',card);ex.textContent=q.explanation;ex.classList.remove('hidden');if(chosen===q.answer)correct++});const score=correct*20;user().quizzes.push({subject:e.target.dataset.subject,score,date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})});user().progress.minutes+=10;recordActivity('quiz',`Scored ${score}% in ${e.target.dataset.subject}`);$('#quizResult').innerHTML=`<span class="pill blue-pill">QUIZ COMPLETE</span><h2>You scored <b>${score}%</b></h2><p>${correct} of 5 correct. Review the explanations above, then try again when you're ready.</p>`;$('#quizResult').classList.remove('hidden');e.target.querySelector('button[type="submit"]').disabled=true;$('#quizResult').scrollIntoView({behavior:'smooth'})});
$('#quizForm').addEventListener('submit',()=>{setTimeout(()=>{const q=user().quizzes[user().quizzes.length-1];if(q){q.folderId=normalizeFolderId($('#quizFolder').value);touchFolder(q.folderId);saveDB();renderOrganization()}},0)});

/* Planner */
function setMinDate(){const d=new Date(Date.now()+86400000);$('#testDate').min=d.toISOString().slice(0,10);if(!$('#testDate').value){const next=new Date(Date.now()+6*86400000);$('#testDate').value=next.toISOString().slice(0,10)}}
$('#plannerForm').addEventListener('submit',e=>{e.preventDefault();const courses=$$('input[name="planCourses"]:checked').map(x=>x.value);if(!courses.length)return toast('Choose at least one course.');const subject=courses.join(' + '),folderId=normalizeFolderId($('#planFolder').value),date=$('#testDate').value,topics=$('#planTopics').value.split(',').map(x=>x.trim()).filter(Boolean),minutes=Number($('#planMinutes').value),days=Math.max(1,Math.ceil((new Date(date+'T12:00:00')-new Date())/86400000)),count=Math.min(days,7),tasks=['Review notes and identify key ideas','Build and study flashcards','Complete a practice quiz','Focus on weak topics','Explain concepts without notes','Mix practice across all topics','Final review and early rest'];const plan=Array.from({length:count},(_,i)=>({day:i+1,task:tasks[i%tasks.length],topic:`${courses[i%courses.length]} · ${topics[i%topics.length]||'Review'}`,minutes}));user().plans.unshift({id:'p'+Date.now(),subject,courses,folderId,date,topics,minutes,plan});touchFolder(folderId);recordActivity('note',`Created a ${subject} study plan`);$('#scheduleTitle').textContent=`${subject} · ${count} day plan`;$('#scheduleList').innerHTML=plan.map(p=>`<div class="schedule-item"><span class="schedule-day">DAY ${p.day}</span><div><b>${escapeHTML(p.task)}</b><p>${escapeHTML(p.topic)}</p></div><span>${p.minutes} min</span></div>`).join('');renderOrganization();toast('Your study plan is ready.')});

/* Progress */
function renderProgress(){const u=user();if(!u)return;const p=u.progress,avg=u.quizzes.length?Math.round(u.quizzes.reduce((a,b)=>a+b.score,0)/u.quizzes.length):null;$('#statNotes').textContent=u.notes.length;$('#statCards').textContent=p.cardsCompleted;$('#statKnown').textContent=`${p.cardsKnown} marked known`;$('#statQuiz').textContent=avg===null?'—':avg+'%';$('#statStreak').textContent=p.streak+(p.streak===1?' day':' days');$('#quizChart').innerHTML=u.quizzes.length?u.quizzes.slice(-7).map(q=>`<div class="chart-bar"><b>${q.score}%</b><i style="height:${q.score}%"></i><small>${escapeHTML(q.subject.slice(0,4))}</small></div>`).join(''):'<div class="empty-mini">Complete a quiz to see your scores here.</div>';$('#weakTopics').innerHTML=p.weakTopics.length?p.weakTopics.slice(-6).map(t=>`<div class="weak-item"><b>${escapeHTML(t)}</b><span>Review next</span></div>`).join(''):'<div class="empty-mini">Topics marked “Need review” will appear here.</div>';$('#subjectProgress').innerHTML=getSubjects().map(s=>{const score=subjectScore(s);return `<div class="progress-subject"><b>${escapeHTML(s)}</b><div class="progress-line"><i style="width:${score}%"></i></div><span>${score}%</span></div>`}).join('')}

async function init(){await loadCourses();if(currentUser===GUEST_SESSION)enterGuestMode();else if(currentUser&&db.users[currentUser])logIn(currentUser);else{localStorage.removeItem(SESSION_KEY);$('#landing').classList.add('active')}}
init();
