(function(root){'use strict';
const freeze=Object.freeze;
const StudentDataCategory=freeze(['ACCOUNT_IDENTITY','PUBLIC_PROFILE','PRIVATE_PROFILE','ACCESSIBILITY_PREFERENCES','LANGUAGE_PREFERENCES','FUNCTIONAL_LEARNING_PREFERENCES','LEARNING_DIFFICULTY_DISCLOSURE','DISABILITY_OR_MEDICAL_INFORMATION','ACCOMMODATION_REQUEST','ACCOMMODATION_DOCUMENT','TEMPORARY_SPEECH_AUDIO','STORED_VOICE_RECORDING','VOICE_MESSAGE','PRONUNCIATION_PRACTICE_AUDIO','SESSION_AUDIO_RECORDING','LIVE_CAPTION_BUFFER','SAVED_TRANSCRIPT','SESSION_TRANSCRIPT','VOICE_MESSAGE_TRANSCRIPT','AUDIO_SUMMARY_TRANSCRIPT','PERSONAL_TRANSCRIPT_NOTE','CONSENT_RECORD','SHARING_GRANT','AUTHORIZED_ADULT_RELATIONSHIP','DATA_ACCESS_HISTORY','OFFLINE_DEVICE_DATA','DOWNLOADED_FILE_METADATA','AI_DERIVED_ARTIFACT','EMBEDDING_OR_SEARCH_INDEX','DATA_EXPORT','DATA_DELETION_REQUEST','OTHER_REVIEWED_CATEGORY']);
const DataSensitivity=freeze(['PUBLIC','PRIVATE','SENSITIVE','HIGHLY_RESTRICTED']);
const ProcessingRequirement=freeze(['OPTIONAL','REQUIRED_FOR_REQUESTED_FEATURE','REQUIRED_BY_ORGANIZATION_POLICY','REQUIRED_BY_APPLICABLE_RULE','REQUIRED_FOR_SAFETY_OR_SECURITY','NOT_AVAILABLE']);
const PrivacyConsentType=freeze(['TEMPORARY_AUDIO_PROCESSING_FOR_SPEECH_TO_TEXT','SAVE_VOICE_MESSAGE','SAVE_SESSION_AUDIO_RECORDING','SAVE_PERSONAL_TRANSCRIPT','SAVE_SHARED_SESSION_TRANSCRIPT','SHARE_FUNCTIONAL_PREFERENCES_WITH_TUTOR','SHARE_SELECTED_PREFERENCES_WITH_TEACHER','SHARE_ACCOMMODATION_REQUEST_WITH_AUTHORIZED_STAFF','INCLUDE_PERSONAL_DATA_IN_EXPORT','OTHER_REVIEWED_OPTIONAL_PROCESSING']);
const ConsentScope=freeze(['ONE_ACTION','ONE_MESSAGE','ONE_SESSION','ONE_COURSE','ONE_ORGANIZATION','ACCOUNT_PREFERENCE']);
const ConsentStatus=freeze(['PENDING','GRANTED','DECLINED','WITHDRAWN','EXPIRED','SUPERSEDED','INVALIDATED','NOT_APPLICABLE']);
const TranscriptSavingPreference=freeze(['ASK_EACH_TIME','DO_NOT_SAVE_PERSONAL_COPY','SAVE_PERSONAL_COPY','ALLOW_SHARED_COPY_WHEN_EXPLICITLY_APPROVED','FOLLOW_REQUIRED_SESSION_POLICY']);
const TutorPreferenceSharingMode=freeze(['SHARE_NOTHING','SHARE_FUNCTIONAL_PREFERENCES_ONLY','CUSTOM']);
const PrivacyDeletionStatus=freeze(['REQUESTED','VALIDATING','ACCESS_REVOKED','DELETING_PRIMARY_COPY','PROVIDER_DELETION_PENDING','BACKUP_EXPIRATION_PENDING','COMPLETED','PARTIALLY_COMPLETED','RETAINED_UNDER_POLICY','LEGAL_OR_SAFETY_HOLD','FAILED','CANCELLED']);
const DataExportStatus=freeze(['REQUESTED','VERIFYING_IDENTITY','PREPARING','READY','DOWNLOADED','EXPIRED','PARTIALLY_AVAILABLE','DENIED','FAILED','CANCELLED']);
const PrivacyRequestType=freeze(['DATA_EXPORT','DELETE_VOICE_RECORDING','DELETE_TRANSCRIPT','DELETE_DERIVED_DATA','DELETE_OFFLINE_DATA','CORRECT_DATA','REVOKE_SHARING','REQUEST_SHARED_RECORD_REMOVAL','REVIEW_AUTHORIZED_ADULT_ACCESS','OTHER_PRIVACY_REQUEST']);
const PrivacyRequestStatus=freeze(['DRAFT','SUBMITTED','IDENTITY_VERIFICATION_REQUIRED','UNDER_REVIEW','IN_PROGRESS','PARTIALLY_COMPLETED','COMPLETED','DENIED','WITHDRAWN','FAILED']);
const TransformationType=freeze(['TRANSCRIPTION','TRANSLATION','SUMMARIZATION','AUDIO_GENERATION','EMBEDDING','SEARCH_INDEXING','EXPORT','OFFLINE_COPY','OTHER_REVIEWED_TRANSFORMATION']);
const PUBLIC_FIELDS=freeze(['displayName','avatar','academicInterests','publicContributionBadges']);
const forbiddenPublic=freeze(['accessibilityProfile','accessibilitySettings','languagePreferences','bridgeLanguageCode','transcriptPreferences','recordingConsent','disability','diagnosis','accommodation','accommodationDocuments','learningDifficulty','guardianInformation','voiceRecordings','transcriptHistory','privacyRequests','tutorSharingPreferences','lowBandwidthPreference','participationModeHistory']);
const functionalFields=freeze(['preferredExplanationLanguage','bridgeLanguage','explanationLevel','captionsPreferred','textOnlyPreferred','textToSpeechHelpful','speechToTextHelpful','largeTextPreferred','reducedMotionPreferred','lowBandwidthPreferred']);
const highly=new Set(['LEARNING_DIFFICULTY_DISCLOSURE','DISABILITY_OR_MEDICAL_INFORMATION','ACCOMMODATION_REQUEST','ACCOMMODATION_DOCUMENT','AUTHORIZED_ADULT_RELATIONSHIP','DATA_EXPORT']);
const sensitive=new Set(['ACCESSIBILITY_PREFERENCES','LANGUAGE_PREFERENCES','FUNCTIONAL_LEARNING_PREFERENCES','TEMPORARY_SPEECH_AUDIO','STORED_VOICE_RECORDING','VOICE_MESSAGE','PRONUNCIATION_PRACTICE_AUDIO','SESSION_AUDIO_RECORDING','LIVE_CAPTION_BUFFER','SAVED_TRANSCRIPT','SESSION_TRANSCRIPT','VOICE_MESSAGE_TRANSCRIPT','AUDIO_SUMMARY_TRANSCRIPT','PERSONAL_TRANSCRIPT_NOTE','CONSENT_RECORD','SHARING_GRANT','DATA_ACCESS_HISTORY','OFFLINE_DEVICE_DATA','DOWNLOADED_FILE_METADATA','AI_DERIVED_ARTIFACT','EMBEDDING_OR_SEARCH_INDEX','DATA_DELETION_REQUEST','OTHER_REVIEWED_CATEGORY']);
const state={transcriptPreference:'ASK_EACH_TIME',tutorSharingMode:'SHARE_NOTHING',consents:[],requests:[],recording:{active:false,transcript:false,startedBy:null,startedAt:null}};
function controlled(v,list,label){if(!list.includes(v))throw new Error(`Unknown ${label}.`);return v}
function classify(c){controlled(c,StudentDataCategory,'student data category');return c==='PUBLIC_PROFILE'?'PUBLIC':highly.has(c)?'HIGHLY_RESTRICTED':sensitive.has(c)?'SENSITIVE':'PRIVATE'}
function toPublicStudentProfileView(input={}){return PUBLIC_FIELDS.reduce((o,k)=>(input[k]===undefined?o:(o[k]=input[k],o)),{})}
function minimizeForAI(input={}){const blocked=/diagnos|disabil|accommodation|guardian|privateNote|medical/i;return Object.fromEntries(Object.entries(input).filter(([k])=>!blocked.test(k)&&k!=='otherParticipants'))}
function tutorPreview(profile={},selected=functionalFields){return {shared:Object.fromEntries(selected.filter(k=>functionalFields.includes(k)&&profile[k]!=null).map(k=>[k,profile[k]])),notShared:['Disability or medical information','Accommodation documents','Private transcript history','Voice recordings','Why these settings were selected']}}
function consentDecision(i){controlled(i.type,PrivacyConsentType,'consent type');controlled(i.scope,ConsentScope,'consent scope');if(i.type==='SAVE_SESSION_AUDIO_RECORDING'&&!['ONE_ACTION','ONE_SESSION'].includes(i.scope))throw new Error('Session recording cannot use blanket account consent.');if(!['GRANTED','DECLINED'].includes(i.status))throw new Error('Consent choice must be granted or declined.');const r={id:`consent-${state.consents.length+1}`,type:i.type,scope:i.scope,status:i.status,noticeVersion:i.noticeVersion,policyVersion:i.policyVersion,dataCategories:(i.dataCategories||[]).map(c=>controlled(c,StudentDataCategory,'student data category')),recipients:i.recipients||[],retentionRule:i.retentionRule||'Policy configuration required',createdAt:new Date().toISOString()};state.consents.push(r);return {...r}}
function withdrawConsent(id){const r=state.consents.find(x=>x.id===id);if(!r)throw new Error('Consent record not found.');r.status='WITHDRAWN';r.withdrawnAt=new Date().toISOString();if(r.type==='SAVE_SESSION_AUDIO_RECORDING')stopRecording();return {...r}}
function startRecording(i){if(i?.authorized!==true)throw new Error('Recording cannot start before current authorization.');if(!i.noticeVersion||!i.policyVersion)throw new Error('Current recording notice and policy are required.');state.recording={active:true,transcript:i.transcript===true,startedBy:i.startedBy||'Authorized session host',startedAt:new Date().toISOString()};announce('Recording started');return {...state.recording}}
function stopRecording(){state.recording.active=false;announce('Recording stopped');return {...state.recording}}
function request(type,categories,key){controlled(type,PrivacyRequestType,'privacy request type');if(!key)throw new Error('An idempotency key is required.');const old=state.requests.find(x=>x.idempotencyKey===key);if(old)return {...old};const r={id:`privacy-request-${state.requests.length+1}`,type,categories:(categories||[]).map(c=>controlled(c,StudentDataCategory,'student data category')),status:'DRAFT',idempotencyKey:key,notice:'This client-only draft has not been submitted to a server.',createdAt:new Date().toISOString()};state.requests.push(r);return {...r}}
function recordingNotice(p={}){return {title:'Session Recording Request',what:p.what||'Session audio. Video is not included unless separately stated.',rawAudio:p.rawAudio||'Policy configuration required.',transcript:p.transcript||'Policy configuration required.',purpose:p.purpose||'Policy configuration required.',recipients:p.recipients||['Policy configuration required'],processors:p.processors||['Processor configuration required'],retention:p.retention||'Retention policy configuration required.',canDecline:p.canDecline!==false,alternative:p.alternative||'Continue without saved recording or use Text-Only participation when available.',withdrawal:'Withdraw optional consent to stop future optional processing. Delete existing eligible data separately.',deletion:'Review eligible deletion controls in My Privacy and Data.',derived:'A transcript or summary may be created only when separately authorized.',downloads:'Files downloaded outside StudySpark may not be remotely removable.'}}
function removeDeviceData(o={}){if(o.unsyncedDrafts>0&&!o.confirmUnsyncedLoss)throw new Error('Export or explicitly confirm removal of unsynced drafts first.');const keys=['studySparkTranscriptCache','studySparkDownloadedAudio','studySparkPracticeData','studySparkOfflinePackages'];if(typeof localStorage!=='undefined')keys.forEach(k=>localStorage.removeItem(k));return {removed:keys,externalFilesRemoved:false,notice:'Files in Downloads, printed pages, and copies in other apps were not removed.'}}
function announce(t){if(typeof document!=='undefined'){const e=document.querySelector('#privacyLiveStatus');if(e)e.textContent=t}}
const inventory=freeze([
['ACCESSIBILITY_PREFERENCES','Accessibility settings','Functional display and participation choices.','Present StudySpark in the way you choose.','You; approved tutor fields only after sharing.','Stored in this browser prototype until cleared.',true],
['LANGUAGE_PREFERENCES','Language preferences','Selected explanation and bridge languages.','Show explanations in your chosen format.','You; selected tutor fields only after sharing.','Stored in this browser prototype until cleared.',true],
['SAVED_TRANSCRIPT','Transcripts and captions','Saved records are distinct from temporary live captions.','Review authorized sessions and content.','Depends on personal or shared transcript choice.','No canonical server retention policy is configured.',false],
['STORED_VOICE_RECORDING','Voice and audio','Stored recordings are separate from temporary microphone processing.','Only the purpose shown before recording.','Depends on current notice and policy.','No recording store or provider policy is configured.',false],
['SHARING_GRANT','Tutor and teacher sharing','Narrow grants for selected functional preferences.','Help an authorized tutor or teacher.','Only the named authorized recipient and scope.','Until revoked or expired under policy.',true],
['OFFLINE_DEVICE_DATA','Offline and device data','Drafts, caches and app-managed downloads on this device.','Support weak connections and offline study.','This browser profile.','Until cleanup, expiry, or browser removal.',true],
['CONSENT_RECORD','Consent and privacy requests','Receipts for granular choices and request drafts.','Remember and explain choices without bundling.','You; authorized privacy staff in production.','Server policy is not configured.',false]
]);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){if(typeof document==='undefined')return;const e=document.querySelector('#privacyDataContent');if(!e)return;e.innerHTML=`<div id="privacyLiveStatus" class="sr-only" role="status" aria-live="polite"></div><section class="privacy-hero card"><span class="kicker">PRIVATE BY DEFAULT · CLIENT PROTOTYPE</span><h2>My Privacy and Data</h2><p>Review data categories, purposes, recipients, retention information, and available controls. Production authorization, provider deletion, secure exports and policy enforcement are not connected.</p><div class="privacy-alert" role="note"><b>No public disability disclosure.</b> Sensitive privacy and accessibility choices are excluded from the public serializer.</div></section><nav class="privacy-tabs" aria-label="Privacy sections"><button type="button" data-privacy="stored">My Stored Data</button><button type="button" data-privacy="recording">Recording & Transcripts</button><button type="button" data-privacy="sharing">Tutor Sharing</button><button type="button" data-privacy="requests">Requests & Device Data</button></nav><section id="privacyPanel"></section>`;e.querySelectorAll('[data-privacy]').forEach(b=>b.onclick=()=>panel(b.dataset.privacy));panel('stored')}
function panel(name){const e=document.querySelector('#privacyPanel');if(!e)return;if(name==='stored')e.innerHTML=`<h2>What information is stored</h2><div class="privacy-grid">${inventory.map(x=>`<article class="card privacy-card"><h3>${safe(x[1])}</h3><p>${safe(x[2])}</p><dl><dt>Sensitivity</dt><dd>${classify(x[0]).replaceAll('_',' ')}</dd><dt>Purpose</dt><dd>${safe(x[3])}</dd><dt>Who may access</dt><dd>${safe(x[4])}</dd><dt>Retention</dt><dd>${safe(x[5])}</dd><dt>Export</dt><dd>Requires production authorization</dd><dt>Deletion</dt><dd>${x[6]?'Device/preference control available':'Requires reviewed server workflow'}</dd></dl></article>`).join('')}</div>`;
if(name==='recording')e.innerHTML=`<div class="privacy-two"><form class="card" id="transcriptPreferenceForm"><h2>Transcript-saving preference</h2><p>Live captions do not automatically mean a saved transcript.</p><label>Personal transcript default<select name="preference">${TranscriptSavingPreference.map(v=>`<option ${v===state.transcriptPreference?'selected':''}>${v}</option>`).join('')}</select></label><button class="btn btn-primary">Save on This Device</button></form><article class="card"><h2>Recording status</h2><p><b>Session audio recording:</b> ${state.recording.active?'On':'Off'}</p><p><b>Saved transcript:</b> ${state.recording.transcript?'On':'Off'}</p><p>Every recording event requires a current notice and authorization.</p><button class="btn btn-secondary" data-notice>Review Recording Information</button></article></div><article class="card privacy-notice" id="recordingNotice" hidden></article>`;
if(name==='sharing')e.innerHTML=`<div class="privacy-two"><form class="card" id="sharingForm"><h2>What My Tutor Can See</h2><label>Sharing mode<select name="mode">${TutorPreferenceSharingMode.map(v=>`<option>${v}</option>`).join('')}</select></label><fieldset><legend>Select functional preferences</legend>${functionalFields.map(v=>`<label><input type="checkbox" name="field" value="${v}"> ${safe(v)}</label>`).join('')}</fieldset><button class="btn btn-primary">Preview Sharing</button></form><article class="card" id="sharingPreview"><h2>Tutor Sharing Preview</h2><p>Nothing is shared by default. A preview creates no grant.</p><p>Diagnoses, documents, private transcripts, recordings, and reasons are excluded.</p></article></div>`;
if(name==='requests')e.innerHTML=`<div class="privacy-grid"><article class="card"><h2>Download My Data</h2><p>Secure export needs server verification, authorization, hashes, a human-readable index and an expiring link.</p><button class="btn btn-secondary" data-request="DATA_EXPORT">Prepare Export Request Draft</button></article><article class="card"><h2>Delete My Data</h2><p>Source deletion does not automatically remove shared records, backups, derived data, or external files.</p><button class="btn btn-secondary" data-request="DELETE_TRANSCRIPT">Prepare Deletion Request Draft</button></article><article class="card"><h2>Private data on this device</h2><p>App-managed caches can be removed. Unsynced work requires a separate warning.</p><button class="btn btn-danger" data-remove>Remove Optional App-Managed Data</button></article><article class="card"><h2>Privacy help</h2><p>This prototype cannot submit a privacy concern.</p><button class="btn btn-secondary" disabled>Report a Privacy Concern — Server Required</button></article></div><div id="privacyRequestStatus" role="status"></div>`;bind(e)}
function bind(e){e.querySelector('#transcriptPreferenceForm')?.addEventListener('submit',x=>{x.preventDefault();state.transcriptPreference=controlled(new FormData(x.target).get('preference'),TranscriptSavingPreference,'transcript preference');announce('Transcript preference saved on this device')});e.querySelector('[data-notice]')?.addEventListener('click',()=>{const n=recordingNotice(),b=e.querySelector('#recordingNotice');b.hidden=false;b.innerHTML=`<h2>${n.title}</h2>${Object.entries(n).slice(1).map(([k,v])=>`<h3>${safe(k)}</h3><p>${safe(Array.isArray(v)?v.join(', '):v)}</p>`).join('')}`});e.querySelector('#sharingForm')?.addEventListener('submit',x=>{x.preventDefault();const d=new FormData(x.target),p=tutorPreview(Object.fromEntries(functionalFields.map(k=>[k,'Selected'])),d.getAll('field'));e.querySelector('#sharingPreview').innerHTML=`<h2>Tutor Sharing Preview</h2><h3>Would share after authorization</h3><ul>${Object.keys(p.shared).map(k=>`<li>${safe(k)}</li>`).join('')||'<li>Nothing</li>'}</ul><h3>Will not share</h3><ul>${p.notShared.map(k=>`<li>${safe(k)}</li>`).join('')}</ul>`});e.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>{const r=request(b.dataset.request,[],`ui-${b.dataset.request}`);e.querySelector('#privacyRequestStatus').innerHTML=`<p class="privacy-alert"><b>${r.status}:</b> ${r.notice}</p>`});e.querySelector('[data-remove]')?.addEventListener('click',()=>{const r=removeDeviceData({unsyncedDrafts:0});e.querySelector('#privacyRequestStatus').innerHTML=`<p class="privacy-alert">Optional app caches cleared. ${r.notice}</p>`})}
const api={StudentDataCategory,DataSensitivity,ProcessingRequirement,PrivacyConsentType,ConsentScope,ConsentStatus,TranscriptSavingPreference,TutorPreferenceSharingMode,PrivacyDeletionStatus,DataExportStatus,PrivacyRequestType,PrivacyRequestStatus,TransformationType,PUBLIC_FIELDS,forbiddenPublic,functionalFields,classify,toPublicStudentProfileView,minimizeForAI,tutorPreview,consentDecision,withdrawConsent,startRecording,stopRecording,request,recordingNotice,removeDeviceData,inventory,state,render,_test:{controlled}};root.StudentPrivacy=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof document!=='undefined'){if(typeof viewNames==='object')viewNames.privacyData=['ACCOUNT','My Privacy and Data'];const old=typeof showView==='function'?showView:null;if(old)showView=async function(v,o={}){const r=await old(v,o);if(v==='privacyData')render();return r}}
})(typeof window!=='undefined'?window:globalThis);
