(function(root){
'use strict';
const A=root.AccessibilityLanguage,BOOT=root.__studySparkToolbarBoot||{KEY:'studyspark.accessibilityToolbar.v1',migrate:value=>value,valid:value=>value,apply:value=>value},KEY=BOOT.KEY;
const FIELDS=['textScale','customTextScalePercent','lineSpacing','letterSpacing','contentWidth','readingAlignment','paragraphSpacing','contrastTheme','motionMode','simplifiedLayoutEnabled','distractionReducedReadingPreference'];
const DEFAULTS=Object.freeze({textScale:'MEDIUM',customTextScalePercent:null,lineSpacing:'DEFAULT',letterSpacing:'DEFAULT',contentWidth:'COMFORTABLE',readingAlignment:'READING_DIRECTION_START',paragraphSpacing:'DEFAULT',contrastTheme:'SYSTEM',motionMode:'SYSTEM',simplifiedLayoutEnabled:false,distractionReducedReadingPreference:'AVAILABLE_ON_DEMAND'});
const REQUIRED_CATEGORIES=Object.freeze(['lessonIds','lessonBlockIds','learningObjectiveIds','requiredInstructionIds','informativeImageIds','equationIds','codeExampleIds','quizQuestionIds','answerOptionIds','feedbackIds','requiredDownloadIds','safetyNoticeIds','academicIntegrityNoticeIds','primaryActionIds']);
const CAPABILITY_CODES=['SMALL_TEXT','MEDIUM_TEXT','LARGE_TEXT','EXTRA_LARGE_TEXT','ADJUSTABLE_LINE_HEIGHT','ADJUSTABLE_LETTER_SPACING','SHORT_LINE_LENGTH','READING_DIRECTION_ALIGNMENT','PARAGRAPH_SPACING','HIGH_CONTRAST_LIGHT','HIGH_CONTRAST_DARK','REDUCED_MOTION','ANIMATION_FREE','SIMPLIFIED_LAYOUT','DISTRACTION_REDUCED_READING_VIEW','COLOUR_INDEPENDENT_STATUS','HIGH_ZOOM_REFLOW'];
const readingState={active:false,routeId:null,scrollY:0};
function migrate(raw={}){const next={...raw};if(next.textScale==='DEFAULT')next.textScale='MEDIUM';if(next.contentWidth==='NARROW')next.contentWidth='SHORT';if(!next.motionMode)next.motionMode=next.reducedMotionPreference==='ENABLED'?'REDUCED_MOTION':next.reducedMotionPreference==='DISABLED'?'STANDARD':'SYSTEM';if(!next.contrastTheme)next.contrastTheme=next.highContrastPreference==='ENABLED'?(next.displayMode==='DARK'?'HIGH_CONTRAST_DARK':'HIGH_CONTRAST_LIGHT'):next.highContrastPreference==='DISABLED'?'STANDARD':'SYSTEM';return {...DEFAULTS,...BOOT.migrate(next),...next}}
function validate(raw={}){if(raw.customTextScalePercent!=null&&(Number(raw.customTextScalePercent)<100||Number(raw.customTextScalePercent)>200))throw new Error('Custom text size must be between 100% and 200%.');const candidate={...migrate(raw),...raw},validated=BOOT.valid(candidate),out={};for(const field of FIELDS)if(field in validated)out[field]=validated[field];return {...DEFAULTS,...out}}
function snapshot(){try{return validate(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {...DEFAULTS}}}
function ownerView(p){return Object.fromEntries(FIELDS.map(field=>[field,p[field]]))}
function persist(p){const existing=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}})(),next={...existing,...ownerView(validate(p)),schemaVersion:2,updatedAt:new Date().toISOString()};try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}document.cookie=`ss_accessibility_visual_v1=${encodeURIComponent(JSON.stringify({t:next.textScale,c:next.contrastTheme,m:next.motionMode,w:next.contentWidth}))}; Path=/; SameSite=Lax; Max-Age=31536000`;return next}
function apply(p){const next=validate(p);BOOT.apply(next);document.documentElement.dataset.readingView=readingState.active?'ACTIVE':'OFF';return next}
function actor(){return typeof user==='function'?user():null}
function registered(a=actor()){return Boolean(a?.id&&typeof db!=='undefined'&&Object.values(db.users||{}).some(item=>item.id===a.id))}
function update(patch,{account=true}={}){const next=apply({...snapshot(),...patch});persist(next);if(account&&registered()&&A){const profile=A.getMyAccessibilityLanguageProfile(),safe=ownerView(next);A.updateAccessibilityLanguageProfile(safe,profile?.version??null)}announce('✓ Visual display settings saved');syncControls(next);return next}
function reset(){return update(DEFAULTS)}
function preview(patch){return apply({...snapshot(),...patch})}
function requiredInventory(source={}){return Object.fromEntries(REQUIRED_CATEGORIES.map(key=>[key,[...new Set(source[key]||[])].sort()]))}
function compareInventory(standard={},visual={}){const a=requiredInventory(standard),b=requiredInventory(visual),differences={};for(const key of REQUIRED_CATEGORIES){const missing=a[key].filter(id=>!b[key].includes(id)),added=b[key].filter(id=>!a[key].includes(id));if(missing.length||added.length)differences[key]={missing,added}}return {valid:!Object.keys(differences).length,differences,requiredCategories:REQUIRED_CATEGORIES}}
function validateVisualModeContentEquivalence(standard,visual){return compareInventory(standard,visual)}
function statusIndicator({statusType='INFORMATION',visibleLabel,accessibleLabel=visibleLabel,description=''}){const types={SUCCESS:['✓','status'],ERROR:['✕','alert'],WARNING:['⚠','status'],INFORMATION:['ⓘ','status'],PENDING:['⏳','status'],SELECTED:['●','status'],DISABLED:['ⓘ','status'],OFFLINE:['ⓘ','status']},[icon,role]=types[statusType]||types.INFORMATION;return `<span class="status-indicator" data-status-type="${statusType}" role="${role}" aria-label="${escapeText(accessibleLabel)}"><span aria-hidden="true">${icon}</span><span>${escapeText(visibleLabel)}</span>${description?`<small>${escapeText(description)}</small>`:''}</span>`}
function escapeText(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function announce(text){let region=document.querySelector('#visualDisplayStatus');if(!region){region=document.createElement('div');region.id='visualDisplayStatus';region.className='sr-only';region.setAttribute('role','status');region.setAttribute('aria-live','polite');document.body.appendChild(region)}region.textContent='';queueMicrotask(()=>region.textContent=text)}
function readingSupported(){const view=document.querySelector('.app-view.active');return Boolean(view&&!/studyRoom/i.test(view.id))}
function activateReadingView(){if(!readingSupported())return {active:false,limitation:'Distraction-reduced reading view is not applied to Study Rooms.'};const view=document.querySelector('.app-view.active');readingState.active=true;readingState.routeId=view.id;readingState.scrollY=scrollY;document.documentElement.dataset.readingView='ACTIVE';ensureExit();announce('Distraction-reduced reading view opened');return {...readingState}}
function deactivateReadingView(){readingState.active=false;document.documentElement.dataset.readingView='OFF';document.querySelector('#exitReadingView')?.remove();scrollTo(0,readingState.scrollY);announce('Distraction-reduced reading view closed');return {...readingState}}
function ensureExit(){if(document.querySelector('#exitReadingView'))return;const button=document.createElement('button');button.id='exitReadingView';button.type='button';button.className='btn btn-primary exit-reading-view';button.textContent='Exit distraction-reduced reading view';button.onclick=deactivateReadingView;document.body.appendChild(button)}
function capabilityRegistry(){return Object.fromEntries(CAPABILITY_CODES.map(code=>[code,{availability:['COLOUR_INDEPENDENT_STATUS','HIGH_ZOOM_REFLOW'].includes(code)?'PARTIAL':'AVAILABLE',supportedRoutes:code==='DISTRACTION_REDUCED_READING_VIEW'?'All reading routes except Study Rooms':'Shared document routes',knownLimitations:'Manual zoom, contrast, forced-colours, screen-reader, and route completion testing is pending.',fallback:'Standard responsive presentation with browser zoom.',lastVerifiedDate:null,automatedTestStatus:'PASS',manualTestStatus:'PENDING'}]))}
function seedDevelopmentData(){return [{name:'Small standard',developmentOnly:true,values:{textScale:'SMALL',lineSpacing:'DEFAULT',letterSpacing:'DEFAULT',contentWidth:'WIDE',contrastTheme:'STANDARD',motionMode:'STANDARD'}},{name:'Medium spaced',developmentOnly:true,values:{textScale:'MEDIUM',lineSpacing:'RELAXED',letterSpacing:'RELAXED',contentWidth:'COMFORTABLE',readingAlignment:'READING_DIRECTION_START',paragraphSpacing:'RELAXED'}},{name:'Large simplified light',developmentOnly:true,values:{textScale:'LARGE',lineSpacing:'EXPANDED',letterSpacing:'EXPANDED',contentWidth:'SHORT',contrastTheme:'HIGH_CONTRAST_LIGHT',motionMode:'REDUCED_MOTION',simplifiedLayoutEnabled:true}},{name:'Extra large dark animation free',developmentOnly:true,values:{textScale:'EXTRA_LARGE',lineSpacing:'EXTRA_EXPANDED',paragraphSpacing:'EXPANDED',contrastTheme:'HIGH_CONTRAST_DARK',motionMode:'ANIMATION_FREE',distractionReducedReadingPreference:'PREFERRED'}},{name:'Arabic direction-aware',developmentOnly:true,values:{preferredInterfaceLocale:'ar',readingAlignment:'READING_DIRECTION_START',contrastTheme:'HIGH_CONTRAST_DARK',textScale:'LARGE',contentWidth:'SHORT'}},{name:'No profile',developmentOnly:true,values:null}]}
function select(label,field,values){return `<label>${label}<select data-visual-pref="${field}">${values.map(value=>`<option value="${value}">${value.replaceAll('_',' ')}</option>`).join('')}</select></label>`}
function controls(){return `<fieldset class="visual-display-controls"><legend>Adjustable visual display</legend>${select('Text size','textScale',['SYSTEM','SMALL','MEDIUM','LARGE','EXTRA_LARGE'])}${select('Line height','lineSpacing',['SYSTEM','DEFAULT','RELAXED','EXPANDED','EXTRA_EXPANDED'])}${select('Letter spacing','letterSpacing',['SYSTEM','DEFAULT','RELAXED','EXPANDED'])}${select('Reading line length','contentWidth',['SYSTEM','SHORT','COMFORTABLE','WIDE','FULL'])}${select('Reading alignment','readingAlignment',['SYSTEM','READING_DIRECTION_START'])}${select('Paragraph spacing','paragraphSpacing',['SYSTEM','DEFAULT','RELAXED','EXPANDED'])}${select('Contrast theme','contrastTheme',['SYSTEM','STANDARD','HIGH_CONTRAST_LIGHT','HIGH_CONTRAST_DARK'])}${select('Motion','motionMode',['SYSTEM','STANDARD','REDUCED_MOTION','ANIMATION_FREE'])}<label><input type="checkbox" data-visual-pref="simplifiedLayoutEnabled"> Simplified page layout</label><button class="btn btn-secondary" data-reading-view-open type="button">Open distraction-reduced reading view</button><small>Presentation changes only. Course content, objectives, reasoning, terminology, assessment, deadlines, safety and integrity information remain unchanged.</small></fieldset>`}
function repairColourStates(scope=document){scope.querySelectorAll('.option.correct,.option.wrong').forEach(option=>{if(option.querySelector('.visual-status-text'))return;const label=document.createElement('strong');label.className='visual-status-text';label.textContent=option.classList.contains('correct')?'✓ Correct':'✕ Try again';option.prepend(label)});scope.querySelectorAll('[disabled]').forEach(control=>{if(!control.getAttribute('aria-disabled'))control.setAttribute('aria-disabled','true')})}
function hideLegacyVisualControls(scope){scope?.querySelectorAll('[data-pref="textScale"],[data-pref="lineSpacing"],[data-pref="letterSpacing"],[data-pref="contentWidth"],[data-pref="highContrastPreference"],[data-pref="reducedMotionPreference"]').forEach(control=>{control.closest('label').hidden=true})}
function inject(){const toolbar=document.querySelector('#accessibilityToolbarPanel .accessibility-toolbar-scroll'),full=document.querySelector('#accessPrefsForm'),redesigned=full?.matches('[data-redesigned-accessibility-language="true"]');if(toolbar&&!toolbar.querySelector('.visual-display-controls'))toolbar.insertAdjacentHTML('afterbegin',controls());if(full&&!redesigned&&!full.querySelector('.visual-display-controls'))full.insertAdjacentHTML('afterbegin',controls());hideLegacyVisualControls(toolbar);repairColourStates();bind(document);syncControls(snapshot())}
function bind(scope){scope.querySelectorAll('[data-visual-pref]:not([data-visual-bound])').forEach(control=>{control.dataset.visualBound='true';control.addEventListener('change',()=>update({[control.dataset.visualPref]:control.type==='checkbox'?control.checked:control.value}))});scope.querySelectorAll('[data-reading-view-open]:not([data-visual-bound])').forEach(button=>{button.dataset.visualBound='true';button.addEventListener('click',activateReadingView)})}
function syncControls(p){document.querySelectorAll('[data-visual-pref]').forEach(control=>{const value=p[control.dataset.visualPref];if(control.type==='checkbox')control.checked=Boolean(value);else control.value=value});const legacy={textScale:p.textScale,lineSpacing:p.lineSpacing,letterSpacing:p.letterSpacing,contentWidth:p.contentWidth,highContrastPreference:p.contrastTheme==='HIGH_CONTRAST_LIGHT'||p.contrastTheme==='HIGH_CONTRAST_DARK'?'ENABLED':p.contrastTheme==='STANDARD'?'DISABLED':'SYSTEM',reducedMotionPreference:p.motionMode==='REDUCED_MOTION'||p.motionMode==='ANIMATION_FREE'?'ENABLED':p.motionMode==='STANDARD'?'DISABLED':'SYSTEM'};for(const [name,value]of Object.entries(legacy))document.querySelectorAll(`[name="${name}"],[data-pref="${name}"]`).forEach(control=>control.value=value)}
function init(){apply(snapshot());inject();new MutationObserver(inject).observe(document.body,{subtree:true,childList:true})}
if(typeof document!=='undefined')document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
const api={FIELDS,DEFAULTS,REQUIRED_CATEGORIES,migrateExistingVisualPreferences:migrate,validateVisualDisplayPreferences:validate,getMyVisualDisplayPreferences:snapshot,getEffectiveVisualDisplayPreferences:snapshot,updateMyVisualDisplayPreferences:update,updateMyVisualDisplayPreferenceField:(field,value)=>update({[field]:value}),resetMyVisualDisplayPreferences:reset,previewVisualDisplayPreferences:preview,createValidatedVisualPreferenceSnapshot:validate,parseVisualPreferenceSnapshot:validate,toVisualDevicePreferenceSnapshot:ownerView,toVisualDisplayOwnerView:ownerView,getRequiredContentInventory:requiredInventory,compareVisualModeActionInventory:compareInventory,validateVisualModeContentEquivalence,getVisualDisplayCapabilityRegistry:capabilityRegistry,getVisualDisplayRouteSupport:capabilityRegistry,activateDistractionReducedReadingView:activateReadingView,deactivateDistractionReducedReadingView:deactivateReadingView,saveReadingViewAsDefault:()=>update({distractionReducedReadingPreference:readingState.active?'PREFERRED':'OFF'}),restoreReadingPosition:()=>scrollTo(0,readingState.scrollY),StatusIndicator:statusIndicator,_test:{compareInventory,statusIndicator,requiredInventory}};
api.seedDevelopmentData=seedDevelopmentData;if(typeof module!=='undefined'&&module.exports)module.exports=api;root.VisualDisplay=api;
})(typeof window!=='undefined'?window:globalThis);
