'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const Coach=require('../prompt-writing-coach.js');
const source=fs.readFileSync(path.join(root,'prompt-writing-coach.js'),'utf8');
const css=fs.readFileSync(path.join(root,'prompt-writing-coach.css'),'utf8');

const workLabels=['Independent practice','Homework','Draft assignment','Research project','Quiz or test','Competition','I am not sure'];
assert.deepEqual(Coach._test.academicWorkTypes.map(item=>item.label),workLabels,'work-type question uses the exact seven options');
assert.match(source,/<legend>What are you working on\?<\/legend>/,'check asks the exact first question');
for(const label of workLabels) assert.match(source,new RegExp(label),`check includes ${label}`);
assert.match(source,/What is the teacher’s AI policy\?/,'check establishes the teacher AI policy');
for(const label of ['AI Allowed','AI Allowed with Disclosure','AI Allowed for Limited Tasks','AI Not Allowed','Policy Unknown']) assert.match(source,new RegExp(label),`check includes ${label}`);
assert.ok(Coach._test.aiAssistancePermissions.some(item=>item.value==='AI_NOT_PERMITTED'));
assert.ok(Coach._test.aiAssistancePermissions.some(item=>item.value==='NOT_SURE'));

const state=Coach._test.newGuidedBuilderState('hint');
let result=Coach._test.academicIntegrityCheck(state);
assert.equal(result.status,'REVIEW_REQUIRED');
assert.equal(result.allowed,false);
state.values.academicWorkType='INDEPENDENT_PRACTICE';
state.values.aiAssistancePermission='GENERAL_LEARNING_SUPPORT';
result=Coach._test.academicIntegrityCheck(state);
assert.equal(result.status,'READY');
assert.equal(result.allowed,true);
assert.equal(result.policyState,'AI_ALLOWED');
state.values.aiAssistancePermission='AI_ALLOWED_WITH_DISCLOSURE';
result=Coach._test.academicIntegrityCheck(state);
assert.equal(result.allowed,true);
assert.equal(result.policyState,'AI_ALLOWED_WITH_DISCLOSURE');

state.values.academicWorkType='HOMEWORK';
state.values.aiAssistancePermission='HINTS_OR_QUESTIONS_ONLY';
assert.equal(Coach._test.academicIntegrityCheck(state).allowed,true,'hint mode matches hint-only homework permission');
state.values.helpType='SIMPLER_EXPLANATION';
assert.equal(Coach._test.academicIntegrityCheck(state).status,'MODE_NOT_PERMITTED','mismatched learning mode is blocked');
state.values.helpType='HINT';
state.values.academicWorkType='QUIZ_OR_TEST';
state.values.aiAssistancePermission='GENERAL_LEARNING_SUPPORT';
result=Coach._test.academicIntegrityCheck(state);
assert.equal(result.allowed,false);
assert.equal(result.policyState,'ACTIVE_ASSESSMENT_RESTRICTED','generic permission cannot authorize an active quiz or test');
state.values.aiAssistancePermission='HINTS_OR_QUESTIONS_ONLY';
assert.equal(Coach._test.academicIntegrityCheck(state).allowed,true,'explicit limited test permission allows only its matching mode');
state.values.aiAssistancePermission='AI_NOT_PERMITTED';
assert.equal(Coach._test.academicIntegrityCheck(state).status,'BLOCKED');
state.values.aiAssistancePermission='NOT_SURE';
assert.equal(Coach._test.academicIntegrityCheck(state).allowed,false);

state.values.academicWorkType='HOMEWORK';
state.values.aiAssistancePermission='HINTS_OR_QUESTIONS_ONLY';
const input=Coach._test.guidedDraftInput(state);
assert.equal(input.academicWorkType,'HOMEWORK');
assert.equal(input.aiAssistancePermission,'HINTS_OR_QUESTIONS_ONLY');
assert.equal(input.academicIntegrityStatus,'READY');
assert.equal(input.assignmentPolicyRevalidated,true);
assert.equal(input.policyState,'AI_ALLOWED_FOR_LIMITED_TASKS');
const actor={userId:'integrity-student',tenantId:'integrity-school',role:'student'};
const session=Coach.createPromptCoachSession({idempotencyKey:'integrity-session',fictionalTask:false},actor).session;
const draft=Coach.createPromptDraftVersion({idempotencyKey:'integrity-draft',promptCoachSessionId:session.id,...input},actor).draft;
assert.equal(draft.academicWorkType,'HOMEWORK','private draft saves work type');
assert.equal(draft.aiAssistancePermission,'HINTS_OR_QUESTIONS_ONLY','private draft saves permission');
assert.equal(draft.academicIntegrityStatus,'READY');

assert.match(source,/const integrity = academicIntegrityCheck\(state\); if \(!integrity\.allowed\)/,'Academic Integrity Check runs before handoff');
assert.ok(source.indexOf('const integrity = academicIntegrityCheck(state)')<source.indexOf('const findings = scanPromptPrivacy(prompt)'),'Academic Integrity Check runs before the final Privacy Check');
assert.match(source,/state\.confirmed = false; state\.reviewed = false; state\.saved = false/,'changing integrity answers invalidates earlier approval');
assert.match(source,/!academicIntegrityCheck\(state\)\.allowed/,'privacy continuation cannot bypass Academic Integrity Check');
assert.doesNotMatch(source,/academicIntegrityCheck\(state\)[\s\S]{0,500}composer\.(?:submit|click)\(/,'integrity approval never submits the composer automatically');
assert.match(css,/\.academic-integrity-check/,'check has a clear inline panel');
assert.match(css,/\.academic-work-options/,'work types have organized controls');
assert.match(css,/@media\(max-width:36rem\)\{\.academic-work-options\{grid-template-columns:1fr\}/,'work types stack on narrow screens');
console.log('Prompt Coach Academic Integrity Check tests passed');
