const fs=require('fs'),path=require('path'),assert=require('assert'),vm=require('vm');const root=path.join(__dirname,'..'),script=fs.readFileSync(path.join(root,'script.js'),'utf8'),nav=fs.readFileSync(path.join(root,'first-screen-navigation.js'),'utf8'),js=fs.readFileSync(path.join(root,'source-comparison-experience.js'),'utf8'),css=fs.readFileSync(path.join(root,'source-comparison-experience.css'),'utf8'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8');new vm.Script(js);
assert(script.includes("sourceComparison:{role:'student',title:'Source Comparison'"));assert(script.includes("viewNames.sourceComparison=['AI COACH','Source Comparison']"));assert(script.includes("sourceComparison:'/ai-coach/source-comparison'"));for(const route of ['/source-comparison','/compare-sources','/ai-coach/compare-sources'])assert(script.includes(`'${route}':'sourceComparison'`));assert(nav.includes("['Source Comparison','sourceComparison']"));
for(const text of ['Source Comparison','Compare evidence, reliability, relevance, currency, bias, and limitations across multiple sources.','Compare Sources','Upload Sources','Paste Source Information','Import Saved Sources','A professional-looking source is not automatically reliable. Compare its evidence, author, date, purpose, and relevance.'])assert(js.includes(text),`missing ${text}`);
for(const text of ['Compare Two Sources','Compare Multiple Sources','Check Conflicting Sources','Compare Primary and Secondary Sources','Compare News Coverage','Compare Research Studies'])assert(js.includes(text),`missing card ${text}`);
for(const text of ['What question are you researching?','What claim are you checking?','What are you trying to decide?','What course or subject is this for?','What source types does the teacher permit?','Add Another Source','Maximum 10 MB'])assert(js.includes(text),`missing input ${text}`);
for(const text of ['Comparison Matrix','Simple View','Detailed View','Student Notes View','Strong Source','Useful with Caution','Limited Evidence','Outdated','Claim-to-Evidence Map','Unable to Verify','When Sources Disagree','Final Comparison Report','Student Thinking Question'])assert(js.includes(text),`missing report ${text}`);
for(const text of ['All Comparisons','Drafts','Completed','Needs More Evidence','You have not compared any sources yet.','Compare My First Sources','Try an Example','Learn How to Compare Sources'])assert(js.includes(text),`missing history ${text}`);
assert(js.includes('sourceCount>=5'));assert(js.includes("item.status==='Draft'")||js.includes("x.status!=='Draft'"));assert(js.includes('localStorage'));assert(js.includes('SpeechRecognition'));assert(js.includes('Invalid website address'));
for(const rule of ['@media(max-width:560px)','@media(prefers-reduced-motion:reduce)','@media(forced-colors:active)','[dir=rtl]','@media print'])assert(css.includes(rule));assert(html.includes('source-comparison-experience.css?v=source-comparison-complete-20260827'));assert(html.includes('source-comparison-experience.js?v=source-comparison-complete-20260827'));console.log('source-comparison-page.test.js passed');
