const fs=require('fs'),path=require('path'),assert=require('assert'),T=require('../text-to-speech.js');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8'),js=fs.readFileSync(path.join(root,'text-to-speech.js'),'utf8'),css=fs.readFileSync(path.join(root,'style.css'),'utf8'),boot=fs.readFileSync(path.join(root,'accessibility-toolbar-boot.js'),'utf8');
const tests=[],test=(name,fn)=>tests.push([name,fn]);
test('module loads before toolbar',()=>assert(html.indexOf('text-to-speech.js')<html.indexOf('accessibility-toolbar.js')));
test('thirteen approved source types',()=>assert.equal(T.SOURCE_TYPES.length,13));
test('all required source types exist',()=>['AI_EXPLANATION','LESSON_INSTRUCTION','READING_PASSAGE','QUIZ_QUESTION','QUIZ_ANSWER_OPTIONS','LEARNER_VISIBLE_FEEDBACK','STUDY_PLAN','SESSION_SUMMARY','VOCABULARY_DEFINITION','LESSON_SUMMARY'].forEach(x=>assert(T.SOURCE_TYPES.includes(x))));
test('authorization required',()=>assert.throws(()=>T.createSpeechDocument({sourceType:'AI_EXPLANATION'}),/denied/));
test('hidden content rejected',()=>assert.throws(()=>T.createSpeechDocument({sourceType:'AI_EXPLANATION',sourceId:'a',sourceVersion:'1',title:'A',authorized:true,hidden:true}),/eligible/));
test('private reviewer notes rejected',()=>assert.throws(()=>T.createSpeechDocument({sourceType:'AI_EXPLANATION',sourceId:'a',sourceVersion:'1',title:'A',authorized:true,privateReviewerNote:'x'}),/eligible/));
test('quiz answer key rejected',()=>assert.throws(()=>T.createSpeechDocument({sourceType:'QUIZ_QUESTION',sourceId:'q',sourceVersion:'1',title:'Q',authorized:true,answerKey:'A'}),/hidden assessment/));
test('excluded blocks omitted',()=>assert.equal(T.createSpeechDocument({sourceType:'AI_EXPLANATION',sourceId:'a',sourceVersion:'1',title:'A',authorized:true,blocks:[{blockType:'PARAGRAPH',visibleText:'Yes'},{blockType:'PARAGRAPH',visibleText:'No',excludedFromSpeech:true}]}).blocks.length,1));
test('speech document preserves source metadata',()=>{const d=T.createSpeechDocument({sourceType:'LESSON_SUMMARY',sourceId:'s',sourceVersion:'4',title:'Summary',authorized:true,blocks:[]});assert.equal(d.sourceVersion,'4');assert.equal(d.sourceId,'s')});
test('math spoken exactly',()=>assert.equal(T.MathSpeechService.speak('x² + 4x + 4').spokenText,'x squared plus four x plus four.'));
test('unsupported non-English math has fallback',()=>assert.equal(T.MathSpeechService.speak('x²','fr').supported,false));
test('sentence segmentation available',()=>assert.equal(T.segmentSentences('One. Two?').length,2));
test('word highlighting falls back',()=>assert.equal(T.resolveHighlightMode('WORD_WHEN_AVAILABLE').supported,'SENTENCE'));
test('word support honestly unavailable',()=>assert.equal(T.getTextToSpeechCapabilityRegistry().TEXT_TO_SPEECH_WORD_HIGHLIGHT.supportLevel,'NOT_AVAILABLE'));
test('downloads honestly unavailable',()=>assert.equal(T.getTextToSpeechCapabilityRegistry().TEXT_TO_SPEECH_AUDIO_DOWNLOAD.supportLevel,'NOT_AVAILABLE'));
test('download API refuses generation',()=>assert.throws(()=>T.requestDownloadableAudio(),/not available/));
test('manual status remains pending',()=>Object.values(T.getTextToSpeechCapabilityRegistry()).forEach(x=>assert.equal(x.manualTestStatus,'PENDING')));
test('five playback speeds',()=>assert.deepStrictEqual(T.SPEEDS,[75,100,125,150,200]));
test('no autoplay attribute or call',()=>assert(!/autoplay|DOMContentLoaded[^\n]*play\(/i.test(js)));
test('no microphone recording or cloning',()=>assert(!/getUserMedia|SpeechRecognition|MediaRecorder|voice.?clon/i.test(js)));
test('one shared player state',()=>assert(js.includes("const state={status:'IDLE'")));
test('new content stops previous playback',()=>assert(js.includes('if(replacing)stop')));
test('original text notice exists',()=>assert(js.includes('never replaces or hides it')));
test('contextual Listen label exists',()=>assert(js.includes('<span>Listen</span>')));
test('all playback controls exist',()=>['play','pause','resume','stop','previous','next','source'].forEach(x=>assert(js.includes(`data-tts="${x}"`))));
test('highlight overlay is aria hidden',()=>assert(js.includes("overlay.setAttribute('aria-hidden','true')")));
test('highlight ignores pointer input',()=>assert(css.includes('.tts-speech-highlight')&&css.includes('pointer-events:none!important')));
test('player supports safe areas',()=>assert(css.includes('env(safe-area-inset-bottom)')));
test('print hides speech UI',()=>assert(css.includes('.tts-player,.tts-listen-button,.tts-speech-highlight')));
test('preference schema includes highlight',()=>assert(boot.includes('textToSpeechHighlightMode')));
test('device voice stays outside account patch',()=>assert(js.includes('persistDeviceVoice')&&!/updateAccessibilityLanguageProfile\([^)]*browserVoiceURI/.test(js)));
test('no reading history analytics',()=>assert(!/analytics|readingHistory|readingSpeed|trackEvent/.test(js)));
let passed=0;for(const [name,fn] of tests){try{fn();passed++;console.log(`PASS ${name}`)}catch(error){console.error(`FAIL ${name}\n${error.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
