'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const speech=read('text-to-speech.js');
const helper=read('ai-coach-language-tools.js');
const css=read('style.css');
const alignment=read('ai-coach-alignment.css');
const academicStyles=read('academic-coach-support.css');
const html=read('index (2).html');

assert.match(speech,/<svg aria-hidden="true"[^>]*>[\s\S]*<span>Listen<\/span>/,'Listen keeps a visible label and decorative SVG audio icon');
assert.doesNotMatch(speech,/🔊/,'Listen no longer depends on an emoji icon');
assert.match(speech,/button\.onclick=\(\)=>\{try\{activate\(documentFromElement\(element\),element\)/,'Text-to-Speech handler remains connected');
assert.match(speech,/element\.querySelector\('\.tts-listen-button'\)/,'nested Listen control does not duplicate');
assert.match(speech,/AICoachLanguageTools\?\.add\(element,button\)/,'Listen joins the shared response toolbar when available');
assert.match(speech,/sourceId=element\.id\|\|\(element\.dataset\.ttsAnchor\|\|=/,'visible AI messages receive a stable speech source ID');
assert.match(speech,/!node\.closest\('\.ai-coach-language-tools'\)/,'toolbar labels are excluded from speech-source titles');
assert.match(helper,/existingListen=container\.querySelector\(':scope > \.tts-listen-button'\)/,'initial Listen control is absorbed into the toolbar');
assert.match(css,/\.tts-listen-button\{float:none;display:inline-flex;flex:0 0 auto;align-self:flex-start/,'flex-row stretching is neutralized');
assert.match(css,/inline-size:fit-content;max-inline-size:100%;min-block-size:40px/,'button uses natural width and an accessible target');
assert.match(css,/padding:\.48rem \.75rem/,'padding is compact and proportional');
assert.match(css,/white-space:nowrap;overflow:visible/,'short label is not clipped or split');
assert.match(helper,/Preparing Audio/,'panel Listen button exposes a preparing state');
assert.match(helper,/Audio Unavailable/,'panel Listen button exposes an unavailable state');
assert.match(helper,/function listenIconName\(\)/,'panel Listen button changes icon by playback state');
assert.match(alignment,/#coachView #coachLanguageActions\.coach-panel-actions \{[\s\S]*display: grid/,'Language and Presentation actions use a shared grid');
assert.match(alignment,/grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/,'Language and Presentation buttons use equal columns by default');
assert.match(alignment,/@container \(min-width: 481px\) \{[\s\S]*grid-template-columns: repeat\(2, minmax\(170px, 1fr\)\)/,'wide panels use two comfortable action columns');
assert.match(alignment,/@container \(max-width: 480px\) \{[\s\S]*grid-template-columns: 1fr/,'narrow panels stack actions before labels are cramped');
assert.match(alignment,/#coachView #coachLanguageActions\.coach-panel-actions \.tts-listen-button > span:last-child[\s\S]*white-space: nowrap/,'panel Listen label stays on one line');
assert.match(alignment,/#coachView #coachLanguageActions\.coach-panel-actions \.btn svg \{[\s\S]*flex: 0 0 auto/,'panel Listen icon cannot take over text width');
assert.match(academicStyles,/\.ai-coach-fullscreen-button \{[\s\S]*white-space: nowrap/,'Full Screen Chat label also stays on one line');
assert.match(html,/style\.css\?v=study-together-account-gate-v2-20260831/,'current shared styles are loaded');
assert.match(html,/text-to-speech\.js\?v=help-language-tools-redesign-20260830/,'current Text-to-Speech injector is loaded');
assert.match(html,/ai-coach-language-tools\.js\?v=help-guide-step-support-placement-20260831/,'current toolbar helper is loaded');
assert.match(html,/ai-coach-alignment\.css\?v=coach-fullscreen-focus-20260831/,'AI Coach alignment styles are loaded');

console.log('compact Listen button tests passed');
