'use strict';
const assert=require('assert'),J=require('../complete-user-journey-test-runtime.js'),Core=require('../core-decision-rules-runtime.js'),Flow=require('../ai-coach-decision-flow-runtime.js'),Offline=require('../low-bandwidth-offline-runtime.js');let n=0;const ok=(x,m)=>{assert.ok(x,m);n++},eq=(a,b)=>{assert.deepStrictEqual(a,b);n++};
eq(J.SUITE_TITLE,'Complete User-Journey Tests');eq(J.schema,'complete-user-journey-tests/1.0');eq(J.getManifest().length,50);eq(new Set(J.getManifest().map(x=>x.journeyId)).size,50);eq(J.getManifest()[0].journeyId,'UJ-001');eq(J.getManifest()[49].journeyId,'UJ-050');
for(const d of J.getManifest()){for(const k of ['journeyId','title','description','featureArea','minimumMVPStage','requiredRoles','requiredFixtures','preconditions','actionReferences','expectedUIAssertions','expectedAPIAssertions','expectedDatabaseAssertions','expectedAccessibilityAssertions','prohibitedSideEffects','requiredCleanup','requiredTestLayers','testOwner','status','createdAt','updatedAt'])ok(Object.hasOwn(d,k),`${d.journeyId}:${k}`);eq(d.status,'PASSING');ok(d.requiredTestLayers.includes('API-style integration'));}
const results=J.runAll();eq(results.length,50);for(const r of results){for(const k of ['journeyId','journeyTitle','mvpStageOrFeatureArea','preconditions','syntheticFixtureReferences','actions','userVisibleAssertions','serverStateAssertions','dataPersistenceAssertions','privacyAssertions','accessibilityAssertions','prohibitedSideEffectAssertions','result','failureEvidence','testDurationMs','environment'])ok(Object.hasOwn(r,k),`${r.journeyId}:${k}`);eq(r.result,'PASS');eq(r.failureEvidence,null);eq(r.environment,'NODE_IN_MEMORY_INTEGRATION');eq(r.state.disciplineCreated,false);eq(r.state.teacherAlertCreated,false);eq(r.state.parentAlertCreated,false);eq(r.state.prohibitedScores,[]);eq(r.state.rawPrivateAnalytics,false);eq(r.state.hiddenChainOfThoughtStored,false);ok(!!r.state.policyVersionId);ok(!!r.state.safeguardSnapshotId);ok(!!r.state.accessibilityProfileVersion);}
const empty=Object.fromEntries(['visibleResponse','structuredResponse','sourceSection','claimRecords','toolResults','accessibilityNames','liveRegions','captions','transcripts','printableView','downloads','clientState','apiResponse','storedContentReferences','logs','analytics'].map(x=>[x,{}]));const scan=J.scanFinalAnswerSurfaces(empty,['x = 5']);eq(scan.passed,true);eq(scan.inspected.length,16);const leak=J.scanFinalAnswerSurfaces({...empty,liveRegions:'The answer is x = 5'},['x = 5']);eq(leak.passed,false);eq(leak.leaks[0].surface,'liveRegions');eq(J.scanPrivacyCanaries({provider:{message:'redacted'},analytics:{event:'privacy-blocked'},logs:{}},['SYNTHETIC-STUDENT-998']).passed,true);eq(J.scanPrivacyCanaries({provider:{message:'SYNTHETIC-STUDENT-998'}},['SYNTHETIC-STUDENT-998']).passed,false);
eq(J.verifySource({exists:true,identity:true,metadata:true,currentness:'CURRENT',relevant:true,exactClaimSupport:false,citationAllowed:true}).claimSupportStatus,'UNSUPPORTED');eq(J.verifySource({exists:false,relevant:false}).citationPermission,false);
eq(results[4].facts.hiddenSurfaceScan,'PASSED');eq(results[13].facts.exactClaimSupport,false);eq(results[15].facts.authoritativeDisagreement,true);eq(results[21].facts.providerCalled,false);eq(results[30].facts.pointerRequired,false);eq(results[31].facts.ttsAutoplay,false);eq(results[32].facts.academicTerm,'photosynthesis');eq(results[37].facts.deploymentReviewBlocked,true);eq(results[39].facts.privateConversationVisible,false);eq(results[40].facts.studentReasoningRequired,true);eq(results[42].facts.privatePromptVisible,false);eq(results[43].facts.submittedEvidenceDeleted,false);eq(results[44].facts.requiredEvidencePreserved,true);eq(results[45].facts.recordExistenceExposed,false);eq(results[46].facts.finalAnswerLocked,true);eq(results[47].facts.label,'Verification pending internet access.');eq(results[48].facts.silentLastWriteWins,false);eq(results[49].facts.ageInferredFromPresentation,false);
const student={userId:'uj-real-student',tenantId:'uj-real-school',role:'student'};const core=Core.evaluateCoreDecisionRules({idempotencyKey:'uj-047-core',decisionRunId:'uj-047-run',sessionId:'uj-session',policyStatus:'AI_NOT_ALLOWED',policyVersionId:'active-test-v1',taskContextType:'ACTIVE_ASSESSMENT',activeAssessment:true,selectedLearningMode:'DO_NOT_GIVE_ME_THE_FINAL_ANSWER',sourceApplicability:'NO_RELIABLE_SOURCE_CONFIRMED'},student);eq(core.result.finalAnswerLocked,true);ok(core.result.effectiveDeniedCapabilities.includes('GENERATE_FINAL_ANSWER'));eq(core.result.teacherAlertCreated,false);eq(core.result.disciplineCreated,false);
const validation=Flow.validateAICoachDecisionResponse({schemaVersion:'ai-coach-decision/1.1',finalAnswerWithheld:false,confidence:{level:'HIGH'},sources:[]},{locked:true,candidate:{finalAnswerIncluded:true},applicability:'NO_RELIABLE_SOURCE_CONFIRMED',i:{promptInjectionOverride:true,candidateCitations:[]}});eq(validation.serverValidated,false);ok(validation.violations.includes('FINAL_ANSWER_LEAK_DETECTED'));ok(validation.violations.includes('PROMPT_INJECTION_DETECTED'));ok(validation.violations.includes('CONFIDENCE_REPAIR_REQUIRED'));
eq(Offline.validateLowBandwidthOfflineOutput({offline:true,offlineSourceActivity:true,sourceStatus:'Verified',pendingLabel:'Verification pending internet access'}).status,'COMPLETION_BLOCKED');eq(Offline.validateLowBandwidthOfflineOutput({offline:true,offlineSourceActivity:true,sourceStatus:'Pending',pendingLabel:'Verification pending internet access'}).pendingStatus,'Verification pending internet access');
const gate=J.releaseGate(results);eq(gate.journeysPassed,50);eq(gate.skipped,0);eq(gate.flaky,0);eq(gate.status,'BLOCKED');eq(gate.recommendation,'NOT_READY_FOR_PRODUCTION_RELEASE');ok(gate.blockers.includes('browserE2E'));ok(gate.blockers.includes('database'));ok(gate.blockers.includes('migrations'));console.log(`${n}/${n} assertions passed`);
