'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),L=require('../low-bandwidth.js');let n=0;const ok=(x,m)=>{assert.ok(x,m);n++},eq=(a,b)=>{assert.deepStrictEqual(a,b);n++};
(async()=>{const root=path.join(__dirname,'..'),js=fs.readFileSync(path.join(root,'low-bandwidth.js'),'utf8'),css=fs.readFileSync(path.join(root,'low-bandwidth.css'),'utf8'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8');eq(L.CONNECTION_TIMEOUT_MS,5000);eq(L.RESTORED_NOTICE_MS,2000);ok(js.includes("root.StudySparkNotificationConstants?.NOTIFICATION_TOAST_DURATION_MS??2000"));ok(html.indexOf('notification-constants.js')<html.indexOf('low-bandwidth.js'));ok(L.CONNECTION_STATES.includes('CONNECTING'));ok(L.CONNECTION_STATES.includes('AUTHENTICATION_REQUIRED'));ok(html.includes('viewContainer'));ok(html.includes('low-bandwidth.js'));ok(!/if\s*\([^)]*connection[^)]*CONNECTING[^)]*\)\s*\{?\s*return/i.test(js));ok(!js.includes('FullScreenConnectionOverlay'));ok(!css.includes('inset:0'));ok(!css.includes('inset: 0'));ok(css.includes('pointer-events:none'));ok(css.includes('pointer-events:auto'));ok(css.includes('z-index:40'));ok(css.includes('inline-size:min(34rem'));ok(css.includes('@media(max-width:320px)'));ok(css.includes('@media(forced-colors:active)'));ok(css.includes('@media(prefers-reduced-motion:reduce)'));ok(css.includes(':focus-visible'));ok(css.includes('@media print'));
L.setConnectionState('UNKNOWN',{announce:false});eq(L.getConnectionAndSyncStatus().connectionState,'UNKNOWN');eq(L.getOnlineFeatureAvailability('AI_COACH_SEND').navigationAvailable,true);eq(L.getOnlineFeatureAvailability('AI_COACH_SEND').localDraftsEditable,true);
const offline=await L.checkConnection({online:false,fetchImpl:async()=>{throw Error('must not call')}});eq(offline.connectionState,'OFFLINE');const ai=L.getOnlineFeatureAvailability('AI_COACH_SEND');eq(ai.available,false);eq(ai.message,'AI Coach is unavailable offline. Your message remains saved as a draft.');eq(ai.navigationAvailable,true);eq(ai.localDraftsEditable,true);eq(ai.accessibilityAvailable,true);eq(ai.languageSettingsAvailable,true);eq(ai.localProgressSavingAvailable,true);eq(L.getOnlineFeatureAvailability('SOURCE_VERIFICATION').message,'Verification pending internet access.');
const before=L._test.state.checkCount;const online=await L.checkConnection({online:true,healthUrl:'/test-health',fetchImpl:async()=>({ok:true,status:200}),setTimeoutImpl:()=>1,clearTimeoutImpl:()=>{}});eq(online.connectionState,'ONLINE_GOOD');eq(L._test.state.checkCount,before+1);eq(L.getOnlineFeatureAvailability('AI_COACH_SEND').available,true);
const auth=await L.checkConnection({online:true,healthUrl:'/test-health',fetchImpl:async()=>({ok:false,status:401}),setTimeoutImpl:()=>1,clearTimeoutImpl:()=>{}});eq(auth.connectionState,'AUTHENTICATION_REQUIRED');eq(L.getOnlineFeatureAvailability('CLOUD_SYNCHRONIZATION').available,false);
const failed=await L.checkConnection({online:true,healthUrl:'/test-health',fetchImpl:async()=>{throw Error('unreachable')},setTimeoutImpl:()=>1,clearTimeoutImpl:()=>{}});eq(failed.connectionState,'SERVER_UNREACHABLE');
let aborted=false;const controller={signal:{},abort(){aborted=true;this.onabort?.()}};const timed=await L.checkConnection({online:true,healthUrl:'/slow-health',controllerFactory:()=>controller,setTimeoutImpl:fn=>{controller.onabort=fn=>{};queueMicrotask(fn);return 1},clearTimeoutImpl:()=>{},fetchImpl:(_u,{signal})=>new Promise((_resolve,reject)=>{controller.onabort=()=>reject(Object.assign(Error('aborted'),{name:'AbortError'}))})});eq(aborted,true);eq(timed.connectionState,'SERVER_UNREACHABLE');
L.setConnectionState('OFFLINE');const draft=L.saveOfflineDraft({draftType:'AI_COACH_DRAFT',sourceType:'VISIBLE_FORM',sourceId:'connection-test',sourceVersion:'1',fieldId:'message',value:'My saved offline draft'});eq(draft.value,'My saved offline draft');eq(draft.submitted,false);ok(L.listMyOfflineDrafts().some(x=>x.id===draft.id));
for(const feature of ['LIVE_SOURCE_RETRIEVAL','SOURCE_VERIFICATION','CLOUD_SYNCHRONIZATION','FINAL_ASSIGNMENT_SUBMISSION','PUBLIC_SHARING','TEACHER_MESSAGE_SEND'])eq(L.getOnlineFeatureAvailability(feature).available,false);ok(js.includes("root.addEventListener?.('online',onOnline)"));ok(js.includes("root.removeEventListener?.('online',onOnline)"));ok(js.includes("root.addEventListener?.('offline',onOffline)"));ok(js.includes("root.removeEventListener?.('offline',onOffline)"));ok(js.includes('if(listenerCleanup)return listenerCleanup'));ok(!/addEventListener\?\.\('online',[^\n]*setConnection\([^\n]*\)/.test(js));ok(js.includes('aria-live="polite"'));ok(js.includes('data-connection-retry'));ok(js.includes('data-connection-dismiss'));console.log(`${n}/${n} assertions passed`)
})().catch(e=>{console.error(e);process.exitCode=1});
