const fs=require('fs'),path=require('path'),assert=require('assert'),D=require('../dyslexia-display.js'),V=require('../visual-display.js');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8'),js=fs.readFileSync(path.join(root,'dyslexia-display.js'),'utf8'),css=fs.readFileSync(path.join(root,'style.css'),'utf8'),profile=fs.readFileSync(path.join(root,'accessibility-language.js'),'utf8'),boot=fs.readFileSync(path.join(root,'accessibility-toolbar-boot.js'),'utf8');
const tests=[];function test(name,fn){tests.push([name,fn])}
test('module loads after visual display',()=>assert(html.indexOf('visual-display.js')<html.indexOf('dyslexia-display.js')));
test('module loads before toolbar',()=>assert(html.indexOf('dyslexia-display.js')<html.indexOf('accessibility-toolbar.js')));
test('central notice is exact',()=>assert.equal(D.DYSLEXIA_FRIENDLY_DISPLAY_NOTICE,'These reading options may make text more comfortable to use. Different students prefer different combinations. No diagnosis is required, and the settings do not change the academic content of your lessons.'));
test('notice appears in controls',()=>assert(js.includes('${DYSLEXIA_FRIENDLY_DISPLAY_NOTICE}')));
test('same accessibility profile API is reused',()=>assert(js.includes('A.updateAccessibilityLanguageProfile')));
test('same device key is reused',()=>assert(js.includes("studyspark.accessibilityToolbar.v1")));
test('no competing profile name exists',()=>assert(!/DyslexiaProfile|ReadingDisabilityProfile|SpecialNeedsDisplayProfile/.test(js)));
test('all fields are in shared profile defaults',()=>D.FIELDS.forEach(field=>assert(profile.includes(field))));
test('legacy boolean migrates to preset status',()=>assert.equal(D.migrateExistingDyslexiaFriendlyPreferences({dyslexiaFriendlyDisplayEnabled:true}).dyslexiaPresetStatus,'SUGGESTED_PRESET'));
test('legacy boolean migration leaves ruler off',()=>assert.equal(D.migrateExistingDyslexiaFriendlyPreferences({dyslexiaFriendlyDisplayEnabled:true}).readingRulerEnabled,false));
test('legacy boolean migration leaves highlight off',()=>assert.equal(D.migrateExistingDyslexiaFriendlyPreferences({dyslexiaFriendlyDisplayEnabled:true}).currentReadingHighlightMode,'OFF'));
test('legacy migration preserves chosen font',()=>assert.equal(D.migrateExistingDyslexiaFriendlyPreferences({dyslexiaFriendlyDisplayEnabled:true,accessibleFontPreference:'READABLE_SERIF'}).accessibleFontPreference,'READABLE_SERIF'));
test('default does not enable any aid',()=>assert.equal(D.DEFAULTS.readingRulerEnabled,false));
test('default highlight is off',()=>assert.equal(D.DEFAULTS.currentReadingHighlightMode,'OFF'));
test('preset sets explicit spacing',()=>assert.equal(D.PRESET.wordSpacingPreference,'RELAXED'));
test('preset sets explicit line height',()=>assert.equal(D.PRESET.lineSpacing,'EXPANDED'));
test('preset sets explicit content width',()=>assert.equal(D.PRESET.contentWidth,'SHORT'));
test('preset sets logical alignment',()=>assert.equal(D.PRESET.readingAlignment,'READING_DIRECTION_START'));
test('preset sets paragraph spacing',()=>assert.equal(D.PRESET.paragraphSpacing,'EXPANDED'));
test('preset reduces italics',()=>assert.equal(D.PRESET.reduceItalicText,true));
test('preset reduces decorative fonts',()=>assert.equal(D.PRESET.disableDecorativeFonts,true));
test('preset reduces clutter',()=>assert.equal(D.PRESET.reduceVisualClutter,true));
test('preset does not contain font',()=>assert(!('accessibleFontPreference'in D.PRESET)));
test('preset does not contain ruler',()=>assert(!('readingRulerEnabled'in D.PRESET)));
test('preset does not contain highlight',()=>assert(!('currentReadingHighlightMode'in D.PRESET)));
test('preset does not contain TTS',()=>assert(!('textToSpeechPreference'in D.PRESET)));
test('preset does not change academic presentation',()=>assert(!('readingPresentationMode'in D.PRESET)));
test('word spacing validates independently',()=>assert.equal(D.validateDyslexiaFriendlyPreferences({wordSpacingPreference:'EXPANDED'}).wordSpacingPreference,'EXPANDED'));
test('ruler validates independently',()=>assert.equal(D.validateDyslexiaFriendlyPreferences({readingRulerEnabled:true}).readingRulerEnabled,true));
test('font validates independently',()=>assert.equal(D.validateDyslexiaFriendlyPreferences({accessibleFontPreference:'HUMANIST_SANS'}).accessibleFontPreference,'HUMANIST_SANS'));
test('highlight validates independently',()=>assert.equal(D.validateDyslexiaFriendlyPreferences({currentReadingHighlightMode:'CURRENT_LINE'}).currentReadingHighlightMode,'CURRENT_LINE'));
test('invalid word spacing rejected',()=>assert.throws(()=>D.validateDyslexiaFriendlyPreferences({wordSpacingPreference:'HUGE'})));
test('invalid font rejected',()=>assert.throws(()=>D.validateDyslexiaFriendlyPreferences({accessibleFontPreference:'REMOTE_URL'})));
test('invalid ruler boolean rejected',()=>assert.throws(()=>D.validateDyslexiaFriendlyPreferences({readingRulerEnabled:'yes'})));
test('invalid tracking mode rejected',()=>assert.throws(()=>D.validateDyslexiaFriendlyPreferences({readingRulerTrackingMode:'AUTO_GUESS'})));
test('device snapshot is allowlisted',()=>assert.deepStrictEqual(Object.keys(D.toDyslexiaDevicePreferenceSnapshot(D.DEFAULTS)).sort(),D.FIELDS.slice().sort()));
test('device fields exclude identity',()=>['userId','email','diagnosis','medicalRecord','guardian','courseGrade','token','readingHistory','readingSpeed'].forEach(field=>assert(!D.FIELDS.includes(field))));
test('root word-spacing token exists',()=>assert(css.includes('--studyspark-word-spacing')));
test('relaxed word spacing is CSS only',()=>assert(css.includes('[data-word-spacing="RELAXED"]')));
test('expanded word spacing is CSS only',()=>assert(css.includes('[data-word-spacing="EXPANDED"]')));
test('source text receives no inserted spaces',()=>assert(!js.includes('textContent.replace')));
test('language-aware spacing exclusions exist',()=>assert(css.includes(':lang(ar),:lang(zh),:lang(ja),:lang(ko),:lang(he),:lang(hi)')));
test('code and math exclude word spacing',()=>assert(css.includes('code,pre,kbd,samp,.math,[data-math]')));
test('forms and tables exclude word spacing',()=>assert(css.includes('table,input,select,textarea')));
test('logical reading alignment remains in Step 5',()=>assert(css.includes('text-align:start!important')));
test('four font choices are available',()=>assert.equal(D.listAvailableReadingFonts().length,4));
test('no special font is falsely exposed',()=>assert(!D.listAvailableReadingFonts().some(font=>font.code==='APPROVED_DYSLEXIA_FRIENDLY_FONT')));
test('fonts report licensing status',()=>D.listAvailableReadingFonts().forEach(font=>assert(font.licensed)));
test('font registry exposes no raw file paths',()=>assert(!/\.woff|\.ttf|file:\/\//i.test(JSON.stringify(D.FONT_REGISTRY))));
test('font URLs cannot be selected',()=>assert.throws(()=>D.validateReadingFontPreference('https://example.com/font','en')));
test('RTL uses system fallback for Latin-only font',()=>assert.equal(D.getFontCapabilityForLanguage('HUMANIST_SANS','ar').fallbackFrom,'HUMANIST_SANS'));
test('system font supports Arabic fallback',()=>assert(D.getFontCapabilityForLanguage('SYSTEM','ar').supportedScripts.includes('Arabic')));
test('code and math fonts are never replaced',()=>assert(css.includes('font-family:revert')));
test('reduced italics is scoped',()=>assert(css.includes('[data-reduce-italics="true"] :is(')));
test('semantic em is not globally normalized',()=>assert(!/em\s*\{[^}]*font-style:normal!important/.test(css)));
test('decorative font reduction is scoped',()=>assert(css.includes('[data-decorative-fonts="REDUCED"]')));
test('visual clutter has independent root state',()=>assert(boot.includes('visualClutter:p.reduceVisualClutter')));
test('visual clutter hides named decoration only',()=>assert(css.includes('[data-visual-clutter="REDUCED"]')));
test('highlight overlay is aria hidden',()=>assert(js.includes("setAttribute('aria-hidden','true')")));
test('highlight overlay is not focusable',()=>assert(js.includes('el.tabIndex=-1')));
test('highlight overlay ignores pointer events',()=>assert(css.includes('pointer-events:none!important')));
test('line geometry uses Range',()=>assert(js.includes('document.createRange()')));
test('line geometry falls back to paragraph',()=>assert(js.includes("fallback:mode==='CURRENT_LINE'")));
test('reading blocks exclude code math tables and forms',()=>assert(js.includes("closest('pre,code,.math,[data-math],table,form")));
test('geometry uses animation frame scheduling',()=>assert(js.includes('requestAnimationFrame')));
test('resize recalculates geometry',()=>assert(js.includes("addEventListener('resize',schedule")));
test('scroll recalculates geometry',()=>assert(js.includes("addEventListener('scroll',schedule")));
test('font loading recalculates geometry',()=>assert(js.includes('document.fonts?.ready.then(schedule)')));
test('ruler overlay is aria hidden',()=>assert(js.includes("ensureOverlay('readingRulerOverlay'")));
test('ruler overlay ignores pointer events',()=>assert(css.includes('.reading-focus-overlay,.reading-ruler-overlay')));
test('ruler has three styles',()=>['HIGHLIGHT_BAND','FOCUS_STRIP','DIM_SURROUNDING_CONTENT'].forEach(value=>assert(profile.includes(value))));
test('ruler has three sizes',()=>assert(profile.includes("readingRulerSize:['SMALL','MEDIUM','LARGE']")));
test('manual movement does not persist',()=>assert(js.includes('function moveRuler(pixels){state.rulerOffset+=pixels;schedule()}')));
test('ruler coordinates are not in persisted fields',()=>assert(!D.FIELDS.includes('rulerOffset')));
test('controller is a named group',()=>assert(js.includes("setAttribute('aria-label','Reading ruler controls')")));
test('controller uses real buttons',()=>assert(js.includes('<button type="button" data-aid="previous"')));
test('no dragging is required',()=>assert(!/dragstart|draggable|pointermove/.test(js)));
test('no global arrow shortcut exists',()=>assert(!/addEventListener\('keydown'[^\n]*Arrow(Up|Down)/.test(js)));
test('controller can hide without disabling ruler',()=>assert(js.includes('collapseController()')&&js.includes('Show reading ruler controls')));
test('ruler can be turned off directly',()=>assert(js.includes("data-aid=\"off\"")));
test('ruler is excluded from print',()=>assert(css.includes('@media print{.reading-focus-overlay,.reading-ruler-overlay')));
test('ruler respects forced colours',()=>assert(css.includes('@media(forced-colors:active){.reading-focus-overlay,.reading-ruler-overlay')));
test('TTS follow is honestly unavailable',()=>assert.equal(D.getDyslexiaDisplayCapabilityRegistry().READING_RULER_TTS_FOLLOW.availability,'UNAVAILABLE'));
test('current line is honestly partial',()=>assert.equal(D.getDyslexiaDisplayCapabilityRegistry().CURRENT_LINE_HIGHLIGHT.availability,'PARTIAL'));
test('ruler manual tests remain pending',()=>assert.equal(D.getDyslexiaDisplayCapabilityRegistry().READING_RULER.manualTestStatus,'PENDING'));
test('capability registry has sixteen codes',()=>assert.equal(Object.keys(D.getDyslexiaDisplayCapabilityRegistry()).length,16));
test('section reset wording preserves unrelated preferences',()=>assert(js.includes('Language, captions, speech, bandwidth, Study Room preferences, account, and progress will stay unchanged.')));
test('reset one option API exists',()=>assert.equal(typeof D.resetMyDyslexiaFriendlyDisplayField,'function'));
test('section reset API exists',()=>assert.equal(typeof D.resetMyDyslexiaFriendlyDisplayPreferences,'function'));
test('development seeds include ruler only',()=>assert(D.seedDevelopmentData().some(seed=>seed.name==='Ruler only'&&seed.values.readingRulerEnabled)));
test('development seeds are isolated',()=>D.seedDevelopmentData().forEach(seed=>assert.equal(seed.developmentOnly,true)));
test('Step 5 content contract is reused',()=>assert.equal(typeof V.validateVisualModeContentEquivalence,'function'));
test('preset preserves source inventory',()=>{const source={lessonBlockIds:['l1'],learningObjectiveIds:['o1'],quizQuestionIds:['q1'],answerOptionIds:['a1'],safetyNoticeIds:['s1'],primaryActionIds:['submit']};assert(V.validateVisualModeContentEquivalence(source,{...source}).valid)});
test('custom view preserves source inventory',()=>{const source={requiredInstructionIds:['i1'],requiredDownloadIds:['d1']};assert(V.validateVisualModeContentEquivalence(source,{...source}).valid)});
test('ruler only preserves source inventory',()=>{const source={lessonBlockIds:['l1'],equationIds:['e1']};assert(V.validateVisualModeContentEquivalence(source,{...source}).valid)});
test('line highlight only preserves source inventory',()=>{const source={codeExampleIds:['c1'],feedbackIds:['f1']};assert(V.validateVisualModeContentEquivalence(source,{...source}).valid)});
test('reduced clutter cannot omit safety',()=>assert(!V.validateVisualModeContentEquivalence({safetyNoticeIds:['s1']},{safetyNoticeIds:[]}).valid));
test('font only cannot omit academic integrity',()=>assert(!V.validateVisualModeContentEquivalence({academicIntegrityNoticeIds:['a1']},{academicIntegrityNoticeIds:[]}).valid));
test('account preferences merge at initialization',()=>assert(js.includes('accountPatch[key]=account[key]')));
test('no analytics records reading position',()=>assert(!/analytics|readingSpeed|readingHistory|trackEvent/.test(js)));
test('no medical claim terms in controls',()=>assert(!/treats dyslexia|improves grades|clinically proven/i.test(js)));
test('no microphone or camera access added',()=>assert(!/getUserMedia|SpeechRecognition/.test(js)));
let passed=0;for(const [name,fn]of tests){try{fn();passed++;console.log(`PASS ${name}`)}catch(error){console.error(`FAIL ${name}\n${error.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
