'use strict';const assert=require('assert'),A=require('../human-agency-lesson.js');let n=0;const ok=(v,m)=>{assert.ok(v,m);n++},eq=(a,b,m)=>{assert.deepStrictEqual(a,b,m);n++},throws=(f,c)=>{assert.throws(f,e=>e.code===c);n++};
const student={userId:'student-1',tenantId:'school-a',role:'student'},other={userId:'student-2',tenantId:'school-b',role:'student'};
eq(A._test.lesson.title,'Who Is Doing the Thinking?');eq(A._test.lesson.pathway,'UNDERSTAND');eq(A._test.lesson.primaryCompetencyBlockId,'competency-1');eq(A._test.lesson.phases,['LEARN','OBSERVE','PRACTISE','EXPLAIN','APPLY','REFLECT']);ok(A._test.lesson.secondaryCompetencyBlockIds.includes('competency-2'));ok(A._test.lesson.secondaryCompetencyBlockIds.includes('competency-5'));ok(A._test.lesson.secondaryCompetencyBlockIds.includes('competency-8'));ok(A._test.lesson.completionDoesNotAwardCompetency);
for(const s of ['STUDENT_LED','STUDENT_LED_WITH_PERMITTED_AI_SUPPORT','GUIDED_REVISION_NEEDED','INSUFFICIENT_STUDENT_CONTRIBUTION','ANSWER_REPLACING_SUPPORT','POLICY_CLARIFICATION_REQUIRED','ACTIVE_ASSESSMENT_RESTRICTED','INSUFFICIENT_INFORMATION','DESCRIPTION_CONFLICTING'])ok(A.AILiteracyHumanAgencyAssessmentStatus.includes(s));
for(const s of ['CHOSE_GOAL','SELECTED_TOPIC','GATHERED_EVIDENCE','EVALUATED_SOURCES','VERIFIED_FACTS','DESIGNED_METHOD','CONDUCTED_EXPERIMENT','CREATED_ARGUMENT','WROTE_INITIAL_DRAFT','REVISED_DRAFT','MADE_FINAL_DECISION','EXPLAINED_REASONING'])ok(A.AILiteracyStudentContributionType.includes(s));
for(const s of ['BRAINSTORMED_OPTIONS','ASKED_GUIDING_QUESTIONS','EXPLAINED_CONCEPT','SUGGESTED_STRUCTURE','REVIEWED_STUDENT_DRAFT','GENERATED_COMPLETE_RESPONSE','SUGGESTED_SOURCES','GENERATED_CITATION','PROVIDED_ACCESSIBILITY_SUPPORT','TRANSLATED_TEXT'])ok(A.AILiteracyAIContributionType.includes(s));
for(const s of ['SOURCE_CHECK_NEEDED','CITATION_CHECK_NEEDED','CALCULATION_CHECK_NEEDED','TEACHER_POLICY_CONFIRMATION_NEEDED','HUMAN_EXPERT_REVIEW_NEEDED'])ok(A.AILiteracyHumanAgencyVerificationRequirement.includes(s));
for(const s of ['ALLOWED','ALLOWED_WITH_STUDENT_CONTRIBUTION','ALLOWED_WITH_DISCLOSURE','LIMITED_SCOPE_ONLY','TEACHER_APPROVAL_REQUIRED','PROHIBITED_FOR_THIS_TASK','ACTIVE_ASSESSMENT_RESTRICTED','POLICY_UNKNOWN','POLICY_CONFLICTING','POLICY_OUTDATED'])ok(A.AILiteracyAssignmentAIUsePolicyStatus.includes(s));
for(const phrase of ['AI may support','meaningful student decisions','people and institutions remain responsible','ask rather than assume','does not make prohibited','need to verify','appropriate human review'])ok(Object.values(A.COPY).some(x=>x.includes(phrase)),phrase);
eq(A._test.scenarios.length,8);for(const s of A._test.scenarios){ok(s.syntheticScenario);ok(s.safeAlternative);ok(s.competencyBlockIds.includes('competency-1'));ok(s.competencyBlockIds.includes('competency-2'));ok(s.competencyBlockIds.includes('competency-5'));ok(s.supportedLanguages.includes('en'));ok(s.readingLevelVariants.includes('PLAIN'))}
const safe=A.listHumanAgencyScenarios(student);eq(safe.length,8);for(const s of safe){eq(s.acceptedAgencyStatuses,undefined);eq(s.acceptedReasoningRules,undefined);eq(s.hiddenAcceptedRules,false)}
const base={idempotencyKey:'r1',lessonSessionId:'session-1',phaseProgressId:'practice',scenarioId:'human-agency-science-fair',scenarioVersion:1,selectedStudentContributionTypes:['SELECTED_FINAL_IDEA','GATHERED_EVIDENCE','EVALUATED_SOURCES','DESIGNED_METHOD','MADE_FINAL_DECISION'],selectedAIContributionTypes:['BRAINSTORMED_OPTIONS'],selectedVerificationRequirements:['SOURCE_CHECK_NEEDED'],selectedDisclosureStatus:'REQUIRED_BY_ASSIGNMENT_POLICY',selectedPolicyStatus:'ALLOWED_WITH_DISCLOSURE',selectedResponsibilityRoles:['STUDENT_OR_USER','SHARED_RESPONSIBILITY'],selectedAgencyStatus:'STUDENT_LED_WITH_PERMITTED_AI_SUPPORT',optionalExplanation:'The student chose, researched, designed, and remains responsible.'};
const r=A.submitHumanAgencyInitialResponse(base,student);eq(r.feedback.status,'STUDENT_AGENCY_PRESERVED');eq(r.competencyAwarded,false);eq(r.response.private,true);eq(r.response.modelTraining,false);eq(r.response.sharedAutomatically,false);const dup=A.submitHumanAgencyInitialResponse(base,student);eq(dup.duplicatePrevented,true);throws(()=>A.toHumanAgencyResponseOwnerView(r.response,other),'OWNERSHIP_DENIED');
const hint=A.requestHumanAgencyHint({scenarioId:base.scenarioId,responseId:r.response.id},student);eq(hint.revealsAcceptedRules,false);eq(hint.penaltyApplied,false);const rev=A.reviseHumanAgencyResponse({...base,idempotencyKey:'rev1',responseId:r.response.id},student);eq(rev.initialPreserved,true);eq(rev.penaltyApplied,false);
const unknown=A.evaluateHumanAgencyPolicyFit({policyStatus:'POLICY_UNKNOWN'},student);eq(unknown.teacherClarificationNeeded,true);eq(unknown.policyInvented,false);const prohibited=A.evaluateHumanAgencyPolicyFit({policyStatus:'PROHIBITED_FOR_THIS_TASK'},student);eq(prohibited.permitted,false);eq(prohibited.safeAlternativeRequired,true);const draft=A.createHumanAgencyTeacherClarificationDraft({assistance:'AI outlining'},student);eq(draft.sent,false);ok(draft.draft.includes('clarify'));const disclosure=A.generateHumanAgencyDisclosureDraft({toolName:'StudySpark',assistance:'brainstorm topics',studentWork:'selected, researched, and wrote the work'},student);eq(disclosure.permissionCreated,false);eq(disclosure.shared,false);
const explanation=A.saveHumanAgencyExplanation({idempotencyKey:'ex1',lessonSessionId:'session-1',text:'Scenario A preserves decisions and research; Scenario B replaces the required writing.'},student).record;const plan=A.saveAIAssistancePlan({idempotencyKey:'plan1',lessonSessionId:'session-1',fictional:true,fields:{decisions:['topic','conclusion'],aiMay:'guiding questions',aiMustNot:'write final',verify:'sources',policy:'unknown',disclosure:'brainstorming',responsibility:'student'}},student).record;const reflection=A.saveHumanAgencyReflection({idempotencyKey:'ref1',lessonSessionId:'session-1',text:'I will keep the reasoning and ask when policy is unclear.'},student).record;ok(explanation.private);ok(plan.fictional);ok(reflection.private);
const responseIds=[r.response.id];for(const [j,id,status,ai] of [[2,'human-agency-draft-review','STUDENT_LED_WITH_PERMITTED_AI_SUPPORT',['REVIEWED_STUDENT_DRAFT']],[3,'human-agency-speech-to-text','STUDENT_LED',['PROVIDED_ACCESSIBILITY_SUPPORT']]]){const s=A._test.scenarios.find(x=>x.id===id),x=A.submitHumanAgencyInitialResponse({...base,idempotencyKey:`r${j}`,scenarioId:id,selectedAgencyStatus:status,selectedAIContributionTypes:ai,selectedStudentContributionTypes:s.acceptedStudentContributionTypes,selectedVerificationRequirements:s.acceptedVerificationRequirements,selectedPolicyStatus:'ALLOWED'},student);responseIds.push(x.response.id)}
const ev=A.generateHumanAgencyEvidenceCandidate({idempotencyKey:'ev1',responseIds,explanationId:explanation.id,planId:plan.id},student);eq(ev.automaticCompetencyAward,false);eq(ev.candidate.competencyStatusAssigned,false);eq(ev.candidate.lessonVersion,1);ok(ev.candidate.studentContribution.length);ok(ev.candidate.aiSupportUsed.length);const accepted=A.acceptHumanAgencyEvidenceCandidate({evidenceId:ev.candidate.id,summary:'My private Human Agency evidence.'},student);eq(accepted.competencyStatusAssigned,false);eq(accepted.candidate.validityStatus,'STUDENT_CONFIRMED');
const cached=A.getCachedHumanAgencyLesson(student);eq(cached.offline,true);eq(cached.policySourceStatus,'REVALIDATE_ON_RECONNECT');const off=A.saveHumanAgencyOfflineResponse({ownerUserId:student.userId,scenarioId:base.scenarioId,scenarioVersion:1,response:{draft:true}},student);eq(off.teacherMessageSent,false);throws(()=>A.saveHumanAgencyOfflineResponse({ownerUserId:other.userId,scenarioId:base.scenarioId,scenarioVersion:1,response:{}},other),'OFFLINE_ACCOUNT_MISMATCH');const sync=A.synchronizeHumanAgencyOfflineSession({idempotencyKey:'sync1',lessonVersion:1},student);eq(sync.policySourceRevalidated,true);eq(sync.duplicateResponsesPrevented,true);eq(sync.duplicateEvidencePrevented,true);eq(sync.competencyStatusAssigned,false);
eq(A.toTutorView().automaticAccess,false);eq(A.toParentView().automaticAccess,false);eq(A.toAdministratorView().individualResponses,false);const tp=A.toHumanAgencyTeacherPreviewView();eq(tp.studentResponsesIncluded,false);eq(tp.plansIncluded,false);eq(tp.disclosuresIncluded,false);for(const f of A.HumanAgencyFeatureFlag)ok(A.getHumanAgencyLessonCapabilities(student)[f.split('_').slice(4,-1).join('').toLowerCase()]!==null||f.length>0);
for(const event of ['LESSON_OPENED','HUMAN_AGENCY_ACTIVITY_STARTED','SCENARIO_ATTEMPTED','LESSON_PAUSED','LESSON_COMPLETED','EVIDENCE_CANDIDATE_REVIEWED','LOW_BANDWIDTH_LESSON_USED','ACCESSIBILITY_FORMAT_USED'])eq(A.createPrivacySafeHumanAgencyAnalyticsEvent(event).privateContentIncluded,false);throws(()=>A.createPrivacySafeHumanAgencyAnalyticsEvent('EXPLANATION_CAPTURED'),'ANALYTICS_EVENT_REJECTED');
const fs=require('fs'),html=fs.readFileSync(require('path').join(__dirname,'..','index (2).html'),'utf8'),css=fs.readFileSync(require('path').join(__dirname,'..','human-agency-lesson.css'),'utf8'),js=fs.readFileSync(require('path').join(__dirname,'..','human-agency-lesson.js'),'utf8');ok(html.includes('human-agency-lesson.js'));ok(html.includes('human-agency-lesson.css'));for(const x of ['<th scope="col">','<th scope="row">','Scenario A','Scenario B','Map the Thinking','Create My AI-Assistance Plan','Speech-to-Text','Prefer Not to Write a Personal Reflection'])ok(js.includes(x));for(const x of ['@media(max-width:32rem)','focus-visible','forced-colors','prefers-reduced-motion','[dir="rtl"]','.low-bandwidth'])ok(css.includes(x));ok(!js.includes('ownership percentage'));ok(!js.includes('AI detector proves'));ok(!js.includes('automatic cheating'));console.log(`${n}/${n} assertions passed`);
