const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8'),app=fs.readFileSync(path.join(root,'script.js'),'utf8'),baseline=fs.readFileSync(path.join(root,'accessibility-baseline.js'),'utf8'),keyboard=fs.readFileSync(path.join(root,'keyboard-accessibility.js'),'utf8'),css=fs.readFileSync(path.join(root,'style.css'),'utf8'),api=require('../keyboard-accessibility.js');
const tests=[];function test(name,fn){tests.push([name,fn])}
test('keyboard layer is loaded after baseline',()=>assert(html.indexOf('accessibility-baseline.js')<html.indexOf('keyboard-accessibility.js')));
test('no positive tabindex ships in page markup',()=>assert(!/tabindex\s*=\s*["'][1-9]/i.test(html)));
test('flashcard has one activation path',()=>assert(!app.includes("$('#flashcard').addEventListener('keydown'")));
test('flashcard receives button semantics',()=>assert(keyboard.includes("setAttribute('role','button')")));
test('flashcard Enter and Space use the click path once',()=>assert(keyboard.includes("event.key!=='Enter'&&event.key!==' '")&&keyboard.includes('card.click()')));
test('flashcard accessible name describes state',()=>assert(keyboard.includes('Reveal flashcard answer')&&keyboard.includes('Show flashcard question')));
test('note cards lose nested button semantics',()=>assert(keyboard.includes("card.removeAttribute('role')")&&keyboard.includes("card.removeAttribute('tabindex')")));
test('note action trigger has contextual name',()=>assert(keyboard.includes('Actions for ${title}')));
test('note menu is exposed as menu',()=>assert(keyboard.includes("menu.setAttribute('role','menu')")));
test('note menu children are menuitems',()=>assert(keyboard.includes("setAttribute('role','menuitem')")));
test('menu trigger advertises popup',()=>assert(keyboard.includes("setAttribute('aria-haspopup','menu')")));
test('escape closes only the active menu',()=>assert(keyboard.includes("event.target.closest('[role=\"menu\"]')")));
test('escape restores focus to menu trigger',()=>assert(keyboard.includes('trigger?.focus()')));
test('tab groups receive tablist role',()=>assert(keyboard.includes("setAttribute('role','tablist')")));
test('tabs expose selected state',()=>assert(keyboard.includes("setAttribute('aria-selected'")));
test('tabs use roving tabindex',()=>assert(keyboard.includes('tab.tabIndex=selected?0:-1')));
test('tabs control named panels',()=>assert(keyboard.includes("setAttribute('aria-controls'")));
test('panels reference their tabs',()=>assert(keyboard.includes("setAttribute('aria-labelledby'")));
test('right arrow moves within tabs',()=>assert(keyboard.includes("event.key==='ArrowRight'")));
test('left arrow moves within tabs',()=>assert(keyboard.includes("event.key==='ArrowLeft'")));
test('home and end are supported in tabs',()=>assert(keyboard.includes("event.key==='Home'")&&keyboard.includes("event.key==='End'")));
test('tab arrow handlers prevent page movement',()=>assert(keyboard.includes('event.preventDefault()')));
test('route change focuses the new heading',()=>assert(baseline.includes('if(changed&&heading&&!activeModal)')));
test('initial route does not steal focus',()=>assert(baseline.includes('lastViewId!==null')));
test('route heading is programmatically focusable',()=>assert(baseline.includes('heading.tabIndex=-1')));
test('route title still updates',()=>assert(baseline.includes('document.title=')));
test('skip link focuses active route heading',()=>assert(keyboard.includes("document.querySelector('.skip-link')")));
test('generic names gain card context',()=>assert(keyboard.includes('`${name} ${context}`')));
test('dynamic content is repaired',()=>assert(keyboard.includes('new MutationObserver')));
test('audit flags positive tabindex',()=>assert.deepStrictEqual(api.auditMarkup('<button tabindex="2">Save</button>'),['positive-tabindex']));
test('audit flags clickable non-native elements',()=>assert(api.auditMarkup('<div role="button">Go</div>').includes('non-native-control')));
test('audit flags exact generic names',()=>assert(api.auditMarkup('<button>Open</button>').includes('context-free-name')));
test('audit allows contextual accessible name',()=>assert(!api.auditMarkup('<button aria-label="Open Biology notes">Open</button>').includes('context-free-name')));
test('audit allows native descriptive controls',()=>assert.deepStrictEqual(api.auditMarkup('<button>Open Biology notes</button>'),[]));
test('global focus indicator remains present',()=>assert(/:focus-visible/.test(css)));
test('reduced motion remains present',()=>assert(/prefers-reduced-motion:\s*reduce/.test(css)));
let passed=0;for(const [name,fn] of tests){try{fn();passed++;console.log(`PASS ${name}`)}catch(error){console.error(`FAIL ${name}\n${error.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
