const fs=require('fs'),path=require('path'),assert=require('assert'),E=require('../explanation-levels.js'),P=require('../plain-language.js');
const root=path.join(__dirname,'..'),js=fs.readFileSync(path.join(root,'explanation-levels.js'),'utf8'),css=fs.readFileSync(path.join(root,'explanation-levels.css'),'utf8'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8'),tests=[],test=(n,f)=>tests.push([n,f]);
const source={...P.seedDevelopmentData()[0].source,sourceId:'levels-photosynthesis'},levels=E.EXPLANATION_LEVELS;
test('script loads after Step 10',()=>assert(html.indexOf('plain-language.js')<html.indexOf('explanation-levels.js')));
test('stylesheet loaded',()=>assert(html.includes('explanation-levels.css')));
test('canonical four levels',()=>assert.deepStrictEqual(levels,['LEVEL_1_BEGINNER','LEVEL_2_SIMPLE','LEVEL_3_STANDARD_ACADEMIC','LEVEL_4_ADVANCED']));
test('exact labels',()=>assert.deepStrictEqual(Object.values(E.EXPLANATION_LEVEL_LABELS),['Level 1: Beginner','Level 2: Simple','Level 3: Standard Academic','Level 4: Advanced']));
test('canonical structures',()=>assert.deepStrictEqual(E.EXPLANATION_STRUCTURES,['STANDARD','STEP_BY_STEP','GLOSSARY_FIRST','EXAMPLE_FIRST']));
test('Beginner maps Level 1',()=>assert.equal(E.STEP_10_MODE_MAP.LEVEL_1_BEGINNER,'BEGINNER_FRIENDLY'));
test('Plain maps Level 2',()=>assert.equal(E.STEP_10_MODE_MAP.LEVEL_2_SIMPLE,'PLAIN_LANGUAGE'));
test('Standard maps Level 3',()=>assert.equal(E.STEP_10_MODE_MAP.LEVEL_3_STANDARD_ACADEMIC,'STANDARD_ACADEMIC'));
test('Detailed maps Level 4',()=>assert.equal(E.STEP_10_MODE_MAP.LEVEL_4_ADVANCED,'DETAILED_TECHNICAL'));
test('step by step is structure',()=>assert(!levels.includes('STEP_BY_STEP_ACADEMIC')));
for(const level of levels)test(`${level} generates`,()=>assert.equal(E.generateExplanationLevel(source,{level}).level,level));
test('generated directly from original',()=>levels.forEach(level=>assert.equal(E.generateExplanationLevel(source,{level}).generatedDirectlyFromOriginal,true)));
test('same source version',()=>levels.forEach(level=>assert.equal(E.generateExplanationLevel(source,{level}).sourceVersion,'1')));
test('same academic level',()=>levels.forEach(level=>assert.equal(E.generateExplanationLevel(source,{level}).academicLevel,source.academicLevel)));
test('same course or grade',()=>levels.forEach(level=>assert.equal(E.generateExplanationLevel(source,{level}).courseOrGrade,source.courseOrGrade)));
test('same learning objective',()=>levels.forEach(level=>assert.equal(E.generateExplanationLevel(source,{level}).learningObjective,source.learningObjective)));
test('original remains available',()=>levels.forEach(level=>assert(E.generateExplanationLevel(source,{level}).originalAvailable)));
test('previous levels remain cached',()=>assert.equal(E.generateExplanationLevel(source,{level:levels[3]}).availableLevels.length,4));
test('cached level id stable',()=>assert.equal(E.generateExplanationLevel(source,{level:levels[0]}).id,E.generateExplanationLevel(source,{level:levels[0]}).id));
test('academic equivalence not claimed',()=>levels.forEach(level=>assert.equal(E.generateExplanationLevel(source,{level}).academicEquivalenceClaimed,false)));
test('validation passed',()=>levels.forEach(level=>assert.equal(E.generateExplanationLevel(source,{level}).validationStatus,'PASSED')));
test('required term remains visible',()=>levels.forEach(level=>assert(/photosynthesis/i.test(E.generateExplanationLevel(source,{level}).adaptation.structuredOutput.blocks.map(x=>x.text).join(' ')))));
test('simpler decrements one level',()=>assert.equal(E._test.simpler(levels[2]),levels[1]));
test('simpler stops at Level 1',()=>assert.equal(E._test.simpler(levels[0]),levels[0]));
test('detail increments one level',()=>assert.equal(E._test.detailed(levels[1]),levels[2]));
test('detail stops at Level 4',()=>assert.equal(E._test.detailed(levels[3]),levels[3]));
test('invalid level rejected',()=>assert.throws(()=>E.generateExplanationLevel(source,{level:'ABILITY_LOW'}),/Unsupported/));
test('invalid structure rejected',()=>assert.throws(()=>E.generateExplanationLevel(source,{structure:'EASY'}),/Unsupported/));
test('step structure supported',()=>assert.equal(E.generateExplanationLevel({...source,sourceId:'step'},{level:levels[2],structure:'STEP_BY_STEP'}).structure,'STEP_BY_STEP'));
test('glossary structure supported',()=>assert.equal(E.generateExplanationLevel({...source,sourceId:'glossary'},{level:levels[2],structure:'GLOSSARY_FIRST'}).structure,'GLOSSARY_FIRST'));
test('unapproved example fails honestly',()=>assert.throws(()=>E.requestApprovedExample({...source,sourceId:'no-example'},levels[1]),/No approved example/));
test('prototype does not fabricate approved example',()=>assert.throws(()=>E.requestApprovedExample({...source,sourceId:'approved-example',allowedExampleTransformations:['approved']},levels[1]),/not available/));
test('active answer protection inherited',()=>assert.throws(()=>E.generateExplanationLevel({...source,sourceId:'active',assessmentContext:'ACTIVE_ASSESSMENT',containsAnswer:true}),/answers/));
test('high-stakes protection inherited',()=>assert.throws(()=>E.generateExplanationLevel({...source,sourceId:'legal',highStakesType:'LEGAL'}),/human-reviewed/));
test('unauthorized source rejected',()=>assert.throws(()=>E.generateExplanationLevel({...source,sourceId:'denied',authorized:false}),/denied/));
test('capability count',()=>assert.equal(Object.keys(E.getExplanationLevelCapabilities()).length,10));
test('manual tests pending',()=>Object.values(E.getExplanationLevelCapabilities()).forEach(x=>assert.equal(x.manualTestStatus,'PENDING')));
test('local provider disclosed',()=>assert.equal(E.getExplanationLevelCapabilities().ADJUSTABLE_EXPLANATION_LEVELS.provider,'DETERMINISTIC_LOCAL'));
test('semantic provider absent',()=>assert.equal(E.getExplanationLevelCapabilities().ADJUSTABLE_EXPLANATION_LEVELS.semanticEquivalenceProvider,false));
test('examples unavailable',()=>assert.equal(E.getExplanationLevelCapabilities().LEVEL_EXAMPLES.supportLevel,'NOT_AVAILABLE'));
test('multilingual unavailable',()=>assert.equal(E.getExplanationLevelCapabilities().MULTILINGUAL_EXPLANATION_LEVELS.supportLevel,'NOT_AVAILABLE'));
test('selector label present',()=>assert(js.includes('<h2 id="explanationLevelTitle">Explanation level</h2>')));
test('required quick actions present',()=>['Make Simpler','Add More Detail','Show an Example'].forEach(x=>assert(js.includes(x))));
test('original control present',()=>assert(js.includes('Show Original')));
test('comparison control present',()=>assert(js.includes('Compare Levels')));
test('AI-generated label present',()=>assert(js.includes('AI-generated ${escape(view.levelLabel)}')));
test('explicit default confirmation',()=>assert(js.includes('Save ${LABELS[level]} as your default explanation level?')));
test('temporary generation does not save',()=>assert(!/function generate[\s\S]{0,1500}savePlainLanguageModeAsDefault/.test(js)));
test('TTS integration',()=>assert(js.includes('TextToSpeech.startTextToSpeech')));
test('no cumulative adaptation source',()=>assert(js.includes('P.generatePlainLanguageExplanation(source,{mode})')&&!js.includes('generateExplanationLevel(view.adaptation')));
test('no ability inference',()=>assert(!/you are a beginner|weak student|low ability|intelligence level|reading ability/i.test(js)));
test('no analytics history',()=>assert(!/trackEvent|dataLayer|advertis|levelUseHistory/.test(js)));
test('no consequential scoring',()=>assert(!/gradePrediction|tutorMatching|fraudScore|safetyScore|integrityScore|serviceApproval|helpCreditDecision/.test(js)));
test('comparison reflows',()=>assert(css.includes('grid-template-columns:1fr')));
test('forced colours supported',()=>assert(css.includes('@media(forced-colors:active)')));
test('minimum target size',()=>assert(css.includes('min-block-size:44px')));
test('safe area supported',()=>assert(css.includes('safe-area-inset-top')));
test('print hides level UI',()=>assert(css.includes('@media print')));
test('source invalidation API',()=>assert.equal(typeof E.invalidateExplanationLevelsForSource,'function'));
test('development fixture remains synthetic',()=>P.seedDevelopmentData().forEach(x=>assert(x.developmentOnly)));
let passed=0;for(const[n,f]of tests){try{f();passed++;console.log(`PASS ${n}`)}catch(e){console.error(`FAIL ${n}\n${e.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
