const fs=require('fs'),path=require('path'),assert=require('assert'),L=require('../language-bridge.js'),E=require('../explanation-levels.js');
const root=path.join(__dirname,'..'),js=fs.readFileSync(path.join(root,'language-bridge.js'),'utf8'),css=fs.readFileSync(path.join(root,'language-bridge.css'),'utf8'),html=fs.readFileSync(path.join(root,'index (2).html'),'utf8'),tests=[],test=(n,f)=>tests.push([n,f]),source=L.seedDevelopmentData()[0].source;
const make=(mode='ENGLISH_THEN_BRIDGE',level='LEVEL_3_STANDARD_ACADEMIC',id=mode+level)=>L.requestLanguageBridgeExplanation({...source,sourceId:id},{languageBridgeMode:mode,bridgeLanguageCode:mode==='ENGLISH_ONLY'?null:'zh-Hans',explanationLevel:level});
test('loads after explanation levels',()=>assert(html.indexOf('explanation-levels.js')<html.indexOf('language-bridge.js')));test('stylesheet loaded',()=>assert(html.includes('language-bridge.css')));
test('six canonical modes',()=>assert.deepStrictEqual(L.LANGUAGE_BRIDGE_MODES,['ENGLISH_ONLY','BRIDGE_LANGUAGE_ONLY','ENGLISH_THEN_BRIDGE','BRIDGE_THEN_ENGLISH','SIDE_BY_SIDE_BILINGUAL','ENGLISH_WITH_TRANSLATED_KEYWORDS']));
test('six exact labels',()=>assert.deepStrictEqual(Object.values(L.LANGUAGE_BRIDGE_MODE_LABELS),['English only','Home language only','English first, then home language','Home language first, then English','Side-by-side bilingual','English with translated keywords']));
test('unknown mode rejected',()=>assert.throws(()=>L.requestLanguageBridgeExplanation(source,{languageBridgeMode:'TRANSLATE'}),/Unsupported/));
test('unknown language rejected',()=>assert.throws(()=>L.requestLanguageBridgeExplanation(source,{languageBridgeMode:'SIDE_BY_SIDE_BILINGUAL',bridgeLanguageCode:'xx'}),/Unsupported/));
test('bridge language required only on request',()=>assert.throws(()=>L.requestLanguageBridgeExplanation(source,{languageBridgeMode:'SIDE_BY_SIDE_BILINGUAL'}),/Choose/));
test('English Only needs no profile language',()=>assert.equal(make('ENGLISH_ONLY').status,'READY'));
for(const mode of L.LANGUAGE_BRIDGE_MODES)test(`${mode} valid`,()=>assert.equal(make(mode).languageBridgeMode,mode));
test('English terminology language fixed to en',()=>assert.equal(make().academicTerminologyLanguageCode,'en'));
test('bridge language separate field',()=>assert.equal(make().bridgeLanguageCode,'zh-Hans'));
test('policy version stored',()=>assert.equal(make().policyVersion,'2026.1'));
test('terminology version stored',()=>assert.equal(make().terminologyRegistryVersion,'2026.1'));
test('contract hash stored',()=>assert(make().academicContractHash));
test('source version stored',()=>assert.equal(make().sourceVersion,'1'));
test('generated directly from original',()=>assert.equal(make().generatedDirectlyFromOriginal,true));
test('original English preserved',()=>assert.equal(make().originalEnglish,source.text));
test('original remains available',()=>assert.equal(make().originalAvailable,true));
test('required notice exact',()=>assert.equal(L.LANGUAGE_BRIDGE_AI_NOTICE,'AI-generated translations may contain mistakes. Keep the English academic terms visible and check important names, numbers, formulas, technical terms, and instructions against the original English version.'));
test('not certified',()=>assert.equal(make().translationCertified,false));
test('not falsely human reviewed',()=>assert.equal(make().humanReviewed,false));
test('photosynthesis English exact',()=>assert.equal(make().englishText,'Photosynthesis is the process plants use to convert light energy into chemical energy.'));
test('photosynthesis Chinese exact',()=>assert.equal(make().bridgeText,'光合作用是植物将光能转化为化学能的过程。'));
for(const [en,zh] of [['Photosynthesis','光合作用'],['Light energy','光能'],['Chemical energy','化学能'],['Chlorophyll','叶绿素']])test(`${en} term pair`,()=>{const t=make().glossary.find(x=>x.englishTerm===en);assert(t);assert.equal(t.bridgeTerm,zh)});
test('English terms remain Home Language Only',()=>['Photosynthesis','Light energy','Chemical energy','Chlorophyll'].forEach(x=>assert(make('BRIDGE_LANGUAGE_ONLY').glossary.some(t=>t.englishTerm===x))));
test('English first section order',()=>{const s=L._test.sections(make('ENGLISH_THEN_BRIDGE'));assert(s.indexOf('>English<')<s.indexOf('中文解释'))});
test('bridge first section order',()=>{const s=L._test.sections(make('BRIDGE_THEN_ENGLISH'));assert(s.indexOf('中文解释')<s.indexOf('>English<'))});
test('side-by-side semantic pair',()=>assert(L._test.sections(make('SIDE_BY_SIDE_BILINGUAL')).includes('language-bridge-pair')));
test('keyword mode remains English',()=>assert.equal(make('ENGLISH_WITH_TRANSLATED_KEYWORDS').bridgeText,null));
test('keyword mode attaches translation',()=>assert(L._test.keywordText(make('ENGLISH_WITH_TRANSLATED_KEYWORDS')).includes('Photosynthesis (光合作用)')));
test('glossary uses approved source',()=>make().glossary.forEach(x=>assert.equal(x.source,'ORGANIZATION_GLOSSARY')));
test('glossary review status',()=>make().glossary.forEach(x=>assert.equal(x.translationReviewStatus,'APPROVED_GLOSSARY')));
test('general translation fails safely',()=>assert.throws(()=>L.requestLanguageBridgeExplanation({...source,sourceId:'general',fixtureKey:null,text:'A different approved explanation.'},{languageBridgeMode:'SIDE_BY_SIDE_BILINGUAL',bridgeLanguageCode:'zh-Hans'}),/original/));
test('unsupported full French fails safely',()=>assert.throws(()=>L.requestLanguageBridgeExplanation({...source,sourceId:'fr'},{languageBridgeMode:'SIDE_BY_SIDE_BILINGUAL',bridgeLanguageCode:'fr'}),/original English/));
test('active assessment blocked',()=>assert.throws(()=>L.requestLanguageBridgeExplanation({...source,sourceId:'active',assessmentContext:'ACTIVE_ASSESSMENT'},{languageBridgeMode:'SIDE_BY_SIDE_BILINGUAL',bridgeLanguageCode:'zh-Hans'}),/limited/));
test('high stakes AI-only blocked',()=>assert.throws(()=>L.requestLanguageBridgeExplanation({...source,sourceId:'policy',highStakesType:'OFFICIAL_POLICY'},{languageBridgeMode:'SIDE_BY_SIDE_BILINGUAL',bridgeLanguageCode:'zh-Hans'}),/Official English/));
test('required English term validator passes',()=>assert.equal(L.validateRequiredEnglishTerms(make()).status,'PASSED'));
test('missing English term validator fails',()=>{const a={...make(),requiredEnglishTerms:['Missing term'],glossary:[]};assert.equal(L.validateRequiredEnglishTerms(a).status,'FAILED_REQUIRED_ENGLISH_TERM')});
test('back translation not proof',()=>assert.equal(L.validateLanguageBridgeArtifact(L._test.artifacts.values().next().value).backTranslationUsedAsProof,false));
for(const level of E.EXPLANATION_LEVELS)test(`${level} bridge uses same level`,()=>assert.equal(make('SIDE_BY_SIDE_BILINGUAL',level).explanationLevel,level));
test('level is not derived from translation',()=>assert(js.includes('englishFor(source,explanationLevel)')&&!js.includes('generateExplanationLevel(bridgeText')));
test('same block carries both languages',()=>{const b=make('SIDE_BY_SIDE_BILINGUAL').structuredOutput.blocks[0];assert(b.english.text);assert(b.bridge.text);assert.deepStrictEqual(b.sourceElementIds,['source-main'])});
test('English block lang and dir',()=>{const s=L._test.sections(make());assert(s.includes('lang="en" dir="ltr"'))});
test('Chinese block lang',()=>assert(L._test.sections(make()).includes('lang="zh-Hans"')));
test('Arabic configured RTL',()=>assert.equal(L.SUPPORTED_BRIDGE_LANGUAGES.find(x=>x.code==='ar').dir,'rtl'));
test('no flags in selector',()=>assert(!/🇨🇳|🇫🇷|🇸🇦|flag/i.test(js)));
test('neutral bridge language label',()=>assert(js.includes('Home or bridge language')));
test('explicit default confirmation',()=>assert(js.includes('as your default Language Bridge mode?')));
test('temporary request does not save',()=>assert(!/function request[\s\S]{0,2500}localStorage\.setItem/.test(js)));
test('TTS English integration',()=>assert(js.includes('Listen to English explanation')));
test('TTS bridge integration',()=>assert(js.includes('Listen to bridge-language explanation')));
test('speech does not autoplay',()=>assert(!/show\([^)]*\)[\s\S]{0,120}startTextToSpeech/.test(js)));
test('report action privacy-safe',()=>assert(js.includes('No explanation text was sent')));
test('ten honest capabilities',()=>assert.equal(Object.keys(L.getLanguageBridgeCapabilities()).length,10));
test('manual status pending',()=>Object.values(L.getLanguageBridgeCapabilities()).forEach(x=>assert.equal(x.manualTestStatus,'PENDING')));
test('general translation unavailable',()=>assert.equal(L.getLanguageBridgeCapabilities().GENERAL_FULL_TRANSLATION.supportLevel,'NOT_AVAILABLE'));
test('semantic equivalence unavailable',()=>assert.equal(L.getLanguageBridgeCapabilities().SEMANTIC_TRANSLATION_EQUIVALENCE.supportLevel,'NOT_AVAILABLE'));
test('certified translation unavailable',()=>assert.equal(L.getLanguageBridgeCapabilities().CERTIFIED_TRANSLATION.supportLevel,'NOT_AVAILABLE'));
test('no nationality inference',()=>assert(!/inferNationality|countryOfOrigin|immigrationStatus|englishProficiencyScore|ELLStatus|ESLStatus/.test(js)));
test('no consequential use',()=>assert(!/tutorMatching|gradePrediction|fraudScore|safetyScore|integrityScore|serviceApproval|helpCreditDecision/.test(js)));
test('responsive stacked layout',()=>assert(css.includes('grid-template-columns:1fr')));
test('forced colours supported',()=>assert(css.includes('@media(forced-colors:active)')));
test('RTL logical alignment',()=>assert(css.includes('[dir="rtl"]{text-align:start}')));
test('formula direction isolated',()=>assert(css.includes('unicode-bidi:isolate')));
test('44px controls',()=>assert(css.includes('min-block-size:44px')));
test('safe areas',()=>assert(css.includes('safe-area-inset-top')));
test('print excludes bridge UI',()=>assert(css.includes('@media print')));
test('source invalidation API',()=>assert.equal(typeof L.invalidateLanguageBridgeArtifacts,'function'));
test('fixtures development only',()=>L.seedDevelopmentData().forEach(x=>assert(x.developmentOnly)));
let passed=0;for(const[n,f]of tests){try{f();passed++;console.log(`PASS ${n}`)}catch(e){console.error(`FAIL ${n}\n${e.stack}`);process.exitCode=1}}console.log(`${passed}/${tests.length} tests passed`);
